begin;
create temporary table wsqa as select array_agg(id order by created_at) users,gen_random_uuid() ticket,gen_random_uuid() client,gen_random_uuid() product,gen_random_uuid() task,gen_random_uuid() dm,gen_random_uuid() ownpost,gen_random_uuid() general,gen_random_uuid() reply,gen_random_uuid() threaded,gen_random_uuid() upload,gen_random_uuid() mention,gen_random_uuid() ticketconv,gen_random_uuid() ticketmention from (select id,created_at from public.profiles where active order by created_at limit 3) p;
insert into public.tickets(id,cliente,responsable) select ticket,'QA rollback only','Inicial' from wsqa;
insert into public.clientes(id,nombre,telefono) select client,'QA rollback only','111' from wsqa;
insert into public.productos(id,ticket_id,descripcion,cantidad,precio) select product,ticket,'QA',1,100 from wsqa;
insert into public.tareas(id,ticket_id,descripcion,tipo,responsable,area,estado) select task,ticket,'CORTAR','produccion','Inicial','planeacion','pendiente' from wsqa;
insert into public.chat_conversations(id,kind,member_a,member_b) select dm,'direct',least(users[1],users[2]),greatest(users[1],users[2]) from wsqa on conflict(member_a,member_b) do nothing;
update wsqa set dm=(select id from public.chat_conversations where kind='direct' and member_a=least(users[1],users[2]) and member_b=greatest(users[1],users[2]));
insert into public.chat_conversations(id,kind,ticket_id) select ticketconv,'ticket',ticket from wsqa;
insert into public.team_posts(id,author_user_id,author_name_snapshot,text) select ownpost,users[1],'QA','Publicación propia' from wsqa;
insert into public.team_posts(id,author_user_id,author_name_snapshot,text,mentions_all) select general,users[2],'QA','Mensaje general',true from wsqa;
insert into public.team_posts(id,author_user_id,author_name_snapshot,text,reply_to_id) select reply,users[2],'QA','Respuesta',ownpost from wsqa;
insert into public.team_posts(id,author_user_id,author_name_snapshot,text,thread_root_id) select threaded,users[2],'QA','Comentario',ownpost from wsqa;
insert into public.team_posts(id,author_user_id,author_name_snapshot,text,conversation_id,file_storage_path) select upload,users[2],'QA','',dm,dm::text||'/qa.pdf' from wsqa;
insert into public.team_posts(id,author_user_id,author_name_snapshot,text,mentions) select mention,users[2],'QA','Mención',jsonb_build_array(jsonb_build_object('id',users[1]::text)) from wsqa;
insert into public.team_posts(id,author_user_id,author_name_snapshot,text,conversation_id,mentions) select ticketmention,users[2],'QA','Mención ticket',ticketconv,jsonb_build_array(jsonb_build_object('id',users[1]::text)) from wsqa;
do $$declare x record;begin select * into x from wsqa;
 assert public.chat_notification_kind_for_user(x.general,x.users[1]) is null;
 assert public.chat_notification_kind_for_user(x.ownpost,x.users[1]) is null;
 assert public.chat_notification_kind_for_user(x.reply,x.users[1])='respuesta';
 assert public.chat_notification_kind_for_user(x.threaded,x.users[1])='respuesta';
 assert public.chat_notification_kind_for_user(x.threaded,x.users[3]) is null;
 assert public.chat_notification_kind_for_user(x.upload,x.users[1])='personal';
 assert public.chat_notification_kind_for_user(x.upload,x.users[3]) is null;
 assert public.chat_notification_kind_for_user(x.mention,x.users[1])='mencion';
 assert public.chat_notification_kind_for_user(x.ticketmention,x.users[1])='mencion';
 assert not has_function_privilege('anon','public.workspace_patch_record(text,uuid,jsonb,jsonb)','execute');
 assert not has_function_privilege('authenticated','public.chat_notification_kind_for_user(uuid,uuid)','execute');
end $$;
grant select on wsqa to authenticated;
select set_config('request.jwt.claim.sub',(select users[1]::text from wsqa),true);
set local role authenticated;
do $$declare x record; r jsonb;begin select * into x from wsqa;
 r:=public.workspace_patch_record('tickets',x.ticket,'{"responsable":"Actual"}','{"responsable":"Inicial"}'); assert r->>'responsable'='Actual';
 r:=public.workspace_patch_record('tickets',x.ticket,'{"cliente":"Editado aparte"}','{"cliente":"QA rollback only"}'); assert r->>'responsable'='Actual';
 begin perform public.workspace_patch_record('tickets',x.ticket,'{"responsable":"Viejo"}','{"responsable":"Inicial"}');raise exception 'stale overwrite accepted';exception when serialization_failure then null;end;
 r:=public.workspace_patch_record('clientes',x.client,'{"telefono":"222"}','{"telefono":"111"}');assert r->>'telefono'='222';
 r:=public.workspace_patch_record('clientes',x.client,'{"nombre":"Editado"}','{"nombre":"QA rollback only"}');assert r->>'telefono'='222';
 begin perform public.workspace_patch_record('clientes',x.client,'{"telefono":"333"}','{"telefono":"111"}');raise exception 'stale phone accepted';exception when serialization_failure then null;end;
 r:=public.workspace_patch_record('productos',x.product,'{"precio":200}','{"precio":100}');assert (r->>'precio')::numeric=200;
 r:=public.workspace_patch_record('productos',x.product,'{"cantidad":2}','{"cantidad":1}');assert (r->>'precio')::numeric=200;
 begin perform public.workspace_patch_record('productos',x.product,'{"precio":300}','{"precio":100}');raise exception 'stale product accepted';exception when serialization_failure then null;end;
 r:=public.workspace_patch_record('tareas',x.task,'{"responsable":"Actual"}','{"responsable":"Inicial"}');
 r:=public.workspace_patch_record('tareas',x.task,'{"estado":"en_proceso"}','{"estado":"pendiente"}');assert r->>'responsable'='Actual';
 assert public.set_ticket_delivery_dates_checked(x.ticket,'{"fecha_compromiso":null}','2026-10-10');
 begin perform public.set_ticket_delivery_dates_checked(x.ticket,'{"fecha_compromiso":null}','2026-10-11');raise exception 'stale date accepted';exception when serialization_failure then null;end;
 begin perform public.workspace_patch_record('tickets',x.ticket,'{"visibility":"private"}','{"visibility":"team"}');raise exception 'forbidden field accepted';exception when raise_exception then assert sqlerrm='Invalid field';end;
end $$;
reset role;
rollback;

