const fs=require('fs'),assert=require('assert'),{chromium}=require('playwright');
const wa=fs.existsSync(__dirname+'/wa-inbox-qa.cjs')?'wa-inbox-qa.cjs':'CHAT-INBOX-QA.cjs',mobile=fs.existsSync(__dirname+'/mobile-app-qa.cjs')?'mobile-app-qa.cjs':'MOBILE-APP-QA.cjs';
let fixture=fs.readFileSync(__dirname+'/'+wa,'utf8').match(/const fixture=`([\s\S]*?)`;/)[1];fixture=fixture.slice(0,fixture.lastIndexOf('render();'))+fs.readFileSync(__dirname+'/'+mobile,'utf8').match(/fixture=fixture.slice[^`]+`([\s\S]*?)`;/)[1]+`
STATE.profiles.push({id:'israel',displayName:'Israel',active:true},{id:'alex',displayName:'Alex',active:true});
STATE.tickets[0].cliente='Ana Cliente';STATE.tickets[1].cliente='Bruno Cliente';STATE.tickets[0].queSigue='Texto obsoleto';STATE.tickets[0].markers=[{id:'oldmarker',type:'imprimir'},{id:'urgent',type:'urgente'}];
window.writes=[];window.failWrite=false;
sb.from=table=>{var row=null;var q={insert(r){row=r;writes.push({table,op:'insert',row:r});return q;},update(r){row=r;writes.push({table,op:'update',row:r});return q;},eq(){return q;},select(){return q;},single(){return Promise.resolve({data:{id:'newmarker'},error:null});},then(resolve){resolve({data:null,error:failWrite?{message:'fallo de prueba'}:null});}};return q;};
sb.rpc=async(name,args)=>{writes.push({rpc:name,args});if(name==='workspace_patch_record')writes.push({table:args.p_table,row:args.p_patch,op:'update'});return {data:!failWrite,error:failWrite?{message:'fallo de prueba'}:null};};
Object.assign(qa,{workDefaultArea,WORK_TASK_NAMES,WORK_LABELS,activeMarkers,ticketFinancials,renderAccountMenu,openMarkerToggle,openCellEditor,openZonePicker,astraReviewOverlay,UI});UI.ticketsView='kanban';qa.view('tickets');
`;
fixture+='Object.assign(qa,{VALLEY_CITIES,valleyPoint,valleyLabels,pirateCatArt});';
let html=fs.readFileSync(__dirname+'/index.html','utf8').replace(/<script[^>]*src=[^>]*><\/script>/g,'').replace(/\bboot\(\);(?=\s*\n\}\)\(\);)/,fixture);html=html.replace('<script>','<script>'+fs.readFileSync(__dirname+'/ops-menu.js','utf8')+'</script><script>');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_BIN||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.setDefaultTimeout(7000);page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.abort());await page.setContent(html);
await page.evaluate(()=>qa.openZonePicker('t0'));const geo=await page.evaluate(()=>{var point=id=>{var c=qa.VALLEY_CITIES.find(x=>x.id===id);return qa.valleyPoint(c.lat,c.lon);};return {mc:point('mcallen'),brown:point('brownsville'),mat:point('matamoros'),island:point('south_padre_island'),port:point('port_isabel'),labels:qa.valleyLabels()};});assert(geo.mc.x<geo.brown.x&&geo.mc.y<geo.brown.y);assert(geo.mat.y>geo.brown.y);assert(geo.island.x>geo.port.x);const boxes=Object.values(geo.labels);assert(!boxes.some((a,i)=>boxes.some((b,j)=>i!==j&&a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y)),'City labels overlap');assert(boxes.every(b=>b.x>=0&&b.x+b.w<=1100&&b.y>=0&&b.y+b.h<=620));await page.locator('[data-valley="in"]').click();assert.equal(await page.locator('.valley-map').evaluate(n=>n.getBoundingClientRect().width),1375);await page.locator('[data-valley="reset"]').click();const svg=await page.locator('.valley-map').evaluate(n=>n.outerHTML);const preview=await browser.newPage({viewport:{width:1100,height:620}});await preview.setContent('<style>body{margin:0}svg{display:block}</style>'+svg);await preview.screenshot({path:__dirname+'/valley-map-preview.png'});await preview.close();await page.locator('[data-action="zone-picker-close"]').click();
const arts=await page.evaluate(()=>['celebrate','ack','im_in','love','laugh','surprised','oh_no'].map(k=>qa.pirateCatArt(k,28)));assert.equal(new Set(arts).size,7);assert(arts.every(s=>s.includes('pirate-cat')&&!s.includes('wa-emoji')));await page.evaluate(arts=>{var p=document.createElement('div');p.id='cat-preview';p.style='padding:28px;display:flex;gap:20px;background:#17212b;color:white;border-radius:18px;position:fixed;top:80px;left:20px;z-index:999';var labels=['Lo logramos','Enterado','Yo me encargo','Me encanta','Jajaja','Wow','No puede ser'];p.innerHTML=arts.map((a,i)=>'<div style="text-align:center">'+a.replace(/width="28" height="28"/,'width="64" height="64"')+'<p style="font-size:12px">'+labels[i]+'</p>'+a+'</div>').join('');document.body.appendChild(p);},arts);await page.locator('#cat-preview').screenshot({path:__dirname+'/pirate-cats-preview.png'});await page.locator('#cat-preview').evaluate(n=>n.remove());
assert.deepEqual(errors,[]);
 assert.equal(await page.locator('.work-discover').isVisible(),false);assert.equal(await page.locator('.kanban-card-quesigue-cell').count(),0);assert.equal(await page.getByText('Texto obsoleto',{exact:true}).count(),0);
 await page.locator('#search-input').fill('Ana');assert.equal(await page.locator('.kanban-card').count(),1);assert.equal(await page.locator('#workspace-search').inputValue(),'Ana');assert.equal(await page.locator('#kanban-board .kanban-column').count(),1);
 await page.locator('#workspace-search').fill('Bruno');assert.equal(await page.locator('.kanban-card').count(),1);assert.equal(await page.locator('#search-input').inputValue(),'Bruno');await page.locator('#workspace-search').fill('');assert.equal(await page.locator('.kanban-card').count(),18);
 await page.locator('.tickets-explorer').dispatchEvent('wheel',{deltaY:-100});assert(await page.locator('.work-discover').isVisible());await page.getByRole('button',{name:'Mostrar vistas y filtros'}).click();assert.equal(await page.locator('.work-discover').isVisible(),false);
 await page.locator('[data-kanban-card="t0"] .work-labels').click();assert.equal(await page.locator('.work-label-picker button').count(),8);assert.equal(await page.locator('.work-label-picker').getByText('Imprimir',{exact:true}).count(),0);await page.getByRole('button',{name:'Cerrar',exact:true}).last().click();
 await page.evaluate(()=>{const t=qa.STATE.tickets[0];t.entregadoAt='2026-10-01T12:00:00Z';t.pagos=[{monto:100}];qa.render();});assert((await page.locator('[data-kanban-card="t0"] .work-labels').textContent()).includes('ENTREGADO PENDIENTE POR PAGAR'));await page.evaluate(()=>{qa.STATE.tickets[0].pagos=[{monto:200}];qa.render();});assert((await page.locator('[data-kanban-card="t0"] .work-labels').textContent()).includes('PAGADO Y ENTREGADO'));
 const chooserPromise=page.waitForEvent('filechooser');await page.locator('[data-kanban-card="t1"] .work-add-photo').click();const chooser=await chooserPromise;await chooser.setFiles({name:'photo.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jX1sAAAAASUVORK5CYII=','base64')});assert(await page.locator('#tickets-thumb-photo-overlay').isVisible());await page.evaluate(()=>{qa.UI.photoBatch=null;qa.render();});
 const qaDateBaseline=await page.evaluate(()=>qa.STATE.tickets[0].fechaCompromiso||null);await page.locator('[data-kanban-card="t0"] [data-workspace="dates"]').click();assert(await page.locator('#work-date-promised').isEditable());assert.equal(await page.locator('#work-date-event').isVisible(),false);await page.locator('.dc-optional summary').click();assert(await page.locator('#work-date-event').isEditable());await page.locator('#work-date-promised').fill('2026-10-10');await page.locator('#work-date-event').fill('2026-10-11');await page.getByRole('button',{name:'Guardar fechas'}).click();await page.waitForFunction(()=>qa.STATE.tickets[0].fechaEvento==='2026-10-11');assert.deepEqual(await page.evaluate(()=>writes.find(w=>w.rpc==='set_ticket_delivery_dates_checked').args),{p_ticket_id:'t0',p_expected:{fecha_compromiso:qaDateBaseline,fecha_evento:null,fechas_auxiliares:[]},p_delivery:'2026-10-10',p_event:'2026-10-11',p_auxiliary:[],p_update_optional:true});
 await page.evaluate(()=>qa.openZonePicker('t0'));assert.equal(await page.locator('.work-map [role="button"]').count(),26);await page.locator('#work-city-search').fill('Edinburg');assert.equal(await page.locator('.work-city-list button:visible').count(),1);await page.locator('.work-city-list button:visible').click();await page.waitForFunction(()=>qa.STATE.tickets[0].deliveryZone==='edinburg');assert(await page.evaluate(()=>writes.some(w=>w.table==='tickets'&&w.row.delivery_zone==='edinburg')));
 await page.locator('[data-kanban-card="t0"] .kanban-add-task').click();assert.equal(await page.locator('#ops-f-resp').inputValue(),'Martin');assert.equal(await page.locator('#ops-f-area').inputValue(),'planeacion');assert.equal(await page.locator('.ops-editor details,.ops-editor input[type=date],.ops-editor input[type=range],.ops-menu').count(),0);assert.equal(await page.locator('#ops-f-desc option').count(),23);
 await page.locator('#ops-f-resp').selectOption({label:'Israel'});assert.equal(await page.locator('#ops-f-area').inputValue(),'produccion');await page.locator('#ops-f-resp').selectOption({label:'Alexia'});assert.equal(await page.locator('#ops-f-area').inputValue(),'planeacion');await page.locator('#ops-f-resp').selectOption({label:'Alex'});assert.equal(await page.locator('#ops-f-area').inputValue(),'produccion');await page.locator('#ops-f-area').selectOption('planeacion');await page.locator('#ops-f-desc').selectOption({label:'ENVIAR DTF'});await page.getByRole('button',{name:'Crear tarea',exact:true}).click();await page.waitForFunction(()=>qa.STATE.tickets[0].tareas.some(t=>t.desc==='ENVIAR DTF'));const created=await page.evaluate(()=>qa.STATE.tickets[0].tareas.find(t=>t.desc==='ENVIAR DTF'));assert.equal(created.area,'planeacion');assert.equal(created.responsable,'Alex');
 await page.evaluate(id=>qa.openOpsEditor('edit',id,'t0'),created.id);await page.locator('#ops-f-resp').selectOption({label:'Israel'});assert.equal(await page.locator('#ops-f-area').inputValue(),'planeacion');await page.getByRole('button',{name:'Guardar',exact:true}).click();assert.equal(await page.evaluate(id=>qa.STATE.tickets[0].tareas.find(t=>t.id===id).area,created.id),'planeacion');
 await page.evaluate(()=>qa.view('operaciones'));assert.equal(await page.locator('#ops-board').count(),0);assert.equal(await page.getByRole('heading',{name:'Tareas',exact:true}).count(),1);assert.equal(await page.locator('.work-task-row').count(),19);await page.getByRole('tab',{name:'Producción',exact:true}).click();assert.equal(await page.locator('.work-task-row').count(),0);await page.getByRole('tab',{name:'Activas',exact:true}).click();
 await page.evaluate(()=>failWrite=true);await page.getByRole('button',{name:'Terminar ENVIAR DTF',exact:true}).click();await page.waitForFunction(()=>qa.STATE.tickets[0].tareas.find(t=>t.desc==='ENVIAR DTF').estado==='pendiente');assert.equal(await page.locator('.work-task-row').count(),19);await page.evaluate(()=>failWrite=false);await page.getByRole('button',{name:'Terminar ENVIAR DTF',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('[data-work-task="'+qa.STATE.tickets[0].tareas.find(t=>t.desc==='ENVIAR DTF').id+'"]'));assert.equal(await page.locator('.work-task-row').count(),18);await page.getByRole('tab',{name:'Terminadas',exact:true}).click();assert.equal(await page.locator('.work-task-row').count(),1);
 await page.evaluate(()=>{qa.UI.accountMenuOpen=true;qa.render();});assert(await page.locator('#work-default-area').isVisible());await page.locator('#work-default-area').selectOption('produccion');await page.getByRole('button',{name:'Guardar destino',exact:true}).click();await page.waitForFunction(()=>qa.workDefaultArea('Martin')==='produccion');assert.equal(await page.evaluate(()=>qa.STATE.tickets[0].tareas[0].area),'planeacion');
 for(const width of [320,390,768]){await page.setViewportSize({width,height:844});await page.evaluate(()=>{qa.UI.accountMenuOpen=false;qa.UI.workToolsOpen=false;qa.view('tickets');});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('.work-discover').isVisible(),false);await page.evaluate(()=>qa.view('operaciones'));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{qa.view('tickets');});await page.screenshot({path:__dirname+'/workspace-kanban-mobile.png'});await page.evaluate(()=>qa.view('operaciones'));await page.getByRole('tab',{name:'Activas',exact:true}).click();await page.screenshot({path:__dirname+'/workspace-tasks-mobile.png'});assert.deepEqual(errors,[]);
 console.log('PASS: shared search and empty columns, hidden tools/reveal, 8 labels and real financial delivery state, empty photo upload, atomic dates, 26 map cities, fixed task catalogue and defaults, manual creation destination and edit preservation, list views, completion rollback/disappearance, per-user preference and 320/390/768px.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});


