(function(root){'use strict';
var bridge,panel,context,owner,controller,revision=0,filesByKey=new Map(),queue=[],state,previewObservers=[];
var labels={logos:'Logos',corel:'CorelDRAW',pdf:'PDF',fotos:'Fotografías',recursos:'Recursos',otros:'Otros'};
var stages={Draft:'Borrador',Proof:'Prueba',Approved:'Aprobado','Print Ready':'Listo para producción',Archived:'Archivado'};
var friendly={LIBRARY_DISABLED:'La biblioteca todavía no está habilitada.',WORKSPACE_IDENTITY_REQUIRED:'Vincula tu cuenta Workspace para abrir los originales.',LIBRARY_IDENTITY_CHANGE_REQUIRES_ADMIN:'Tu cuenta Google cambió. Un administrador debe revisar los accesos anteriores.',LIBRARY_FOLDER_SHARED:'La carpeta de la biblioteca tiene permisos compartidos que necesitan revisión.',LIBRARY_FOLDER_CONNECTION_CHANGED:'La cuenta propietaria de Drive cambió. Un administrador debe revisar las carpetas.',ASSET_SCOPE_MISMATCH:'Esta versión pertenece a otro trabajo. Abre su biblioteca para subir una versión.',NATIVE_EXPIRY_UNCONFIRMED:'Google no confirmó el vencimiento del acceso. No abrimos el archivo.',LIBRARY_PREEXISTING_ACCESS:'Ya existe un permiso de Google para este archivo. Un administrador debe revisarlo.',ORIGINAL_CHANGED_EXTERNALLY:'El archivo cambió o se movió en Drive. Conservamos el registro; necesita revisión.',FILE_HASH_REQUIRED:'No pudimos verificar el archivo.',UPLOAD_BUSY_OR_EXPIRED:'La sesión venció o está ocupada. Revisa la carga antes de crear otra.',WORKSPACE_DOMAIN_MISMATCH:'Usa tu cuenta del Workspace del negocio.'};
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function size(n){return n>=1073741824?(n/1073741824).toFixed(2)+' GB':n>=1048576?(n/1048576).toFixed(1)+' MB':(n/1024).toFixed(0)+' KB';}
function error(e){return friendly[e.code]||(e.name==='AbortError'?'Carga pausada. Puedes reanudarla.':e.code?root.DTGWorkspaceAPI.message(e):e.message)||'No pudimos completar la operación.';}
function storageKey(){return 'dtg-library-manifest:'+owner+':'+context.customerId+':'+(context.ticketId||'general');}
function persist(){try{localStorage.setItem(storageKey(),JSON.stringify({version:1,owner:owner,customer_id:context.customerId,ticket_id:context.ticketId||null,items:queue,updated_at:new Date().toISOString()}));}catch{state.notice='No se pudo guardar la recuperación local. Descarga el manifiesto antes de cerrar.';}}
function restore(){try{var saved=JSON.parse(localStorage.getItem(storageKey())||'null');queue=saved&&saved.owner===owner&&Array.isArray(saved.items)?saved.items:[];queue.forEach(function(i){if(['uploading','hashing','queued','failed'].includes(i.status))i.status='paused';});}catch{queue=[];}}
async function api(action,input,binary){var r=revision;return root.DTGWorkspaceAPI.request(action,input,{binary:binary,actor:owner,signal:controller.signal,isCurrent:function(){return revision===r;}});}
function button(a,label,id){return '<button type="button" class="btn btn-ghost" data-library="'+a+'"'+(id?' data-id="'+esc(id)+'"':'')+(state.busy&&!['pause','close','manifest'].includes(a)?' disabled':'')+'>'+esc(label)+'</button>';}
function fileRow(f){var current=f.current_file_id===f.id,approved=f.usage&&f.usage.production_approved;return '<article class="library-file"><div class="library-preview" data-library-preview="'+esc(f.id)+'">'+esc(labels[f.category]||'Archivo')+'</div><div class="library-file-info"><strong>'+esc(f.filename)+'</strong><small>'+size(f.size_bytes)+' · v'+f.version+' · '+esc(stages[f.stage]||f.stage)+(current?' · Actual':'')+'</small><small>'+esc(f.origin_ticket_id?'Archivo de un trabajo':'Recurso general del cliente')+' · '+esc(f.availability==='available'?'Disponible':'Carga pendiente')+'</small>'+(approved?'<span class="library-approved">Aprobado para este trabajo</span>':'')+'</div><div class="library-file-actions">'+(f.availability==='available'?button('open','Abrir en Drive',f.id)+button('download','Descargar',f.id)+(f.thumbnail_path?button('preview','Vista previa',f.id):button('prepare-preview','Preparar vista previa',f.id))+button('current','Elegir versión',f.id)+(context.ticketId&&state.all?button('reuse','Usar en este trabajo',f.id):'')+(bridge.isAdmin()?button('proof','Marcar prueba',f.id)+button('print-ready','Listo para producción',f.id)+(context.ticketId&&f.usage?button('approve','Aprobar este trabajo',f.id):''):''):'')+'</div></article>';}
function render(){previewObservers.splice(0).forEach(function(o){o.disconnect();});if(!panel)return;if(bridge.actor()!==owner){close();return;}var sc=panel.querySelector('.library-body'),top=sc?sc.scrollTop:0;
 var versions=state.files.filter(function(f,i,a){return f.origin_ticket_id===(context.ticketId||null)&&a.findIndex(function(x){return x.asset_id===f.asset_id;})===i;});
 panel.innerHTML='<section class="library-dialog" role="dialog" aria-modal="true" aria-label="Biblioteca de archivos"><header><div><h2>Archivos · '+esc(context.name||'Cliente')+'</h2><p>'+(context.ticketId?'Trabajo #'+esc(context.seq):'Biblioteca del cliente')+'</p></div>'+button('close','Cerrar')+'</header><div class="library-body">'+(state.error?'<p role="alert" class="library-error">'+esc(state.error)+'</p>':'')+(state.notice?'<p role="status">'+esc(state.notice)+'</p>':'')+
 '<div class="library-toolbar">'+button('refresh','Actualizar')+(context.ticketId?button('scope',state.all?'Ver este trabajo':'Ver archivos del cliente'):'')+(state.status&&!state.status.identity?button('identity','Vincular mi cuenta Workspace'):'')+(bridge.isAdmin()&&state.status&&!state.status.enabled?button('enable','Habilitar biblioteca'):'')+'</div>'+
 (state.oauth?'<p><a href="'+esc(state.oauth)+'" target="_blank" rel="noopener noreferrer">Autorizar mi cuenta Workspace</a>. Al terminar, vuelve y pulsa Actualizar.</p>':'')+
 (state.status&&state.status.identity?'<p class="muted">Cuenta para abrir originales: '+esc(state.status.identity.email)+'</p>':'')+
 '<form data-library-form="filter" class="library-filter"><label>Buscar<input name="search" value="'+esc(state.search)+'" maxlength="150" placeholder="Nombre del archivo"></label><label>Formato<select name="category"><option value="">Todos</option>'+Object.keys(labels).map(function(k){return '<option value="'+k+'"'+(state.category===k?' selected':'')+'>'+labels[k]+'</option>';}).join('')+'</select></label><button class="btn"'+(state.busy?' disabled':'')+'>Buscar</button></form>'+
 '<details class="library-upload"'+(!state.files.length?' open':'')+'><summary>Subir originales o migrar una carpeta</summary><p>Los originales se conservan en Drive. Puedes seleccionar varios archivos o una carpeta. Revisa el cliente antes de iniciar.</p><form data-library-form="add"><label>Archivos<input name="files" type="file" multiple'+(state.busy?' disabled':'')+'></label><label>Carpeta<input name="folder" type="file" webkitdirectory multiple'+(state.busy?' disabled':'')+'></label><label>Categoría<select name="category"><option value="">Detectar por formato</option>'+Object.keys(labels).map(function(k){return '<option value="'+k+'">'+labels[k]+'</option>';}).join('')+'</select></label><label>Versión<select name="asset"><option value="">Nuevos archivos</option>'+versions.map(function(f){return '<option value="'+esc(f.asset_id)+'">Nueva versión de '+esc(f.filename)+'</option>';}).join('')+'</select></label><button class="btn"'+(state.busy?' disabled':'')+'>Agregar a la cola</button></form></details>'+
 (queue.length?'<section class="library-queue"><h3>Carga por lotes · '+queue.filter(function(q){return ['done','skipped'].includes(q.status);}).length+'/'+queue.length+'</h3><div class="library-toolbar">'+button('run','Iniciar o reanudar')+(state.busy?button('pause','Pausar'):'')+button('manifest','Descargar manifiesto')+'</div><p>Para reanudar después de cerrar, vuelve a seleccionar los mismos archivos. Nunca borramos los archivos de tu computadora.</p>'+queue.map(function(q){return '<article><strong>'+esc(q.relative_path||q.name)+'</strong><small>'+size(q.size)+' · '+esc({queued:'En cola',paused:'Pausado',hashing:'Verificando archivo',uploading:'Subiendo',done:'Guardado',skipped:'Omitido por decisión del usuario',duplicate:'Coincidencia encontrada',failed:'Pendiente de reintento'}[q.status]||q.status)+(q.progress!=null?' · '+q.progress+'%':'')+'</small>'+(q.error?'<p>'+esc(q.error)+'</p>':'')+(q.status==='duplicate'?button('skip','Usar el archivo existente',q.key)+button('force','Conservar otra copia',q.key):'')+'</article>';}).join('')+'</section>':'')+
 '<details><summary>Añadir imagen de vista previa a Corel, PDF u otro archivo</summary><form data-library-form="preview"><label>Archivo<select name="file_id">'+state.files.filter(function(f){return f.availability==='available';}).map(function(f){return '<option value="'+esc(f.id)+'">'+esc(f.filename)+'</option>';}).join('')+'</select></label><label>Imagen exportada<input name="image" type="file" accept="image/jpeg,image/png,image/webp" required></label><button class="btn"'+(state.busy?' disabled':'')+'>Guardar vista previa</button></form></details><section class="library-results"><h3>Archivos'+(state.all?' del cliente':'')+'</h3>'+state.files.map(fileRow).join('')+(!state.files.length?'<p>No hay archivos que coincidan.</p>':'')+(state.hasMore?button('more','Cargar más'):'')+'</section></div></section>';
 sc=panel.querySelector('.library-body');sc.scrollTop=top;
 if(!state.busy)previews();
}
async function load(more){var last=more&&state.files[state.files.length-1],r=await api('listLibraryFiles',{customer_id:context.customerId,ticket_id:context.ticketId&&!state.all?context.ticketId:null,search:state.search,category:state.category,before:last?last.uploaded_at:null,before_id:last?last.id:null});state.files=more?state.files.concat(r.files):r.files;state.hasMore=r.has_more;}
function previews(){var nodes=panel.querySelectorAll('[data-library-preview]');nodes.forEach(function(n){var f=state.files.find(function(f){return f.id===n.dataset.libraryPreview;});if(!f||!f.thumbnail_path)return;var observer=new IntersectionObserver(function(entries){if(!entries[0].isIntersecting)return;observer.disconnect();var r=revision;api('getFileAccess',{file_id:f.id,preview:true}).then(function(p){if(r!==revision||!n.isConnected||!p.url)return;var img=document.createElement('img');img.src=p.url;img.alt='Vista previa de '+f.filename;img.loading='lazy';n.replaceChildren(img);}).catch(function(){});},{root:panel.querySelector('.library-body'),rootMargin:'100px'});previewObservers.push(observer);observer.observe(n);});}
async function action(fn){if(state.busy)return;state.error='';state.busy=true;var r=revision;render();try{await fn();}catch(e){if(r===revision)state.error=error(e);}finally{if(r===revision){state.busy=false;render();}}}
async function open(c){if(!c.customerId)return;close();context=c;owner=bridge.actor();if(!owner)return;controller=new AbortController();state={files:[],status:null,search:'',category:'',hasMore:false,busy:false,error:'',notice:'',all:!c.ticketId};restore();panel=document.createElement('div');panel.className='library-overlay';document.body.appendChild(panel);render();await action(async function(){state.status=await api('libraryStatus');await load();});var b=panel&&panel.querySelector('button');if(b)b.focus({preventScroll:true});}
function close(){previewObservers.splice(0).forEach(function(o){o.disconnect();});revision++;if(controller)controller.abort();if(panel){panel.remove();panel=null;}filesByKey.clear();queue=[];context=null;owner=null;}
function add(selected,category,asset){if(!selected.length)throw Error('Selecciona archivos o una carpeta.');if(asset&&selected.length!==1)throw Error('Selecciona un solo archivo para crear una nueva versión.');selected.forEach(function(file){if(state.status&&file.size>Number(state.status.max_file_bytes))throw Error(file.name+' supera el tamaño permitido.');var relative=file.webkitRelativePath||file.name;var existing=queue.find(function(q){return q.relative_path===relative&&q.size===file.size&&!['done','skipped'].includes(q.status);});var q=existing||{key:crypto.randomUUID(),name:file.name,relative_path:relative,size:file.size,mime:file.type||'application/octet-stream',category:category||null,asset_id:asset||null,status:'queued'};if(!existing)queue.push(q);else q.status='queued';filesByKey.set(q.key,file);});persist();}
async function run(){if(!state.status||!state.status.enabled)throw Object.assign(new Error(),{code:'LIBRARY_DISABLED'});
 for(var q of queue){if(['done','skipped','duplicate'].includes(q.status))continue;var file=filesByKey.get(q.key);if(!file){q.status='paused';q.error='Vuelve a seleccionar este archivo para reanudar.';continue;}
  try{q.error='';q.status='hashing';render();var sha=await root.DTGLibraryTransfer.hash(file,controller.signal,function(p){q.progress=Math.floor(p*100);render();});
   if(q.sha256&&q.sha256!==sha)throw Error('El archivo cambió. Selecciona la versión original para reanudar.');q.sha256=sha;persist();
   if(!q.session_id&&!q.duplicate_checked){var duplicate=await api('findLibraryDuplicate',{customer_id:context.customerId,ticket_id:context.ticketId||null,source_sha256:sha});if(duplicate.files.length){q.status='duplicate';q.existing_file_id=duplicate.files[0].id;q.existing_name=duplicate.files[0].filename;persist();continue;}q.duplicate_checked=true;}
   var session=q.session_id?await api('resumeUpload',{session_id:q.session_id}):await api('beginLibraryUpload',{customer_id:context.customerId,ticket_id:context.ticketId||null,idempotency_key:q.key,filename:file.name,mime_type:q.mime,size_bytes:file.size,source_sha256:sha,category:q.category,asset_id:q.asset_id});q.session_id=session.session_id;q.file_id=session.file_id;q.status='uploading';q.progress=0;persist();render();
   await root.DTGLibraryTransfer.upload(file,session,api,controller.signal,function(p){q.progress=Math.floor(p*100);render();});q.status='done';q.progress=100;persist();
   try{var thumb=await createPreview(file);if(thumb)await api('previewUpload',{file_id:q.file_id,mime_type:'image/jpeg'},thumb);}catch{q.preview_pending=true;persist();}
  }catch(e){if(e.name==='AbortError')throw e;q.status='failed';q.error=error(e);persist();}
 }
 await load();state.notice='Lote procesado. Revisa los pendientes y descarga el manifiesto.';
}
async function createPreview(file){if(!/^image\/(jpeg|png|webp)$/.test(file.type)||file.size>26214400)return null;var b=await createImageBitmap(file),scale=Math.min(1,800/Math.max(b.width,b.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(b.width*scale));c.height=Math.max(1,Math.round(b.height*scale));c.getContext('2d').drawImage(b,0,0,c.width,c.height);b.close();return new Promise(function(resolve){c.toBlob(function(blob){resolve(blob&&blob.size<=1048576?blob:null);},'image/jpeg',.7);});}
function manifest(){persist();var blob=new Blob([JSON.stringify({version:1,customer_id:context.customerId,ticket_id:context.ticketId||null,exported_at:new Date().toISOString(),items:queue},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='migracion-'+context.customerId.slice(0,8)+'.json';a.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);}
document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('[data-library]');if(!b||!bridge)return;var a=b.dataset.library,id=b.dataset.id;if(a==='entry'){var c=bridge.customer(b.dataset.customer);open({customerId:b.dataset.customer,ticketId:b.dataset.ticket||null,seq:b.dataset.seq,name:c&&(c.nombre||c.name)});return;}if(!panel)return;if(a==='close'){if(state.busy){controller.abort();queue.forEach(function(q){if(['uploading','hashing'].includes(q.status))q.status='paused';});persist();}close();return;}if(a==='manifest'){manifest();return;}if(a==='pause'){controller.abort();queue.forEach(function(q){if(['uploading','hashing'].includes(q.status))q.status='paused';});persist();controller=new AbortController();state.notice='Carga pausada; puedes reanudar.';return;}
 action(async function(){
  if(a==='refresh'){state.status=await api('libraryStatus');await load();}
  else if(a==='enable'){state.status=await api('configureLibrary',{enabled:true});}
  else if(a==='identity'){var r=await api('beginLibraryIdentity');state.oauth=r.url;}
  else if(a==='scope'){state.all=!state.all;await load();}
  else if(a==='more')await load(true);
  else if(a==='run')await run();
  else if(a==='skip'){var q=queue.find(function(q){return q.key===id;});if(q){q.status='skipped';q.file_id=q.existing_file_id;persist();}}
  else if(a==='force'){var q=queue.find(function(q){return q.key===id;});if(q){q.status='queued';q.duplicate_checked=true;persist();}}
  else if(a==='open'||a==='download'){var tab=window.open('about:blank','_blank');try{var r=await api('directFileAccess',{file_id:id});if(tab){tab.opener=null;tab.location.replace(a==='download'?r.download_url:r.url);}else state.notice='Permite abrir una pestaña para acceder a Drive.';state.notice='Abre Drive con '+r.account_email+'. El acceso temporal dura hasta una hora.';}catch(e){if(tab)tab.close();throw e;}}
  else if(a==='preview'){var tab=window.open('about:blank','_blank');try{var r=await api('getFileAccess',{file_id:id,preview:true});if(tab&&r.url){tab.opener=null;tab.location.replace(r.url);}else if(tab)tab.close();}catch(e){if(tab)tab.close();throw e;}}
  else if(a==='reuse'){await api('reuseFile',{file_id:id,ticket_id:context.ticketId});state.all=false;await load();}
  else if(a==='prepare-preview'){await api('requestLibraryPreview',{file_id:id});state.notice='Vista previa solicitada. Si Drive no la genera, puedes añadir una imagen exportada.';}
  else if(a==='current'){await api('setCurrentVersion',{file_id:id});await load();}
  else if(a==='proof'||a==='print-ready'){await api('setFileStage',{file_id:id,stage:a==='proof'?'Proof':'Print Ready'});await load();}
  else if(a==='approve'){await api('approveForProduction',{file_id:id,ticket_id:context.ticketId});await load();}
 });
});
document.addEventListener('submit',function(e){var form=e.target;if(!form.dataset||!form.dataset.libraryForm||!panel)return;e.preventDefault();if(state.busy)return;var data=new FormData(form);if(form.dataset.libraryForm==='filter'){action(async function(){state.search=String(data.get('search')||'');state.category=String(data.get('category')||'');await load();});}else if(form.dataset.libraryForm==='preview'){action(async function(){var thumb=await createPreview(form.elements.image.files[0]);if(!thumb)throw Error('Selecciona una imagen JPG, PNG o WebP de menos de 25 MB.');await api('previewUpload',{file_id:String(data.get('file_id')),mime_type:'image/jpeg'},thumb);await load();});}else if(form.dataset.libraryForm==='add'){try{var selected=Array.from(form.elements.files.files).concat(Array.from(form.elements.folder.files));add(selected,String(data.get('category')||''),String(data.get('asset')||''));state.error='';render();}catch(e){state.error=error(e);render();}}});
window.addEventListener('beforeunload',function(e){if(state&&state.busy&&queue.some(function(q){return ['uploading','hashing'].includes(q.status);})){e.preventDefault();e.returnValue='';}});
document.addEventListener('keydown',function(e){if(!panel)return;if(e.key==='Escape'&&!state.busy){close();return;}if(e.key==='Tab'){var fields=Array.from(panel.querySelectorAll('button:not(:disabled),input,select,a[href]')).filter(function(x){return x.getClientRects().length;});var first=fields[0],last=fields[fields.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
root.DTGClientLibrary={mount:function(b){bridge=b;},open:open,reset:close};
})(window);
