const fs=require('fs'),assert=require('assert'),{chromium}=require('playwright');
const waFile=fs.existsSync(__dirname+'/wa-inbox-qa.cjs')?'wa-inbox-qa.cjs':'CHAT-INBOX-QA.cjs';
let fixture=fs.readFileSync(__dirname+'/'+waFile,'utf8').match(/const fixture=`([\s\S]*?)`;/)[1];
fixture=fixture.slice(0,fixture.lastIndexOf('render();'))+`
STATE.clientes=[{id:'client',nombre:'Impresiones y diseños Matamoros',empresa:'Cliente con nombre largo',telefono:'8681234567',email:'qa@example.invalid',createdAt:'2026-09-01T12:00:00Z'},...Array.from({length:30},(_,i)=>({id:'client'+i,nombre:'Cliente de prueba '+i,createdAt:'2026-09-01T12:00:00Z'}))];
STATE.tickets=Array.from({length:18},(_,i)=>({id:'t'+i,seq:100+i,clienteId:'client',cliente:STATE.clientes[0].nombre,responsable:'Jonathan',estado:i===17?'entregado':'abierto',entregadoAt:i===17?'2026-09-01T12:00:00Z':null,createdAt:'2026-09-01T12:00:00Z',lastActivityAt:'2026-10-01T12:00:00Z',fechaAtencion:'2026-10-01',fechaCompromiso:'2026-10-02',queSigue:'Preparar archivos y confirmar medidas con cliente',visibility:'public',productos:[{id:'prod'+i,desc:'Lona con impresión de alta resolución',cantidad:2,precio:100}],pagos:[],documentos:[],thread:[],markers:[],workOrders:[],accessProfileIds:[],tareas:[{id:'task'+i,desc:'Comprar vinil negro para el pedido',tipo:'produccion',area:'planeacion',tipoOperacion:'Compra',estado:'pendiente',progreso:0,responsable:'Jonathan',fechaAtencion:'2026-10-01'}]}));
Object.assign(qa,{openOpsEditor,openCierreModalForTicket,openDocumentForm,resetDisclosure:()=>MOBILE_DISCLOSURE=Object.create(null),view:v=>{UI.selectedTicketId=null;UI.selectedClienteId=null;UI.operaciones.editor=null;UI.mainView=v;render();},ticket:()=>{UI.mainView='tickets';UI.selectedTicketId='t0';render();},client:()=>{UI.selectedTicketId=null;UI.mainView='clientes';UI.selectedClienteId='client';render();}});render();
`;
fixture+=`
window.libraryWrites=[];var libraryFrom=sb.from;sb.from=function(table){if(table==='feed_reactions')return {upsert:async row=>{libraryWrites.push(row);return {error:null};},delete:()=>({eq:()=>({eq:()=>({eq:async()=>({error:null})})})})};return libraryFrom(table);};refreshFromServer=async()=>{};
STATE.tickets[0].thread=[{id:'file1',type:'archivo',storage_path:'photo/one.jpg',filename:'one.jpg',caption:'Diseño del cliente',autor:'Martin',ts:new Date().toISOString()}];STATE.teamPosts.push({id:'library-pending',authorUserId:'martin',autor:'Martin',createdAt:new Date().toISOString(),text:'Foto sin ticket',imageStoragePath:'photo/pending.jpg',pinLevel:'none',mentions:[]});qa.view('biblioteca');
`;
fixture+='Object.assign(qa,{bibliotecaAllPhotos,libraryPendingPhotos});';
let html=fs.readFileSync(__dirname+'/index.html','utf8').replace(/<script[^>]*src=[^>]*><\/script>/g,'').replace(/\bboot\(\);(?=\s*\n\}\)\(\);)/,fixture);
html=html.replace('<script>','<script>'+fs.readFileSync(__dirname+'/ops-menu.js','utf8')+'</script><script>');

(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_BIN||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.abort());await page.setContent(html);
assert.equal(await page.locator('#biblioteca-scroll .feed-item-post').count(),0);assert.equal(await page.locator('.library-module').count(),2);assert.equal(await page.locator('[data-library-post="library-pending"]').count(),1);
await page.locator('.library-tools summary').click();assert.equal(await page.locator('.library-tools .pirate-cat').count(),7);assert.equal(await page.locator('.library-tools .wa-emoji').count(),0);await page.locator('.library-tools [data-reaction="love"]').click();await page.waitForFunction(()=>libraryWrites.length===1);assert.equal(await page.evaluate(()=>libraryWrites[0].reaction_type),'love');assert.equal(await page.evaluate(()=>libraryWrites[0].target_id),'library-pending');
await page.locator('[data-library="preview"]').click();assert(await page.locator('.biblioteca-viewer-media').isVisible());await page.locator('[data-action="biblioteca-viewer-close"]').click();await page.locator('[data-action="biblioteca-open-photo"]').click();assert(await page.locator('.biblioteca-viewer-media').isVisible());await page.locator('[data-action="biblioteca-viewer-close"]').click();
if(!(await page.locator('.library-tools').evaluate(n=>n.open)))await page.locator('.library-tools summary').click();await page.locator('[data-action="feed-photo-relacionar-open"]').click();assert(await page.locator('#feed-relacionar-input').isVisible());await page.locator('[data-action="feed-relacionar-cancel"]').click();await page.locator('#biblioteca-search').fill('sin ticket');assert.equal(await page.locator('.library-module').count(),1);await page.locator('#biblioteca-search').fill('');
await page.waitForFunction(()=>qa.UI.biblioteca.search==='');await page.evaluate(()=>{qa.UI.sidebarOpen=false;qa.render();});await page.waitForFunction(()=>document.querySelectorAll('.library-module').length===2);for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const dims=await page.locator('.library-pending-media,.library-module .biblioteca-tile').evaluateAll(ns=>ns.map(n=>{var r=n.getBoundingClientRect();return Math.abs(r.width-r.height);}));assert(dims.every(d=>d<2));if(width===390)await page.screenshot({path:__dirname+'/library-mobile.png'});}
await page.evaluate(()=>{var now=new Date().toISOString();qa.STATE.conversations.push({id:'new-ticket-chat',kind:'ticket',ticket_id:'t0'},{id:'unrelated-dm',kind:'direct',member_a:'alexia',member_b:'ceci'});qa.STATE.teamPosts.push({id:'new-ticket-photo',conversationId:'new-ticket-chat',authorUserId:'martin',autor:'Martin',createdAt:now,text:'Nueva foto del ticket',imageStoragePath:'new-ticket-chat/new.jpg',pinLevel:'none'},{id:'no-ticket-photo',noTicketRequired:true,authorUserId:'martin',autor:'Martin',createdAt:now,text:'Imagen sin ticket necesario',imageStoragePath:'public/complete.jpg',pinLevel:'none'},{id:'foreign-photo',conversationId:'unrelated-dm',authorUserId:'alexia',createdAt:now,imageStoragePath:'private/other.jpg'},{id:'deleted-photo',conversationId:'new-ticket-chat',deletedAt:now,createdAt:now,imageStoragePath:'private/deleted.jpg'});qa.view('biblioteca');});
const photos=await page.evaluate(()=>qa.bibliotecaAllPhotos());assert(photos.some(p=>p.id==='new-ticket-photo'&&p.bucket==='chat-private'));assert(photos.some(p=>p.id==='no-ticket-photo'));assert(!photos.some(p=>p.id==='foreign-photo'||p.id==='deleted-photo'));await page.locator('[data-library-post-id="new-ticket-photo"]').click();assert.equal(await page.locator('.biblioteca-viewer-media img').getAttribute('data-storage-bucket'),'chat-private');assert.equal(await page.locator('[data-action="delete-photo-open"]').count(),0);await page.locator('[data-action="biblioteca-viewer-close"]').click();
const compact=await page.locator('.library-module:not([data-library-post]) .library-module-info').first().boundingBox();assert(compact.height<120,'Compact info strip');
assert.deepEqual(errors,[]);console.log('PASS library: square modular cards, linked/unlinked photo preview, seven custom winking reactions and persisted stable IDs, linking picker, search and 320–1280px.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
