(function(root){
 'use strict';
 var bridge,host=null,actor=null,revision=0,controller=null,poll=null;
 function initial(){return {status:null,switcher:false,collapsed:{},inbox:'',folder:'inbox',messages:[],selected:null,thread:[],search:'',busy:false,error:'',notice:'',settings:false,compose:false,draft:{to:'',cc:'',bcc:'',subject:'',body:'',inbox_id:'',ticket_id:'',reply_message_id:''},draftId:null,drafts:[],command:null,operations:[],oauthUrl:'',more:false};}
 var state=initial();
 function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
 function btn(action,label,extra,disabled){return '<button type="button" class="btn btn-ghost" data-mail="'+action+'" '+(extra||'')+(disabled?' disabled':'')+'>'+esc(label)+'</button>';}
 function box(){return ((state.status&&state.status.inboxes)||[]).find(function(b){return b.id===state.inbox;});}
 function groupKey(b){return b.logical_inbox||b.id;}
 function preference(){try{return JSON.parse(localStorage.getItem('dtg-mail-order:'+actor)||'[]');}catch(e){return [];}}
 function personalAlias(){var n=String(bridge.actorName?bridge.actorName():'').toLowerCase();return {jonathan:'jona',martin:'martin',ceci:'ceci',tania:'tania',israel:'israel','alex dh':'alex',alexia:'alexia'}[n]||'';}
 function defaultInbox(){var boxes=(state.status&&state.status.inboxes)||[],name=String(bridge.actorName?bridge.actorName():'').toLowerCase(),alias=name==='martin'?'hello':personalAlias();return (boxes.find(function(b){return b.email_alias===alias+'@956print.com';})||boxes.find(function(b){return b.logical_inbox==='commercial';})||boxes[0]||{}).id||'';}
 function unread(group){if(!state.status||!state.status.unread_snapshot)return '—';var ids=group.map(function(b){return b.id;}),seen={};state.status.unread_snapshot.forEach(function(m){if(ids.includes(m.inbox_id))seen[m.id]=true;});return String(Object.keys(seen).length)+(state.status.unread_capped?'+':'');}
 function groupedBoxes(){var groups={};((state.status&&state.status.inboxes)||[]).forEach(function(b){var k=groupKey(b);if(!groups[k])groups[k]=[];groups[k].push(b);});var order=preference(),own=personalAlias()+'@956print.com';return Object.values(groups).sort(function(a,b){function rank(g){var k=groupKey(g[0]),i=order.indexOf(k);if(i>=0)return i;return order.length+(g.some(function(v){return v.email_alias===own;})?0:k==='commercial'?1:2);}return rank(a)-rank(b);});}
 function currentBoxes(){var b=box();return b?((state.status&&state.status.inboxes)||[]).filter(function(x){return groupKey(x)===groupKey(b);}):[];}
 function readInbox(){return state.selected&&state.selected._inbox_id||state.inbox;}
 function senders(){return ((state.status&&state.status.inboxes)||[]).filter(function(b){return b.can_send&&b.connected&&b.active&&b.verification_status==='accepted';});}
 function senderOptions(value){return '<option value="">'+(senders().length?'Elegir remitente':'Sin remitentes verificados')+'</option>'+((state.status&&state.status.inboxes)||[]).filter(function(b){return b.can_send&&b.active;}).map(function(b){var ready=b.connected&&b.verification_status==='accepted';return '<option value="'+esc(b.id)+'"'+(value===b.id?' selected':'')+(ready?'':' disabled')+'>'+esc(b.email_alias)+(ready?'':' · pendiente en Gmail')+'</option>';}).join('');}
 function opts(rows,key,label,value,empty){return (empty?'<option value="">'+esc(empty)+'</option>':'')+rows.map(function(r){return '<option value="'+esc(r[key])+'"'+(r[key]===value?' selected':'')+'>'+esc(r[label])+'</option>';}).join('');}
 function labels(m){return m.label_ids||[];}
 function visible(m){var ls=labels(m),q=state.search.toLowerCase();if(q&&[m.subject,m.from_address,m.snippet,(m.to_addresses||[]).join(' ')].join(' ').toLowerCase().indexOf(q)<0)return false;if(state.folder==='sent')return m.direction==='outbound';if(state.folder==='starred')return ls.includes('STARRED');if(state.folder==='archive')return m.direction==='inbound'&&!ls.includes('INBOX');return m.direction==='inbound'&&ls.includes('INBOX');}
 function threads(){var grouped={};state.messages.filter(visible).forEach(function(m){var k=m.connection_id+':'+m.thread_id;if(!grouped[k])grouped[k]={last:m,count:0,unread:false};grouped[k].count++;grouped[k].unread=grouped[k].unread||labels(m).includes('UNREAD');});return Object.values(grouped);}
 function plain(p){if(p&&p.mimeType==='text/plain'&&p.body&&p.body.data){try{return new TextDecoder().decode(Uint8Array.from(atob(p.body.data.replace(/-/g,'+').replace(/_/g,'/')),function(c){return c.charCodeAt(0);}));}catch(e){return '';}}return (p&&p.parts||[]).map(plain).filter(Boolean).join('\n');}
 function header(m,name){return (m.payload&&m.payload.headers||[]).filter(function(h){return h.name.toLowerCase()===name;}).map(function(h){return h.value;}).join(', ');}
 function attachments(p,result){result=result||[];if(p&&p.filename)result.push(p.filename);(p&&p.parts||[]).forEach(function(x){attachments(x,result);});return result;}
 function gmailLink(m){var b=box();return 'https://mail.google.com/mail/?authuser='+encodeURIComponent(b&&b.account_email||'')+'#all/'+encodeURIComponent(m.id);}
 function resultLabel(op){return {queued:'En cola',running:'Procesando',retry:'Pendiente de reintento',done:'Aceptado por Gmail',failed:'No enviado',unknown:'Resultado incierto'}[op.state]||'Pendiente';}
 function paint(){
  if(!host||!host.isConnected)return;
  var cfg=state.status,b=box(),admin=bridge.isAdmin(),rows=threads(),enabled=cfg&&cfg.enabled;
  var nav=groupedBoxes().map(function(group){var x=group[0],key=groupKey(x),chosen=group.some(function(v){return v.id===state.inbox;}),name=group.length>1?({commercial:'Ventas',quotes_invoices:'Cotizaciones y facturas',support:'Soporte',artwork:'Arte'}[key]||x.display_name):x.email_alias;return '<div class="mail-account-group" draggable="true" data-group="'+esc(key)+'"><div class="mail-group-line"><button class="mail-account '+(chosen?'selected':'')+'" data-mail="inbox" data-id="'+esc(x.id)+'"><strong>'+esc(name)+'</strong><small>'+esc(group.map(function(v){return v.email_alias;}).join(' / '))+'</small><span class="mail-unread" title="Sin leer sincronizados">'+esc(unread(group))+'</span></button><button class="btn btn-ghost" data-mail="collapse" data-id="'+esc(key)+'" aria-label="Colapsar o expandir '+esc(name)+'" aria-expanded="'+!state.collapsed[key]+'">'+(state.collapsed[key]?'▸':'▾')+'</button><button class="btn btn-ghost" data-mail="move-up" data-id="'+esc(key)+'" aria-label="Subir '+esc(name)+'">↑</button></div>'+(!state.collapsed[key]?'<div class="mail-group-aliases">'+group.map(function(v){return btn('inbox',v.email_alias,'data-id="'+esc(v.id)+'"');}).join('')+'</div>':'')+'</div>';}).join('')||'<p>No tienes bandejas autorizadas.</p>';
  nav='<button class="mail-switch-toggle" data-mail="switcher" aria-expanded="'+state.switcher+'"><strong>'+esc(b?b.email_alias:'Elegir bandeja')+'</strong><span>▾</span><small>Sin leer: '+esc(b?unread(currentBoxes()):'—')+'</small></button><div class="mail-switch-list"'+(state.switcher?'':' hidden')+'>'+nav+'<p class="mail-hint">Arrastra para ordenar; ↑ también funciona con teclado. Avisos de correos sincronizados, hasta 1000 coincidencias.</p></div>';
  var folderNames=[['inbox','Recibidos'],['sent','Enviados'],['starred','Destacados'],['archive','Archivados'],['drafts','Borradores']];
  var folders=folderNames.map(function(f){return '<button data-mail="folder" data-id="'+f[0]+'" class="mail-folder '+(state.folder===f[0]?'selected':'')+'">'+f[1]+'</button>';}).join('');
  var list=state.folder==='drafts'?state.drafts.map(function(d){return '<button class="mail-row" data-mail="draft" data-id="'+esc(d.id)+'"><strong>'+esc(d.subject||'(Sin asunto)')+'</strong><small>Borrador guardado · '+esc(new Date(d.updated_at).toLocaleString())+'</small></button>';}).join(''):rows.map(function(r){var m=r.last;return '<button data-mail="read" data-id="'+esc(m.id)+'" class="mail-row '+(state.selected&&state.selected.id===m.id?'selected ':'')+(r.unread?'unread':'')+'"><span><strong>'+esc(m.from_address)+'</strong><time>'+esc(new Date(m.occurred_at||m.sent_at||m.received_at).toLocaleDateString())+'</time></span><b>'+esc(m.subject||'(Sin asunto)')+(r.count>1?' · '+r.count:'')+'</b><p>'+esc(m.snippet||'')+'</p></button>';}).join('');
  var reading=state.selected?'<header class="mail-reading-head"><h2>'+esc(state.selected.subject||'(Sin asunto)')+'</h2>'+btn('reply','Responder','',!senders().length)+btn('state',labels(state.selected).includes('UNREAD')?'Marcar leído':'Marcar no leído','data-state="'+(labels(state.selected).includes('UNREAD')?'read':'unread')+'"',state.busy||!b||!b.can_send)+btn('state',labels(state.selected).includes('STARRED')?'Quitar destacado':'Destacar','data-state="'+(labels(state.selected).includes('STARRED')?'unstar':'star')+'"',state.busy||!b||!b.can_send)+btn('state','Archivar','data-state="archive"',state.busy||!b||!b.can_send)+'</header>'+state.thread.map(function(m){var files=attachments(m.payload);return '<article class="mail-message"><header><strong>'+esc(header(m,'from'))+'</strong><small>Para: '+esc(header(m,'to'))+' · '+esc(new Date(Number(m.internalDate)).toLocaleString())+'</small></header><pre>'+esc(plain(m.payload)||'Este mensaje solo tiene contenido HTML. Ábrelo en Gmail para verlo.')+'</pre>'+(files.length?'<p>Adjuntos: '+files.map(esc).join(', ')+'</p>':'')+'<a href="'+esc(gmailLink(m))+'" target="_blank" rel="noopener noreferrer">Abrir en Gmail'+(files.length?' / descargar adjuntos':'')+'</a></article>';}).join('')+'<form id="mail-link"><label>Vincular a ticket<select name="ticket_id" required>'+opts(bridge.tickets(),'id','label','','Seleccionar ticket')+'</select></label><button class="btn"'+(state.busy?' disabled':'')+'>Vincular correo</button></form>':'<div class="mail-empty"><h2>Tu correo, junto a tus tickets</h2><p>Elige una bandeja y una conversación, o redacta un correo nuevo.</p></div>';
  var draft=state.draft;
  var composer=state.compose?'<section class="mail-compose"><header><h2>'+(draft.reply_message_id?'Responder':'Nuevo correo')+'</h2>'+btn('close-compose','Cerrar borrador')+'</header><form id="mail-compose-form"><label>Desde<select name="inbox_id" required aria-describedby="mail-from-help"'+(!senders().length?' disabled':'')+'>'+senderOptions(draft.inbox_id)+'</select></label><p id="mail-from-help" class="mail-hint">'+(senders().length?'Elige la dirección que verá el cliente.':'Gmail todavía no confirmó los remitentes. Puedes guardar el borrador mientras se completa la configuración.')+'</p><label>Para<input name="to" value="'+esc(draft.to)+'" placeholder="cliente@ejemplo.com" required maxlength="3000"></label><div class="mail-cc"><label>CC<input name="cc" maxlength="3000" value="'+esc(draft.cc)+'"></label><label>CCO<input name="bcc" maxlength="3000" value="'+esc(draft.bcc)+'"></label></div><label>Asunto<input name="subject" maxlength="300" value="'+esc(draft.subject)+'" required'+(draft.reply_message_id?' readonly':'')+'></label><label>Mensaje<textarea name="body" rows="10" maxlength="100000" required>'+esc(draft.body)+'</textarea></label><label>Ticket relacionado<select name="ticket_id">'+opts(bridge.tickets(),'id','label',draft.ticket_id,'Sin ticket')+'</select></label><p class="mail-hint">Varios destinatarios: sepáralos con comas. La firma del remitente se añade al enviar.</p><footer><button class="btn btn-primary"'+(!enabled||!senders().length||state.busy?' disabled':'')+'>Enviar correo</button>'+btn('save-draft','Guardar borrador','',state.busy)+btn('discard','Descartar borrador','',state.busy)+'</footer></form></section>':'';
  var settings='';
  if(admin&&state.settings){var setup=cfg&&cfg.setup;settings='<section class="mail-settings"><h2>Conectar cuentas y aliases</h2><p>Cada cuenta de Google se autoriza una vez. Sus aliases se detectan y se usan como remitentes; no se crean desde el CRM.</p><ol><li>En Google Admin abre el usuario → Add alternate emails; agrega hello, sales y los aliases que le pertenezcan.</li><li>En Google Cloud habilita Gmail y Drive API y crea un cliente OAuth web.</li><li>Redirección autorizada: <code>'+esc(bridge.url()+'/functions/v1/google-oauth-callback')+'</code></li></ol><p><a href="https://console.cloud.google.com/auth/clients" target="_blank" rel="noopener noreferrer">Crear cliente OAuth en Google</a> · <a href="https://admin.google.com/ac/users" target="_blank" rel="noopener noreferrer">Administrar usuarios y aliases</a></p>'+(setup&&!setup.configured?'<form id="mail-oauth-config"><label>Client ID<input name="client_id" required autocomplete="off"></label><label>Client secret<input type="password" name="client_secret" required autocomplete="new-password"></label><button class="btn"'+(state.busy?' disabled':'')+'>Guardar credenciales de Google</button><p>Solo se guardan en el servidor. Las claves internas se generan automáticamente.</p></form>':'<p>Configuración del backend lista.</p>')+'<form id="mail-connect"><label>Cuenta real de Workspace<input type="email" name="account_email" placeholder="martin@956print.com" required></label><button class="btn"'+(state.busy||!setup||!setup.configured?' disabled':'')+'>Conectar cuenta</button></form>'+(state.oauthUrl?'<a class="btn btn-primary" href="'+esc(state.oauthUrl)+'" target="_blank" rel="noopener noreferrer">Autorizar en Google</a>':'')+'<div>'+(cfg&&cfg.connections||[]).map(function(c){return '<p><strong>'+esc(c.account_email)+'</strong> · '+esc(c.state)+' '+btn('disconnect','Desconectar','data-id="'+esc(c.id)+'"',state.busy)+'</p>';}).join('')+'</div>'+btn('validate','Detectar y validar aliases','',state.busy)+btn('enable',enabled?'Pausar correo':'Activar correo','',state.busy||(!enabled&&(!setup||!setup.configured||!setup.connected)))+'<h3>Permisos por bandeja</h3><form id="mail-permission"><label>Miembro<select name="user_id" required>'+opts(bridge.members(),'id','displayName','','Elegir miembro')+'</select></label><label>Bandeja<select name="inbox_id" required>'+opts(cfg&&cfg.inboxes||[],'id','email_alias','','Elegir bandeja')+'</select></label><label><input name="can_read" type="checkbox" checked> Puede leer</label><label><input name="can_send" type="checkbox"> Puede enviar y administrar mensajes</label><button class="btn"'+(state.busy?' disabled':'')+'>Guardar permisos</button></form></section>';}
  if(admin&&state.settings&&b)settings+='<section class="mail-settings"><h2>Firma · '+esc(b.email_alias)+'</h2><form id="mail-signature"><label>Nombre del remitente<input name="from_name" maxlength="120" value="'+esc(b.default_from_name||'956 Print')+'" required></label><label>Firma<textarea name="signature" maxlength="5000" rows="3">'+esc(b.default_signature||'')+'</textarea></label><button class="btn"'+(state.busy?' disabled':'')+'>Guardar firma de esta bandeja</button></form></section>';
  host.innerHTML='<section class="mail-workspace" aria-label="Correos"><header class="mail-top"><h1>Correos</h1><div>'+btn('new','Redactar')+btn('refresh','Actualizar','',state.busy)+btn('sync','Sincronizar','',state.busy||!enabled||!b||!b.connected||!admin)+(admin?'<button type="button" class="btn btn-ghost'+(state.settings?' selected':'')+'" data-mail="settings">Conexiones y permisos</button>':'')+'</div></header>'+(state.error?'<p role="alert" class="mail-error">'+esc(state.error)+'</p>':'')+(state.notice?'<p role="status" class="mail-notice">'+esc(state.notice)+'</p>':'')+(!enabled?'<p class="mail-notice">El correo está pendiente de activación. Puedes preparar borradores; tus tickets siguen disponibles.</p>':''+'<div class="mail-layout"><aside class="mail-banks"><h2>Bandejas</h2>'+nav+'<nav aria-label="Carpetas de correo">'+folders+'</nav></aside><section class="mail-list"><form id="mail-search"><label>Buscar en correos cargados<input type="search" name="query" value="'+esc(state.search)+'" placeholder="Remitente o asunto"></label><button class="btn">Buscar</button></form><p class="mail-hint">'+(state.busy?'Actualizando…':rows.length+' conversaciones en esta página')+'</p>'+list+(!list?'<p class="mail-empty">'+(state.folder==='drafts'?'No hay borradores guardados.':'No hay correos en esta vista. Sincroniza la bandeja si esperas mensajes nuevos.')+'</p>':'')+(state.more&&state.folder!=='drafts'?btn('more','Cargar anteriores','',state.busy):'')+'</section><section class="mail-reading">'+(state.settings?settings:reading)+'</section></div>'+composer+'<section class="mail-operations" aria-label="Resultados de envío"><h2>Operaciones recientes</h2>'+state.operations.map(function(o){return '<p>'+esc(resultLabel(o))+' '+(o.last_error?esc(root.DTGWorkspaceAPI.message({code:o.last_error})): '')+' '+btn('operation','Consultar resultado','data-id="'+esc(o.operation_id)+'"',state.busy)+(o.state==='queued'?btn('process','Procesar ahora','data-id="'+esc(o.operation_id)+'"',state.busy):'')+'</p>';}).join('')+'</section>')+'</section>';
 }
 async function api(action,input){var rev=revision;return root.DTGWorkspaceAPI.request(action,input,{signal:controller.signal,actor:actor,isCurrent:function(){return rev===revision;}});}
 async function run(fn){if(state.busy)return;var rev=revision;state.busy=true;state.error='';paint();try{await fn();}catch(e){if(rev===revision&&e.name!=='AbortError')state.error=root.DTGWorkspaceAPI.message(e);}finally{if(rev===revision){state.busy=false;paint();}}}
 async function load(more){state.status=await api('status');if(!state.inbox||!state.status.inboxes.some(function(b){return b.id===state.inbox;}))state.inbox=defaultInbox();if(state.folder==='drafts'){state.drafts=await api('listMailDrafts');return;}if(!state.inbox){state.messages=[];return;}var input={inbox_id:state.inbox};if(more&&state.messages.length)input.before=state.messages[state.messages.length-1].occurred_at;var batches=await Promise.all(currentBoxes().map(async function(b){var rows=await api('listEmails',Object.assign({},input,{inbox_id:b.id}));return rows.map(function(m){return Object.assign({},m,{_inbox_id:b.id});});}));var seen={},rows=batches.flat().sort(function(a,b){return String(b.occurred_at).localeCompare(String(a.occurred_at));}).filter(function(m){if(seen[m.id])return false;seen[m.id]=true;return true;}).slice(0,50);state.messages=more?state.messages.concat(rows):rows;state.more=rows.length===50;}
 function remember(op){state.operations=state.operations.filter(function(o){return o.operation_id!==op.operation_id;});state.operations.unshift(op);}
 async function process(id){remember(await api('processMailOperation',{operation_id:id}));state.notice='Consulta el resultado de envío en Operaciones recientes.';}
 function fresh(){state.compose=true;state.draftId=null;state.command=null;state.draft={to:'',cc:'',bcc:'',subject:'',body:'',inbox_id:(senders().find(function(x){return x.id===state.inbox;})||senders()[0]||{}).id||'',ticket_id:'',reply_message_id:''};}
 function addresses(s){return String(s||'').split(/[,;\n]/).map(function(x){return x.trim();}).filter(Boolean);}
 async function send(){var d=state.draft,command=state.command||(state.command=crypto.randomUUID());var op=await api('sendEmail',{inbox_id:d.inbox_id,to:addresses(d.to),cc:addresses(d.cc),bcc:addresses(d.bcc),subject:d.subject,body:d.body,ticket_id:d.ticket_id||null,reply_message_id:d.reply_message_id||null,idempotency_key:command});remember(op);state.notice='Correo registrado. Comprobando si Gmail lo acepta…';if(state.draftId){try{await api('deleteMailDraft',{draft_id:state.draftId});}catch(e){/* Accepted outbox remains authoritative even if draft cleanup fails. */}}state.draft={to:'',cc:'',bcc:'',subject:'',body:'',inbox_id:'',ticket_id:'',reply_message_id:''};state.compose=false;state.command=null;state.draftId=null;await process(op.operation_id);}
 document.addEventListener('input',function(e){if(!host||!host.contains(e.target))return;var f=e.target.closest('#mail-compose-form');if(f&&e.target.name){state.draft[e.target.name]=e.target.value;}});
 document.addEventListener('change',function(e){if(!host||!host.contains(e.target))return;if(e.target.closest('#mail-compose-form')&&e.target.name==='inbox_id'){state.draft.inbox_id=e.target.value;if(!state.draft.reply_message_id)return;var sender=senders().find(function(x){return x.id===e.target.value;});if(sender&&state.selected&&sender.connection_id!==state.selected.connection_id){state.draft.reply_message_id='';state.notice='Ese remitente usa otra cuenta: el correo se enviará como una conversación nueva.';paint();}}});
 document.addEventListener('submit',function(e){if(!host||!host.contains(e.target))return;var f=e.target;if(!/^mail-/.test(f.id))return;e.preventDefault();var data=Object.fromEntries(new FormData(f));if(f.id==='mail-search'){state.search=data.query;paint();return;}if(f.id==='mail-oauth-config'){var secret=data.client_secret;f.reset();run(async function(){state.status=await api('configureMail',{client_id:data.client_id,client_secret:secret});state.notice='Credenciales guardadas. Ahora conecta cada cuenta real.';secret='';});return;}run(async function(){if(f.id==='mail-compose-form')await send();else if(f.id==='mail-connect'){var result=await api('beginOAuth',data);if(!result.url.startsWith('https://accounts.google.com/'))throw Error();state.oauthUrl=result.url;state.notice='Abre Autorizar en Google. Después vuelve aquí y pulsa Actualizar.';}else if(f.id==='mail-permission'){await api('setInboxAccess',{user_id:data.user_id,inbox_id:data.inbox_id,can_read:!!data.can_read,can_send:!!data.can_send});state.notice='Permisos de la bandeja guardados.';}else if(f.id==='mail-signature'){await api('saveMailSignature',{inbox_id:state.inbox,from_name:data.from_name,signature:data.signature});await load();state.notice='Firma guardada para esta dirección.';}else if(f.id==='mail-link'){await api('attachEmailToTicket',{message_id:state.selected.id,ticket_id:data.ticket_id});state.notice='Correo vinculado al ticket seleccionado.';}});});
 document.addEventListener('click',function(e){var el=e.target.closest('[data-mail]');if(!el||!host||!host.contains(el))return;var a=el.dataset.mail,id=el.dataset.id;if(a==='switcher'){state.switcher=!state.switcher;paint();return;}if(a==='collapse'){state.collapsed[id]=!state.collapsed[id];paint();return;}if(a==='move-up'){var order=groupedBoxes().map(function(g){return groupKey(g[0]);}),i=order.indexOf(id);if(i>0){order.splice(i,1);order.splice(i-1,0,id);try{localStorage.setItem('dtg-mail-order:'+actor,JSON.stringify(order));}catch(e){}paint();}return;}
  if(a==='settings'){state.settings=!state.settings;paint();return;}if(a==='new'){if(state.draft.body||state.draft.subject){state.compose=true;state.notice='Retomaste tu borrador. Guárdalo o descártalo antes de empezar otro.';paint();return;}fresh();paint();return;}if(a==='close-compose'){state.compose=false;state.notice='Borrador conservado en esta sesión. Guárdalo para recuperarlo tras recargar.';paint();return;}
  run(async function(){if(a==='refresh')await load();else if(a==='inbox'){state.settings=false;state.inbox=id;state.switcher=false;state.selected=null;state.thread=[];await load();}else if(a==='folder'){state.settings=false;state.folder=id;state.selected=null;await load();}else if(a==='more')await load(true);else if(a==='read'){state.settings=false;var mail=await api('getEmail',{message_id:id});state.selected=Object.assign({},mail.metadata,{_inbox_id:(state.messages.find(function(m){return m.id===id;})||{})._inbox_id||state.inbox});var thread=await api('getThread',{message_id:id});state.thread=thread.messages||[mail.message];}else if(a==='reply'){if(!state.selected)return;if(state.compose&&state.draft.body){state.notice='Guarda o descarta tu borrador antes de responder a otro hilo.';return;}var m=state.selected;fresh();var match=String(m.from_address).match(/[^<>\s,]+@[^<>\s,]+/);state.draft.to=m.direction==='outbound'?(m.to_addresses||[]).join(', '):(match?match[0]:'');state.draft.subject=m.subject||'(Sin asunto)';state.draft.reply_message_id=m.rfc_message_id?m.id:'';state.draft.inbox_id=(senders().find(function(x){return x.id===readInbox();})||senders().find(function(x){return x.connection_id===m.connection_id;})||{}).id||'';}else if(a==='state'){var changed=await api('setEmailState',{message_id:state.selected.id,inbox_id:readInbox(),state:el.dataset.state});state.selected.label_ids=changed.label_ids;await load();}else if(a==='validate'){await api('validateAliases');await load();state.notice='Aliases reales detectados y verificados con Gmail.';}else if(a==='enable'){await api('configure',{enabled:!state.status.enabled});await load();}else if(a==='disconnect'){await api('disconnect',{connection_id:id});await load();}else if(a==='sync'){var op=await api('syncEmails',{connection_id:box().connection_id,idempotency_key:crypto.randomUUID()});remember(op);await process(op.operation_id);await load();}else if(a==='operation'){remember(await api('operationStatus',{operation_id:id}));}else if(a==='process')await process(id);else if(a==='save-draft'){var d=await api('saveMailDraft',{draft_id:state.draftId,draft:state.draft});state.draftId=d.id;state.notice='Borrador guardado en tu cuenta del CRM.';}else if(a==='draft'){var d=await api('getMailDraft',{draft_id:id});state.draft=d.draft;state.draftId=d.id;state.command=null;state.compose=true;}else if(a==='discard'){if(state.draftId)await api('deleteMailDraft',{draft_id:state.draftId});state.compose=false;state.draft={to:'',cc:'',bcc:'',subject:'',body:'',inbox_id:'',ticket_id:'',reply_message_id:''};state.draftId=null;state.command=null;state.notice='Borrador descartado.';}});
 });
 var dragged=null;
 document.addEventListener('dragstart',function(e){var row=e.target.closest('[data-group]');if(!host||!row||!host.contains(row))return;dragged=row.dataset.group;e.dataTransfer.setData('text/plain',dragged);e.dataTransfer.effectAllowed='move';});
 document.addEventListener('dragover',function(e){var row=e.target.closest('[data-group]');if(dragged&&host&&row&&host.contains(row))e.preventDefault();});
 document.addEventListener('drop',function(e){var row=e.target.closest('[data-group]');if(!dragged||!host||!row||!host.contains(row))return;e.preventDefault();var order=groupedBoxes().map(function(g){return groupKey(g[0]);}),from=order.indexOf(dragged),to=order.indexOf(row.dataset.group);if(from>=0&&to>=0){order.splice(from,1);order.splice(to,0,dragged);try{localStorage.setItem('dtg-mail-order:'+actor,JSON.stringify(order));}catch(e){}paint();}dragged=null;});document.addEventListener('dragend',function(){dragged=null;});
 function reset(){revision++;if(controller)controller.abort();clearInterval(poll);poll=null;host=null;actor=null;controller=null;state=initial();}
 root.DTGMail={openSettings:function(){if(!bridge.isAdmin())return;state.settings=true;paint();},configure:function(b){bridge=b;},show:function(h){if(actor!==bridge.actor()){reset();actor=bridge.actor();controller=new AbortController();}host=h;paint();if(!state.status&&!state.busy)run(load);if(!poll)poll=setInterval(function(){if(!host||!host.isConnected||document.hidden||state.busy)return;var pending=state.operations.filter(function(o){return ['queued','running','retry'].includes(o.state);});if(pending.length)run(async function(){for(var op of pending)remember(await api('operationStatus',{operation_id:op.operation_id}));});},5000);},hide:function(){host=null;clearInterval(poll);poll=null;},reset:reset};
})(window);
