const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const root=__dirname;
const actor='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',ticket='11111111-1111-4111-8111-111111111111';
const fixture=`AUTH_STATUS='signed_in';AUTH_SESSION={user:{id:'${actor}'}};CURRENT_PROFILE={id:AUTH_SESSION.user.id,active:true,role:'admin',display_name:'Martin'};STATE.meta={teamNames:[],queSigueOptions:[],opsProviders:[]};STATE.profiles=[{id:'${actor}',displayName:'Martin',active:true},{id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',displayName:'Ceci',active:true}];STATE.conversations=[];STATE.tickets=[{id:'${ticket}',seq:1411,cliente:'Cliente de prueba',visibility:'private',estado:'abierto',productos:[],tareas:[],workOrders:[],markers:[],thread:[],pagos:[],documentos:[]}];window.mailQA={switchActor:function(id,role,name){if(name)CURRENT_PROFILE.display_name=name;CURRENT_PROFILE.id=id;CURRENT_PROFILE.role=role;AUTH_SESSION.user.id=id;}};sb={auth:{getSession:async()=>({data:{session:{user:{id:CURRENT_PROFILE.id},access_token:'qa-only'}}})}};document.getElementById('app').innerHTML='<style>.sidebar-account-menu{position:static!important}</style>'+renderAccountMenu()+'<button data-action="go-correos">Correos</button>';`;
const html=fs.readFileSync(root+'/index.html','utf8').replace(/<script src="https:[^>]*><\/script>/g,'').replace(/\bboot\(\);(?=\s*\n\}\)\(\);)/,fixture);
const server=http.createServer((req,res)=>{const file=req.url.split('?')[0];res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');if(file==='/')return res.end(html);const target=path.join(root,file);if(!target.startsWith(root)||!fs.existsSync(target)){res.statusCode=404;return res.end();}res.end(fs.readFileSync(target));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{
 const page=await browser.newPage({viewport:{width:1280,height:900}}),requests=[],errors=[];let configured=true,hang=false,failSend=false;
 const inbox='22222222-2222-4222-8222-222222222222',second='33333333-3333-4333-8333-333333333333',message='44444444-4444-4444-8444-444444444444';let drafts={};
 const boxes=[{id:inbox,connection_id:'account1',email_alias:'hello@956print.com',account_email:'martin@956print.com',can_send:true,connected:true,active:true,verification_status:'accepted'},{id:second,connection_id:'account1',email_alias:'sales@956print.com',account_email:'martin@956print.com',can_send:true,connected:true,active:true,verification_status:'accepted'}];
 const metadata={id:message,connection_id:'account1',thread_id:'thread1',rfc_message_id:'<qa@example.com>',from_address:'Cliente <customer@example.com>',to_addresses:['hello@956print.com'],subject:'Pedido <script>evil</script>',snippet:'Quiero 24 playeras',direction:'inbound',label_ids:['INBOX','UNREAD'],occurred_at:new Date().toISOString()};
 page.on('pageerror',e=>errors.push(e.message));await page.route('**/functions/v1/integration-api',async route=>{const input=route.request().postDataJSON();requests.push(input);if(hang&&input.action==='status')return;let data;
 if(input.action==='status')data={enabled:configured,domain:'956print.com',inboxes:boxes,connections:[{id:'account1',account_email:'martin@956print.com',state:'connected'}],unread_snapshot:[{id:message,inbox_id:inbox},{id:message,inbox_id:second}],unread_capped:false,setup:{configured,connected:configured,missing:configured?[]:['GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET']}};
 else if(input.action==='listEmails')data=[metadata];
 else if(input.action==='getEmail')data={metadata,message:{}};
 else if(input.action==='getThread')data={messages:[{id:'gmail1',internalDate:String(Date.now()),payload:{mimeType:'text/plain',headers:[{name:'from',value:metadata.from_address},{name:'to',value:'hello@956print.com'}],body:{data:Buffer.from('<img src=x onerror=evil()> Hola').toString('base64url')}}}]};
 else if(input.action==='sendEmail'&&failSend)return route.fulfill({status:503,contentType:'application/json',body:'{"error":"PROVIDER_UNAVAILABLE"}'});
 else if(input.action==='sendEmail')data={operation_id:'55555555-5555-4555-8555-555555555555',state:'queued'};
 else if(input.action==='processMailOperation'||input.action==='operationStatus')data={operation_id:input.operation_id,state:'done'};
 else if(input.action==='saveMailDraft'){const id=input.draft_id||'66666666-6666-4666-8666-666666666666';drafts[id]=input.draft;data={id};}
 else if(input.action==='listMailDrafts')data=Object.keys(drafts).map(id=>({id,subject:drafts[id].subject,updated_at:new Date().toISOString()}));
 else if(input.action==='getMailDraft')data={id:input.draft_id,draft:drafts[input.draft_id]};
 else if(input.action==='deleteMailDraft'){delete drafts[input.draft_id];data={deleted:true};}
 else if(input.action==='beginOAuth')data={url:'https://accounts.google.com/o/oauth2/v2/auth?test=1'};
 else if(input.action==='configureMail'){configured=true;data={inboxes:boxes,enabled:false,connections:[],setup:{configured:true,connected:false,missing:[]}};}
 else if(input.action==='setEmailState'){metadata.label_ids=['INBOX'];data={label_ids:metadata.label_ids};}
 else data={ok:true};await route.fulfill({contentType:'application/json',body:JSON.stringify(data)});});
 await page.goto('http://127.0.0.1:'+server.address().port);assert.equal(requests.length,0,'mail stays outside critical startup');await page.getByRole('button',{name:'Configuración de correo',exact:true}).click();await page.locator('#mail-connect').waitFor();assert.deepEqual(await page.locator('#mail-permission [name=user_id] option').allTextContents(),['Elegir miembro','Martin','Ceci']);await page.getByRole('button',{name:'Conexiones y permisos',exact:true}).click();await page.locator('.mail-switch-toggle').click();await page.locator('.mail-account').first().waitFor({state:'attached'});assert.equal(await page.locator('.mail-account').count(),2);
 await page.locator('.mail-account').nth(1).click();await page.waitForFunction(()=>document.querySelector('.mail-account.selected').textContent.includes('sales@'));assert.equal(requests.filter(x=>x.action==='listEmails').at(-1).inbox_id,second);await page.locator('.mail-switch-toggle').click();await page.getByRole('button',{name:/^Colapsar o expandir/}).first().click();assert.equal(await page.locator('.mail-group-aliases').count(),1);await page.getByRole('button',{name:/^Subir/}).nth(1).click();assert.match(await page.locator('.mail-account').first().textContent(),/sales@/);await page.locator('.mail-switch-toggle').click();
 await page.locator('.mail-row').first().click();await page.locator('.mail-message pre').waitFor();assert.match(await page.locator('.mail-message pre').textContent(),/<img/);assert.equal(await page.locator('.mail-message img').count(),0);
 await page.getByRole('button',{name:'Responder',exact:true}).click();await page.locator('#mail-compose-form').waitFor();assert.equal(await page.locator('[name=to]').inputValue(),'customer@example.com');assert.equal(await page.locator('#mail-compose-form [name=inbox_id]').inputValue(),second);
 await page.locator('[name=cc]').fill('copy@example.com');await page.locator('[name=bcc]').fill('hidden@example.com');await page.locator('[name=body]').fill('Respuesta editable');await page.locator('#mail-compose-form [name=ticket_id]').selectOption(ticket);
 failSend=true;await page.getByRole('button',{name:'Enviar correo',exact:true}).click();await page.locator('[role=alert]').waitFor();assert.equal(await page.locator('[name=body]').inputValue(),'Respuesta editable');const first=requests.filter(x=>x.action==='sendEmail').at(-1);assert.equal(first.reply_message_id,message);assert.deepEqual(first.cc,['copy@example.com']);assert.deepEqual(first.bcc,['hidden@example.com']);
 failSend=false;await page.getByRole('button',{name:'Enviar correo',exact:true}).click();await page.getByText('Aceptado por Gmail',{exact:false}).waitFor();assert.equal(requests.filter(x=>x.action==='sendEmail').at(-1).idempotency_key,first.idempotency_key);assert.equal(await page.locator('#mail-compose-form').count(),0);
 await page.getByRole('button',{name:'Redactar',exact:true}).click();await page.locator('[name=subject]').fill('Borrador privado');await page.locator('[name=body]').fill('Retomar después');await page.getByRole('button',{name:'Guardar borrador',exact:true}).click();await page.getByText('Borrador guardado en tu cuenta del CRM.',{exact:true}).waitFor();await page.getByRole('button',{name:'Cerrar borrador',exact:true}).click();await page.getByRole('button',{name:'Borradores',exact:true}).click();await page.getByRole('button',{name:'Borrador privado',exact:false}).click();assert.equal(await page.locator('[name=body]').inputValue(),'Retomar después');
 hang=true;await page.evaluate(()=>{const timeout=AbortSignal.timeout.bind(AbortSignal);AbortSignal.timeout=()=>timeout(50);});await page.getByRole('button',{name:'Actualizar',exact:true}).click();await page.getByText('La conexión tardó demasiado.',{exact:false}).waitFor();assert.equal(await page.locator('[name=body]').inputValue(),'Retomar después');hang=false;await page.getByRole('button',{name:'Cerrar borrador',exact:true}).click();
 for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no horizontal overflow at '+width);}
 configured=false;await page.getByRole('button',{name:'Actualizar',exact:true}).click();await page.getByRole('button',{name:'Conexiones y permisos',exact:true}).click();await page.locator('#mail-oauth-config').waitFor();await page.locator('#mail-oauth-config [name=client_id]').fill('qa.apps.googleusercontent.com');await page.locator('#mail-oauth-config [name=client_secret]').fill('qa-only-secret');await page.getByRole('button',{name:'Guardar credenciales de Google',exact:true}).click();await page.getByText('Credenciales guardadas.',{exact:false}).waitFor();assert(!(await page.locator('.mail-workspace').textContent()).includes('qa-only-secret'));await page.locator('#mail-connect [name=account_email]').fill('martin@956print.com');await page.getByRole('button',{name:'Conectar cuenta',exact:true}).click();await page.getByRole('link',{name:'Autorizar en Google',exact:true}).waitFor();assert.equal(requests.filter(x=>x.action==='beginOAuth').at(-1).account_email,'martin@956print.com');
 await page.evaluate(()=>{mailQA.switchActor('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','member');DTGMail.reset();DTGMail.show(document.getElementById('dtg-mail-root'));});await page.locator('.mail-account').first().waitFor({state:'attached'});assert.equal(await page.getByRole('button',{name:'Conexiones y permisos',exact:true}).count(),0);assert.equal(await page.locator('#mail-compose-form').count(),0);assert.deepEqual(errors,[]);boxes.forEach(b=>b.logical_inbox='commercial');await page.reload();await page.getByRole('button',{name:'Configuración de correo',exact:true}).click();await page.locator('.mail-account').first().waitFor({state:'attached'});assert.equal(await page.locator('.mail-account').count(),1);assert.equal(await page.locator('.mail-unread').textContent(),'1');assert.match(await page.locator('.mail-account').textContent(),/hello@.*sales@/);assert.equal(await page.locator('.mail-row').count(),1,'duplicate message across grouped aliases appears once');assert.equal(new Set(requests.filter(x=>x.action==='listEmails').slice(-2).map(x=>x.inbox_id)).size,2,'group reads each authorized alias');boxes.push({id:'77777777-7777-4777-8777-777777777777',email_alias:'jona@956print.com',logical_inbox:'personal-jona',connection_id:'account1',can_send:true,connected:true,active:true,verification_status:'accepted'});await page.evaluate(()=>{mailQA.switchActor('cccccccc-cccc-4ccc-8ccc-cccccccccccc','member','Jonathan');DTGMail.reset();DTGMail.show(document.getElementById('dtg-mail-root'));});await page.waitForFunction(()=>document.querySelector('.mail-switch-toggle').textContent.includes('jona@'));await page.locator('.mail-switch-toggle').click();assert.match(await page.locator('.mail-account').first().textContent(),/jona@/);assert.match(await page.locator('.mail-account').nth(1).textContent(),/Ventas/);console.log('PASS actual Correos navigation; alias switch; safe thread; explicit reply with CC/CCO and ticket; same-key retry; encrypted-draft API; timeout preserves editor; role/session isolation; 320–1280px; no startup calls. Provider and session mocked.');
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
