const fs=require('fs'),assert=require('assert'),{chromium}=require('playwright');
const waFile=fs.existsSync(__dirname+'/wa-inbox-qa.cjs')?'wa-inbox-qa.cjs':'CHAT-INBOX-QA.cjs';
let fixture=fs.readFileSync(__dirname+'/'+waFile,'utf8').match(/const fixture=`([\s\S]*?)`;/)[1];
fixture=fixture.slice(0,fixture.lastIndexOf('render();'))+`
STATE.clientes=[{id:'client',nombre:'Impresiones y diseños Matamoros',empresa:'Cliente con nombre largo',telefono:'8681234567',email:'qa@example.invalid',createdAt:'2026-09-01T12:00:00Z'},...Array.from({length:30},(_,i)=>({id:'client'+i,nombre:'Cliente de prueba '+i,createdAt:'2026-09-01T12:00:00Z'}))];
STATE.tickets=Array.from({length:18},(_,i)=>({id:'t'+i,seq:100+i,clienteId:'client',cliente:STATE.clientes[0].nombre,responsable:'Jonathan',estado:i===17?'entregado':'abierto',entregadoAt:i===17?'2026-09-01T12:00:00Z':null,createdAt:'2026-09-01T12:00:00Z',lastActivityAt:'2026-10-01T12:00:00Z',fechaAtencion:'2026-10-01',fechaCompromiso:'2026-10-02',queSigue:'Preparar archivos y confirmar medidas con cliente',visibility:'public',productos:[{id:'prod'+i,desc:'Lona con impresión de alta resolución',cantidad:2,precio:100}],pagos:[],documentos:[],thread:[],markers:[],workOrders:[],accessProfileIds:[],tareas:[{id:'task'+i,desc:'Comprar vinil negro para el pedido',tipo:'produccion',area:'planeacion',tipoOperacion:'Compra',estado:'pendiente',progreso:0,responsable:'Jonathan',fechaAtencion:'2026-10-01'}]}));
Object.assign(qa,{openOpsEditor,openCierreModalForTicket,openDocumentForm,resetDisclosure:()=>MOBILE_DISCLOSURE=Object.create(null),view:v=>{UI.selectedTicketId=null;UI.selectedClienteId=null;UI.operaciones.editor=null;UI.mainView=v;render();},ticket:()=>{UI.mainView='tickets';UI.selectedTicketId='t0';render();},client:()=>{UI.selectedTicketId=null;UI.mainView='clientes';UI.selectedClienteId='client';render();}});render();
`;
let html=fs.readFileSync(__dirname+'/index.html','utf8').replace(/<script[^>]*src=[^>]*><\/script>/g,'').replace(/\bboot\(\);(?=\s*\n\}\)\(\);)/,fixture);
html=html.replace('<script>','<script>'+fs.readFileSync(__dirname+'/ops-menu.js','utf8')+'</script><script>');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_BIN||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'}),errors=[];page.setDefaultTimeout(8000);page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.abort());await page.setContent(html);assert.deepEqual(errors,[]);
for(const width of [320,390,768]){await page.setViewportSize({width,height:844});for(const v of ['tickets','operaciones','calendario','clientes','biblioteca','cxc','informes']){await page.evaluate(v=>qa.view(v),v);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,v+' overflows '+width);const title=await page.locator(v==='calendario'?'.dc-heading h1':'.mobile-page-title').textContent();assert(title.length>0);const small=await page.locator('.main button:visible').evaluateAll(nodes=>nodes.filter(e=>e.getBoundingClientRect().height<43.9).map(e=>({text:e.textContent,cls:e.className,h:e.getBoundingClientRect().height})));assert.deepEqual(small,[],v+' tiny touch targets '+JSON.stringify(small));}}
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>qa.view('operaciones'));
assert.equal(await page.locator('#ops-board').count(),0);assert(await page.getByRole('tab',{name:'Planeación',exact:true}).isVisible());
await page.getByRole('tab',{name:'Planeación',exact:true}).click();assert.equal(await page.evaluate(()=>qa.UI.operaciones.workView),'planeacion');
await page.evaluate(()=>qa.render());assert.equal(await page.getByRole('tab',{name:'Planeación',exact:true}).getAttribute('aria-selected'),'true');
await page.screenshot({path:__dirname+'/mobile-operations.png'});
await page.getByRole('button',{name:'+ Tarea',exact:true}).click();await page.locator('#ops-f-desc').selectOption({label:'ENVIAR DTF'});await page.locator('#ops-f-resp').selectOption({label:'Jonathan'});assert.equal(await page.locator('#ops-f-desc').inputValue(),'ENVIAR DTF');const modal=await page.locator('.ops-editor').boundingBox();assert(modal.x>=0&&modal.x+modal.width<=390&&modal.height<=844);assert.equal(await page.locator('#ops-f-desc').evaluate(el=>getComputedStyle(el).fontSize),'16px');await page.screenshot({path:__dirname+'/mobile-task.png'});
await page.evaluate(()=>qa.view('tickets'));await page.getByRole('button',{name:'Mostrar vistas y filtros'}).click();await page.locator('[data-mobile-choice="tickets-view"]').selectOption({label:'Detalles'});assert.equal(await page.evaluate(()=>qa.UI.ticketsView),'details');assert(await page.locator('.mobile-table-hint').isVisible());assert.equal(await page.locator('.tickets-details-wrap').getAttribute('role'),'region');await page.locator('[data-mobile-choice="tickets-view"]').selectOption({label:'Responsables'});assert.equal(await page.evaluate(()=>qa.UI.ticketsView),'kanban');assert((await page.locator('#kanban-board-tabs [aria-selected="true"]').textContent()).includes('Jonathan'));await page.evaluate(()=>qa.render());assert((await page.locator('#kanban-board-tabs [aria-selected="true"]').textContent()).includes('Jonathan'));assert(await page.locator('.kanban-add-task').first().isVisible());await page.locator('.kanban-add-task').first().click();assert(await page.locator('#ops-f-desc').isEditable());
await page.locator('[data-action="ops-ed-close"]').first().click();await page.evaluate(()=>qa.ticket());assert.equal(await page.locator('.tk-chips').isVisible(),false);await page.locator('[data-mobile-disclosure="ticket-details"] summary').click();assert.equal(await page.locator('[data-action="header-edit"][data-field="quesigue"]').count(),0);assert.equal(await page.locator('[data-mobile-disclosure="ticket-details"]').getAttribute('open')!==null,true);await page.screenshot({path:__dirname+'/mobile-ticket.png'});
await page.evaluate(()=>{qa.UI.headerEditField=null;qa.client();});assert.equal(await page.locator('.ficha-identity-controls').isVisible(),false);await page.locator('[data-mobile-disclosure="client-style"] summary').click();assert(await page.locator('.ficha-identity-controls').isVisible());await page.locator('[data-mobile-choice="client-history"]').selectOption({index:1});assert.notEqual(await page.evaluate(()=>qa.UI.clienteHistoriaFilter),'todo');await page.screenshot({path:__dirname+'/mobile-client.png'});
await page.evaluate(()=>qa.view('biblioteca'));await page.locator('[data-mobile-disclosure="photo-filters"] summary').click();await page.locator('[data-action="biblioteca-filter-fecha"]').selectOption('hoy');assert.equal(await page.evaluate(()=>qa.UI.biblioteca.fecha),'hoy');
await page.evaluate(()=>qa.view('calendario'));assert.equal(await page.locator('.calendar-tipo-switch').count(),0);await page.getByRole('tab',{name:'Semana',exact:true}).click();assert.equal(await page.evaluate(()=>qa.UI.calendar.view),'week');assert.equal(await page.evaluate(()=>qa.UI.calendar.tipo),'compromiso');assert(await page.locator('[data-dc="mine"]').isVisible());await page.screenshot({path:__dirname+'/mobile-calendar.png'});
await page.evaluate(()=>qa.view('cxc'));assert.equal(await page.locator('.cxc-aging').isVisible(),false);await page.locator('[data-mobile-disclosure="cxc-aging"] summary').click();assert(await page.locator('.cxc-aging').isVisible());assert(await page.locator('[data-action="cxc-pago-open"]').isVisible());await page.screenshot({path:__dirname+'/mobile-cxc.png'});
await page.evaluate(()=>qa.view('informes'));await page.locator('[data-mobile-choice="report-period"]').selectOption({label:'Rango'});assert.equal(await page.evaluate(()=>qa.UI.informes.period),'rango');assert(await page.locator('#informes-from').isVisible());await page.locator('[data-mobile-disclosure="report-0"] summary').click();assert(await page.locator('.report-card').first().isVisible());await page.screenshot({path:__dirname+'/mobile-reports.png'});
await page.evaluate(()=>qa.view('clientes'));await page.locator('.clientes-view').evaluate(el=>el.scrollTop=300);const scroll=await page.locator('.clientes-view').evaluate(el=>el.scrollTop);await page.evaluate(()=>qa.render());assert(scroll>0);assert.equal(await page.locator('.clientes-view').evaluate(el=>el.scrollTop),scroll);
await page.setViewportSize({width:320,height:480});
await page.evaluate(()=>{qa.STATE.tickets[0].thread=[{id:'photo',type:'archivo',storage_path:'qa/photo.jpg',filename:'photo.jpg',ts:new Date().toISOString(),autor:'Martin'}];qa.UI.biblioteca.fecha='todas';qa.view('biblioteca');});assert(await page.locator('.biblioteca-tile').isVisible());assert.equal(await page.locator('.biblioteca-tile').evaluate(el=>Math.round(el.getBoundingClientRect().width)),await page.locator('.biblioteca-tile').evaluate(el=>Math.round(el.getBoundingClientRect().height)));
await page.evaluate(()=>qa.client());if(!await page.locator('.cid-swatch').first().isVisible())await page.locator('[data-mobile-disclosure="client-style"] summary').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const swatch=await page.locator('.cid-swatch').first().boundingBox();assert(swatch.width>=44&&swatch.height>=44);
await page.evaluate(()=>qa.view('operaciones'));await page.getByRole('button',{name:'+ Tarea',exact:true}).click();await page.locator('#ops-f-desc').selectOption({label:'CORTAR'});const smallModal=await page.locator('.ops-editor').boundingBox();assert(smallModal.x>=0&&smallModal.width<=320&&smallModal.height<=480);await page.locator('[data-action="ops-ed-save"]').scrollIntoViewIfNeeded();const save=await page.locator('[data-action="ops-ed-save"]').boundingBox();assert(save.y>=0&&save.y+save.height<=480);assert.equal(await page.locator('#ops-f-desc').inputValue(),'CORTAR');
await page.evaluate(()=>{qa.UI.operaciones.editor=null;qa.ticket();qa.openDocumentForm('invoice');});await page.locator('#docform-po').fill('PO-123');const doc=await page.locator('.docform-modal').boundingBox();assert(doc.x>=0&&doc.width<=320&&doc.height<=480);await page.locator('[data-action="docform-step"]').scrollIntoViewIfNeeded();const preview=await page.locator('[data-action="docform-step"]').boundingBox();assert(preview.y>=0&&preview.y+preview.height<=480);await page.locator('[data-action="docform-step"]').click();assert(await page.locator('.docform-modal-preview').isVisible());assert.equal(await page.evaluate(()=>qa.UI.docDraft.poReference),'PO-123');await page.locator('[data-action="close-docform"]').first().click();
await page.evaluate(()=>qa.view('informes'));await page.setViewportSize({width:1280,height:900});assert(await page.locator('.report-card-head').first().isVisible());assert(await page.locator('[data-action="informes-period"]').first().isVisible());await page.evaluate(()=>qa.view('operaciones'));assert.equal(await page.locator('#ops-board').count(),0);assert(await page.getByRole('tab',{name:'Activas',exact:true}).isVisible());assert.equal(await page.locator('.mobile-choice:visible').count(),0);await page.evaluate(()=>qa.view('informes'));assert(await page.locator('.report-card-head').first().isVisible());assert(await page.locator('[data-action="informes-period"]').first().isVisible());assert.deepEqual(errors,[]);
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{qa.resetDisclosure();qa.UI.operaciones.responsable='';qa.UI.calendar.view='agenda';qa.UI.calendar.tipo='todos';qa.UI.informes.period='mes';});for(const v of ['operaciones','tickets','calendario','informes']){await page.evaluate(v=>qa.view(v),v);await page.screenshot({path:__dirname+'/mobile-final-'+v+'.png'});}
console.log('PASS mobile app: 320/390/768px seven views, existing filters/periods/tabs, task draft/modal, Kanban create, ticket edits, client styling/history, CxC disclosure, report disclosure, scroll restoration and desktop controls.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
