const fs=require('fs'),path=require('path'),assert=require('assert'),vm=require('vm'),{pathToFileURL}=require('url'),{chromium}=require('playwright');
const {validate,productionRefs}=require('./staging/policy.js'),{build}=require('./scripts/staging/build.cjs'),{connection}=require('./scripts/staging/config.cjs');
// Reserved .test origins and synthetic refs: never real infrastructure identifiers.
const config={environment:'staging',appUrl:'https://crm-staging.test',crmProjectRef:'a'.repeat(20),peProjectRef:'b'.repeat(20),supabaseUrl:'https://'+'a'.repeat(20)+'.supabase.co',supabasePublishableKey:'sb_publishable_fixture',productEngineUrl:'https://pe-staging.test',productionOrigins:['https://impresionesmatamoros.github.io','https://jpjpnxamiclvhmcywyhx.supabase.co'],ownerConfirmedIsolation:true,externalEffects:{whatsapp:false,email:false,push:false,payments:false,webhooks:false,transcription:false}};
for(const r of productionRefs)assert.throws(()=>validate({...config,crmProjectRef:r,supabaseUrl:'https://'+r+'.supabase.co'}));
assert.throws(()=>validate({...config,ownerConfirmedIsolation:false}));assert.throws(()=>validate({...config,peProjectRef:config.crmProjectRef}));assert.throws(()=>validate({...config,externalEffects:{...config.externalEffects,email:true}}));assert.throws(()=>validate({...config,supabaseUrl:'https://other.test'}));assert.throws(()=>validate({...config,appUrl:'https://impresionesmatamoros.github.io/test'}));assert.throws(()=>validate({...config,supabasePublishableKey:'sb_secret_not_allowed'}));assert.throws(()=>validate(JSON.parse(fs.readFileSync('staging/environment.example.json','utf8'))));
assert.throws(()=>connection('postgres://postgres:fake@db.jpjpnxamiclvhmcywyhx.supabase.co/postgres',config.crmProjectRef));assert.throws(()=>connection('postgres://postgres:fake@arbitrary.test/postgres',config.crmProjectRef));
assert.equal(connection('postgres://postgres:fake@db.'+config.crmProjectRef+'.supabase.co/postgres',config.crmProjectRef).includes(config.crmProjectRef),true);
const out=build(config,path.join(__dirname,'dist/staging-qa'));
assert.throws(()=>build(config,path.join(__dirname,'supabase')));
assert(!fs.readFileSync(path.join(out,'sw.js'),'utf8').includes('showNotification'));assert(!fs.existsSync(path.join(out,'staging/fixtures.sql')));assert.equal(JSON.parse(fs.readFileSync(path.join(out,'manifest.webmanifest'))).short_name,'DTG TEST');
const source=fs.readFileSync('index.html','utf8');assert(!source.includes('sb_publishable_PlY_'));assert(!source.includes('<<<<<<<'));assert(source.includes('fetchClientes(), fetchTicketMarkers()'));assert(source.includes('function ticketSearchInput'));assert(source.includes('var cxFetch=fetchAllState'));
for(const m of source.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g))if(m[1].trim())new vm.Script(m[1]);
const workflow=fs.readFileSync('.github/workflows/staging.yml','utf8');assert(!workflow.includes('branches: [main]'));assert(!workflow.includes('pages: write'));assert(!workflow.includes('id-token: write'));assert(!workflow.includes('environment: production'));
const stub=fs.readFileSync('staging/blocked-function.ts','utf8');assert(!stub.includes('await fetch'));assert(!stub.includes('SUPABASE_SERVICE_ROLE_KEY'));
// Intercept CLI provisioning to verify the plan without contacting Supabase.
const cli=require('child_process'),savedCli=cli.execFileSync,savedEnv={...process.env},commands=[];
const fixtureFile=path.join(out,'qa-config.json');fs.writeFileSync(fixtureFile,JSON.stringify(config));
process.env.STAGING_CONFIG_FILE=fixtureFile;process.env.STAGING_CONFIRMED_PROJECT_REF=config.crmProjectRef;process.env.SUPABASE_ACCESS_TOKEN='fixture-only-token';process.env.STAGING_PE_BASE_URL=config.productEngineUrl;process.env.STAGING_PE_API_TOKEN='fixture-only-token-with-at-least-32-characters';
cli.execFileSync=function(bin,args,options){commands.push(args);assert(args.includes(config.crmProjectRef));assert(!args.some(a=>productionRefs.includes(a)));if(args[0]==='functions'){const name=args[2],file=path.join(options.cwd,'supabase/functions',name,'index.ts');if(name!=='product-engine-proxy')assert.equal(fs.readFileSync(file,'utf8'),stub);}return Buffer.from('');};
try{console.log('QA: Supabase CLI is intercepted; no remote provisioning will occur.');require('./scripts/staging/deploy-functions.cjs').deploy();assert.equal(commands.length,4);assert.equal(commands[0][0],'secrets');process.env.STAGING_CONFIRMED_PROJECT_REF=productionRefs[0];assert.throws(()=>require('./scripts/staging/deploy-functions.cjs').deploy());assert.equal(commands.length,4);}finally{cli.execFileSync=savedCli;for(const k of Object.keys(process.env))if(!(k in savedEnv))delete process.env[k];Object.assign(process.env,savedEnv);}
(async()=>{
 const {handle}=await import(pathToFileURL(path.join(__dirname,'supabase/functions/product-engine-proxy/handler.js')).href);
 let calls=0;const req=()=>new Request('https://function.test',{method:'POST',headers:{Authorization:'Bearer fixture'},body:JSON.stringify({op:'health'})});
 const env={DTG_ENVIRONMENT:'staging',STAGING_CRM_PROJECT_REF:config.crmProjectRef,SUPABASE_URL:config.supabaseUrl,STAGING_PE_ORIGIN:new URL(config.productEngineUrl).origin,PRODUCT_ENGINE_BASE_URL:config.productEngineUrl,PRODUCT_ENGINE_API_TOKEN:'fixture-token-not-a-real-secret'};
 const deps={env,verifyUser:async()=>true,fetchImpl:async()=>{calls++;return new Response('{}',{status:200});}};
 assert.equal((await handle(req(),{...deps,env:{...env,SUPABASE_URL:'https://jpjpnxamiclvhmcywyhx.supabase.co'}})).status,503);assert.equal(calls,0);assert.equal((await handle(req(),deps)).status,200);assert.equal(calls,1);
 const browser=await chromium.launch({executablePath:process.env.CHROME_BIN||undefined,headless:true});
 try{
  const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[],requests=[];page.setDefaultTimeout(6000);page.on('pageerror',e=>{errors.push(e.message);console.error('Browser:',e.message);});
  const sdk='window.sdkCalls=[];window.supabase={createClient:(url,key)=>{sdkCalls.push({url,key});return {auth:{getSession:async()=>({data:{session:null},error:null}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})}}}};';
  await page.route('**/*',async route=>{const u=new URL(route.request().url());requests.push(u.href);if(u.hostname==='cdn.jsdelivr.net')return route.fulfill({contentType:'application/javascript',body:sdk});if(u.origin===config.appUrl){const name=u.pathname==='/'?'index.html':decodeURIComponent(u.pathname.slice(1));const file=path.resolve(out,name);if(file.startsWith(out+path.sep)&&fs.existsSync(file)&&fs.statSync(file).isFile())return route.fulfill({path:file});}return route.abort();});
  await page.goto(config.appUrl);await page.waitForSelector('#dtg-staging-banner');await page.waitForTimeout(100);
  assert.equal(await page.title(),'DTG CRM — STAGING');assert((await page.locator('#dtg-staging-banner').textContent()).includes('OFF'));assert.equal(await page.evaluate(()=>DTG_STAGING_VALIDATED),true);assert.equal(await page.evaluate(()=>sdkCalls[0].url),config.supabaseUrl);assert.equal(await page.locator('#login-email').count()>0||await page.locator('input[type=email]').count()>0,true);
  const results=await page.evaluate(async()=>{const urls=['https://jpjpnxamiclvhmcywyhx.supabase.co/rest/v1/tickets','https://wa.me/15555555555','https://api.stripe.com/v1/payment_intents',DTG_ENV.supabaseUrl+'/functions/v1/push-fanout',DTG_ENV.supabaseUrl+'/functions/v1/transcribe-chat-audio',DTG_ENV.supabaseUrl+'/auth/v1/recover'];return await Promise.all(urls.map(async url=>{try{await fetch(url);return false;}catch(e){return true;}}));});assert(results.every(Boolean));
  await page.evaluate(()=>{const a=document.createElement('a');a.id='qa-external';a.href='mailto:cliente@example.invalid';a.textContent='Email';a.style.cssText='position:fixed;top:100px;left:10px;z-index:2147483646';document.body.appendChild(a);});await page.locator('#qa-external').click();assert.equal(await page.evaluate(()=>window.open('https://wa.me/15555555555')),null);assert.equal(await page.evaluate(()=>navigator.sendBeacon('https://production.test','x')),false);
  assert(!requests.some(u=>u.includes('jpjpnxamiclvhmcywyhx')||u.includes('wa.me')||u.includes('api.stripe.com')));assert.deepEqual(errors,[]);
  // Missing config stops before client/session/database creation.
  await page.route('**/environment.js',r=>r.fulfill({contentType:'application/javascript',body:fs.readFileSync('environment.js','utf8')}));await page.reload();await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>DTG_STAGING_VALIDATED),false);assert.equal(await page.evaluate(()=>sdkCalls.length),0);assert((await page.locator('#app').textContent()).includes('sin configurar'));
  await page.setViewportSize({width:1280,height:900});assert(await page.locator('#dtg-staging-banner').isVisible());assert.deepEqual(errors,[]);
 }finally{await browser.close();}
 console.log('PASS STAGING: fail-closed config, all known project refs denied, separate app/CRM/PE origins, no public secret key, blocked external transports/contact links/Auth email endpoints, banner on mobile/PC, inert SW, staging-only workflow, proxy isolation, safe build paths, current CRM changes retained. All network targets were intercepted test fixtures; no remote staging or production DB accessed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
