const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
const fixture=`<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="/client-library.css"><style>body{margin:0;background:#17191e;color:white;font:14px Arial}.btn{color:inherit;background:#292e36;border:1px solid #666;border-radius:6px;padding:8px}.person-avatar img{width:32px;height:32px}</style><button data-library="entry" data-customer="customer-1">Archivos</button><script src="/library-transfer.js"></script><script src="/client-library.js"></script><script src="/image-thumbnails.js"></script><script>
window.mock={files:[],sessions:{},offset:0,puts:0,calls:[],derivatives:{},signs:0};let actor='actor-1';
window.DTGWorkspaceAPI={message:e=>e.code,request:async function(action,input,opts){mock.calls.push({action,binary:!!(opts&&opts.binary)});if(action==='libraryStatus')return {enabled:true,identity:{email:'staff@956print.com'},max_file_bytes:2147483648};if(action==='listLibraryFiles')return {files:mock.files.filter(f=>!input.search||f.filename.includes(input.search)),has_more:false};if(action==='findLibraryDuplicate')return {files:mock.files.filter(f=>f.source_sha256===input.source_sha256)};if(action==='beginLibraryUpload'){let s=Object.assign({},input,{session_id:'session-'+input.idempotency_key,file_id:'file-'+input.idempotency_key,provider:'GOOGLE_DRIVE',confirmed_offset:0,state:'pending'});mock.sessions[s.session_id]=s;return s;}if(action==='directUploadSession')return Object.assign({},mock.sessions[input.session_id],{upload_url:'https://www.googleapis.com/upload/drive/v3/files?upload_id=fixture'});if(action==='resumeUpload')return Object.assign({},mock.sessions[input.session_id],{confirmed_offset:mock.offset});if(action==='completeUpload'){let s=mock.sessions[input.session_id];if(!mock.files.some(f=>f.id===s.file_id))mock.files.push({id:s.file_id,asset_id:s.asset_id||s.file_id,filename:s.filename,size_bytes:s.size_bytes,source_sha256:s.source_sha256,category:'corel',version:1,stage:'Draft',availability:'available',origin_ticket_id:null});return {state:'complete',file_id:s.file_id};}if(action==='previewUpload')return {};if(action==='directFileAccess')return {url:'https://drive.google.com/file/d/test/view',download_url:'https://drive.google.com/uc?export=download&id=test',account_email:'staff@956print.com'};if(action==='resolveThumbnails')return {images:input.images.map(i=>({key:i.key,url:actor==='actor-1'?mock.derivatives[i.key]||null:null,denied:actor!=='actor-1'}))};if(action==='registerThumbnail'){const url=URL.createObjectURL(opts.binary);mock.derivatives[input.source_bucket+':'+input.source_path+':'+input.variant]=url;return {url};}throw Error('Unexpected API '+action);}};
DTGClientLibrary.mount({actor:()=>actor,isAdmin:()=>true,customer:()=>({nombre:'Cliente piloto'})});
DTGImages.mount({actor:()=>actor,originalURL:async()=>{mock.signs++;return location.origin+'/source.svg';}});
window.addImages=()=>{document.querySelectorAll('.person-avatar').forEach(n=>n.remove());for(let i=0;i<4;i++){let span=document.createElement('span');span.className='person-avatar';let img=document.createElement('img');img.dataset.storagePath='avatar.jpg';img.dataset.storageBucket='profile-avatars';span.appendChild(img);document.body.appendChild(span);DTGImages.observe(img);}};
window.switchActor=()=>{actor='actor-2';DTGImages.reset();};
</script>`;
const server=http.createServer((req,res)=>{let name=new URL(req.url,'http://localhost').pathname;if(name==='/fixture'){res.setHeader('Content-Type','text/html');res.end(fixture);return;}if(name==='/source.svg'){res.setHeader('Content-Type','image/svg+xml');res.setHeader('Access-Control-Allow-Origin','*');res.end('<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512"><rect width="512" height="512" fill="#38b"/></svg>');return;}let file=path.resolve(root,'.'+name);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.statusCode=404;res.end();return;}res.setHeader('Content-Type',name.endsWith('.css')?'text/css':'text/javascript');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser=await chromium.launch({executablePath:process.env.CHROME_BIN||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{for(const width of [1280,390]){let page=await browser.newPage({viewport:{width,height:850}}),errors=[],lost=false;page.setDefaultTimeout(7000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')console.log('Browser error:',m.text());});await page.route('https://www.googleapis.com/**',async route=>{let r=route.request();if(r.method()==='OPTIONS'){await route.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'PUT','Access-Control-Allow-Headers':'content-range,content-type'}});return;}assert.equal(r.method(),'PUT');assert.equal(r.headers().authorization,undefined);let match=r.headers()['content-range'].match(/bytes (\d+)-(\d+)\/(\d+)/);assert(match);let offset=Number(match[2])+1,total=Number(match[3]);assert.equal(r.postDataBuffer().length,offset-Number(match[1]));await page.evaluate(n=>{mock.offset=n;mock.puts++;},offset);if(!lost&&Number(match[1])===4194304){lost=true;await route.abort('failed');return;}await route.fulfill({status:offset===total?200:308,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Expose-Headers':'Range','Range':'bytes=0-'+(offset-1),'Content-Type':'application/json'},body:offset===total?'{}':''});});
 await page.goto('http://127.0.0.1:'+server.address().port+'/fixture');await page.getByRole('button',{name:'Archivos',exact:true}).click();await page.waitForSelector('[data-library="run"]',{state:'detached'});await page.locator('[data-library-form="add"] input[name="files"]').setInputFiles({name:'diseño.CDR',mimeType:'application/octet-stream',buffer:Buffer.alloc(10*1048576,7)});await page.getByRole('button',{name:'Agregar a la cola'}).click();await page.getByRole('button',{name:'Iniciar o reanudar'}).click();try{await page.waitForFunction(()=>mock.files.length===1,{},{timeout:10000});}catch(e){console.log(await page.locator('body').innerText());console.log(await page.evaluate(()=>({calls:mock.calls,sessions:mock.sessions,puts:mock.puts})));throw e;}await page.waitForFunction(()=>document.querySelector('.library-queue').textContent.includes('Guardado'));assert.equal(await page.evaluate(()=>mock.puts),3);assert.equal(await page.evaluate(()=>mock.calls.some(c=>c.binary&&c.action!=='previewUpload')),false);assert(lost);
 // Closing and reopening restores the local manifest without storing a Google URI.
 await page.getByRole('button',{name:'Cerrar',exact:true}).click();await page.getByRole('button',{name:'Archivos',exact:true}).click();await page.waitForSelector('.library-queue');assert((await page.locator('.library-queue').textContent()).includes('Guardado'));assert.equal(await page.evaluate(()=>Object.values(localStorage).some(v=>v.includes('upload_id'))),false);
 await page.locator('details.library-upload').evaluate(el=>el.open=true);await page.locator('[data-library-form="add"] input[name="files"]').setInputFiles({name:'copia.CDR',mimeType:'application/octet-stream',buffer:Buffer.alloc(10*1048576,7)});await page.getByRole('button',{name:'Agregar a la cola'}).click();await page.getByRole('button',{name:'Iniciar o reanudar'}).click();await page.waitForSelector('[data-library="skip"]');assert.equal(await page.evaluate(()=>mock.files.length),1);await page.getByRole('button',{name:'Usar el archivo existente'}).click();await page.waitForFunction(()=>document.querySelector('.library-queue').textContent.includes('Omitido'));
 await page.screenshot({path:path.join(root,'..','library-qa-'+width+'.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.getByRole('button',{name:'Cerrar',exact:true}).click();await page.evaluate(()=>addImages());await page.waitForFunction(()=>Array.from(document.querySelectorAll('.person-avatar img')).every(i=>i.naturalWidth===96));assert.equal(await page.evaluate(()=>mock.calls.filter(c=>c.action==='registerThumbnail').length),1);assert.equal(await page.evaluate(()=>mock.signs),1);let count=await page.evaluate(()=>mock.calls.length);await page.evaluate(()=>addImages());await page.waitForFunction(()=>Array.from(document.querySelectorAll('.person-avatar img')).every(i=>i.naturalWidth===96));assert.equal(await page.evaluate(()=>mock.calls.length),count);await page.evaluate(()=>{switchActor();addImages();});await page.waitForTimeout(120);assert.equal(await page.evaluate(()=>Array.from(document.querySelectorAll('.person-avatar img')).every(i=>!i.getAttribute('src'))),true);assert.deepEqual(errors,[]);await page.close();console.log('PASS',width,'direct bytes, lost response recovery, persistent manifest, explicit dedup, 96px private shared thumbnails and account isolation');}
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exit(1);});
