-- GENERATED by scripts/generate-seeds.ts — DO NOT EDIT. Source: data/reference.ts.
-- REFERENCE DATA (ADR-0013). Provisional values: FX 16.50, MX factor 0.70.

insert into market (id, code, name, default_currency) values
  ('b6319fd5-78f4-5e74-8ca0-84db2e246a43', 'USA', 'Estados Unidos', 'USD'),
  ('3eed2c9d-11f4-563f-98bb-dd0d23080d49', 'MX', 'México', 'MXN');

insert into price_book (id, code, market_id, currency, mode, source_price_book_id, default_factor) values
  ('096f98ae-3ce4-5963-b616-95dd648cff87', 'USA_MASTER', 'b6319fd5-78f4-5e74-8ca0-84db2e246a43', 'USD', 'MASTER', null, null),
  ('7afbf95c-6274-564f-b6df-170f5e590eda', 'MX_DERIVED', '3eed2c9d-11f4-563f-98bb-dd0d23080d49', 'MXN', 'DERIVED', '096f98ae-3ce4-5963-b616-95dd648cff87', 0.70);

insert into pricing_parameter (id, key, value, valid_from, valid_to) values
  ('750f3ead-e2aa-5f4d-9570-450f97e5c6d8', 'usd_mxn_fx', 16.50, '2026-09-29T00:00:00Z', null);

insert into decoration_method (id, key, name, is_active) values
  ('bb517b51-f86c-592d-8106-dddf29b01ad1', 'DTF', 'DTF textil', true),
  ('25b7c3ee-a56e-52dc-b994-13e017096252', 'EMBROIDERY', 'Bordado', true),
  ('c507936e-8b8d-5cde-8735-1fd1eec8540c', 'SCREEN_PRINTING', 'Serigrafía', true),
  ('5eeaf560-62cb-53f7-a2be-ba87f89feb62', 'HTV', 'HTV / vinil textil', true);

insert into publication_profile (id, key, name, inclusion_mode, allowed_statuses, shows_prices, price_book_id, locale) values
  ('21b40028-8f2f-5636-b214-710cfa7c4981', 'crm_internal', 'CRM interno', 'ALL_MATCHING', array['ACTIVE']::catalog_status[], true, null, 'es'),
  ('8ef033f9-a5c7-57da-baa7-8addb251b66d', 'catalog_general', 'Catálogo general (sin precios)', 'EXPLICIT', array['ACTIVE']::catalog_status[], false, null, 'es'),
  ('52f5224c-a0aa-5807-9446-8fa8afebe8c0', 'price_list_usa', 'Lista de precios USA', 'EXPLICIT', array['ACTIVE']::catalog_status[], true, '096f98ae-3ce4-5963-b616-95dd648cff87', 'es'),
  ('c74c837b-3da7-5a39-af42-bf6c7077c598', 'price_list_mx', 'Lista de precios México', 'EXPLICIT', array['ACTIVE']::catalog_status[], true, '7afbf95c-6274-564f-b6df-170f5e590eda', 'es');

insert into decision_record (id, code, title, status, statement, decided_by, decided_at, source) values
  ('b7c8dc20-24f8-531a-928e-8e975184cc8a', 'OD-MX-PRICING', 'Precio México derivado de USA', 'DECIDED', 'MXN = USD × factor México × tipo de cambio maestro. Factor default 0.70 sobrescribible por producto; tipo de cambio provisional 16.5 editable; precio manual MX prevalece. Redondeo e IVA pendientes (P1-02).', 'owner', '2026-09-29T00:00:00Z', 'OWNER_DECISIONS_POST_AUDIT.md');
