-- GENERATED by scripts/generate-seeds.ts — DO NOT EDIT. Source: data/dev-slice/.
-- DEV SLICE — development data, NOT production truth. Real authorized prices; provisional statuses (P1-01).

insert into category (id, key, name, parent_id, sort, is_active) values
  ('31d6b240-362d-5bb7-a1b7-ca51d7c10d8c', 'impresos_papel', 'Impresos en Papel', null, 0, true),
  ('79ad5584-500f-5575-b199-fc9c0e8e3087', 'playeras_textiles', 'Playeras y Textiles', null, 0, true),
  ('854e81c5-5c53-5fad-be89-5f91addc2332', 'gorras_accesorios', 'Gorras y Accesorios', null, 0, true),
  ('68d3189e-e254-5218-bf5d-14a5f000b1cf', 'banderas_displays', 'Banderas y Displays', null, 0, true),
  ('bd44f50d-33d5-5156-9242-742e4115914d', 'servicios_especiales', 'Servicios Especiales', null, 0, true);

insert into catalog_item (id, public_code, kind, canonical_name, status, sale_unit, measurement_spec, decoration_policy, customer_supplied_item, description_internal, merged_into_id) values
  ('9a7f52f4-b893-5808-bfa2-21ccace19965', 'DTG-00001', 'PRODUCT', 'Tarjeta de presentación Tradicional', 'ACTIVE', 'PIECE', null, 'NONE', 'NOT_APPLICABLE', null, null),
  ('ccabd035-6447-550f-b8be-08e8b6d8d0e2', 'DTG-00002', 'PRODUCT', 'Tarjeta de presentación Premium / Gloss', 'ACTIVE', 'PIECE', null, 'NONE', 'NOT_APPLICABLE', null, null),
  ('bdf332e7-d03b-5223-bd25-4006aebb5885', 'DTG-00003', 'PRODUCT', 'Flyers', 'ACTIVE', 'PIECE', null, 'NONE', 'NOT_APPLICABLE', null, null),
  ('3e66e8e4-e365-5ee3-bf9f-30486288969d', 'DTG-00004', 'PRODUCT', 'Imanes para vehículo — par 2 × 1 ft', 'ACTIVE', 'PAIR', null, 'NONE', 'NOT_APPLICABLE', null, null),
  ('9a6c6eef-c05c-5abf-933b-786ee7f3f570', 'DTG-00005', 'PRODUCT', 'Camiseta de algodón cuello redondo', 'ACTIVE', 'PIECE', null, 'OPTIONAL', 'NOT_APPLICABLE', null, null),
  ('21ae272d-619f-537f-b7bf-5bb418fc2dac', 'DTG-00006', 'PRODUCT', 'Camiseta Dry Fit / poliéster', 'ACTIVE', 'PIECE', null, 'OPTIONAL', 'NOT_APPLICABLE', null, null),
  ('2118b3b7-4ef6-555d-8053-41f1742976e8', 'DTG-00007', 'PRODUCT', 'Gorra', 'ACTIVE', 'PIECE', null, 'OPTIONAL', 'NOT_APPLICABLE', null, null),
  ('a698953b-aeb0-566d-bbb3-90ac476952cc', 'DTG-00008', 'PRODUCT', 'X-Banner completo', 'ACTIVE', 'PIECE', null, 'NONE', 'NOT_APPLICABLE', null, null),
  ('a09ec452-c755-538b-8752-25bda134d265', 'DTG-00009', 'PRODUCT', 'Estructura X-Banner', 'ACTIVE', null, null, 'NONE', 'NOT_APPLICABLE', null, null),
  ('dbe194c9-7ed9-51ac-bb56-d7013a89e7a4', 'DTG-00010', 'PRODUCT', 'Gráfica impresa X-Banner', 'ACTIVE', null, null, 'NONE', 'NOT_APPLICABLE', null, null),
  ('1b0c6cb7-d15e-5bf0-854c-4744babe1eb8', 'DTG-00011', 'PRODUCT', 'Yard Sign / Realtor Sign 18 × 24 in', 'ACTIVE', 'PIECE', null, 'NONE', 'NOT_APPLICABLE', null, null),
  ('d3b32238-191c-5c5d-82f3-4701c7ed538a', 'DTG-00012', 'PRODUCT', 'Estaca para yard sign', 'CANDIDATE', null, null, 'NONE', 'NOT_APPLICABLE', null, null),
  ('170e3c75-5a85-5350-be2f-ace4ed45d8c6', 'DTG-00013', 'SERVICE', 'Aplicación DTF sobre artículo del cliente', 'ACTIVE', null, null, 'REQUIRED', 'REQUIRED', null, null),
  ('e5c4d1af-5064-5752-9947-fdf31848ba3c', 'DTG-00014', 'PRODUCT', 'DTF Transfer individual', 'CANDIDATE', null, null, 'NONE', 'NOT_APPLICABLE', null, null),
  ('917f0a15-aba6-514a-a9ef-b1fa57f7f77a', 'DTG-00015', 'PRODUCT', 'DTF Gang Sheet', 'CANDIDATE', null, null, 'NONE', 'NOT_APPLICABLE', null, null),
  ('201c6543-8beb-5c7a-8ac9-0ef4860d971f', 'DTG-00016', 'PRODUCT', 'Invitación para evento', null, null, null, 'NONE', 'NOT_APPLICABLE', null, null);

select setval('catalog_item_public_code_seq', (select max(substring(public_code from 5)::bigint) from catalog_item));

insert into catalog_item_category (item_id, category_id, is_primary) values
  ('9a7f52f4-b893-5808-bfa2-21ccace19965', '31d6b240-362d-5bb7-a1b7-ca51d7c10d8c', true),
  ('ccabd035-6447-550f-b8be-08e8b6d8d0e2', '31d6b240-362d-5bb7-a1b7-ca51d7c10d8c', true),
  ('bdf332e7-d03b-5223-bd25-4006aebb5885', '31d6b240-362d-5bb7-a1b7-ca51d7c10d8c', true),
  ('3e66e8e4-e365-5ee3-bf9f-30486288969d', 'bd44f50d-33d5-5156-9242-742e4115914d', true),
  ('9a6c6eef-c05c-5abf-933b-786ee7f3f570', '79ad5584-500f-5575-b199-fc9c0e8e3087', true),
  ('21ae272d-619f-537f-b7bf-5bb418fc2dac', '79ad5584-500f-5575-b199-fc9c0e8e3087', true),
  ('2118b3b7-4ef6-555d-8053-41f1742976e8', '854e81c5-5c53-5fad-be89-5f91addc2332', true),
  ('a698953b-aeb0-566d-bbb3-90ac476952cc', '68d3189e-e254-5218-bf5d-14a5f000b1cf', true),
  ('a09ec452-c755-538b-8752-25bda134d265', '68d3189e-e254-5218-bf5d-14a5f000b1cf', true),
  ('dbe194c9-7ed9-51ac-bb56-d7013a89e7a4', '68d3189e-e254-5218-bf5d-14a5f000b1cf', true),
  ('201c6543-8beb-5c7a-8ac9-0ef4860d971f', '31d6b240-362d-5bb7-a1b7-ca51d7c10d8c', true);

insert into option_definition (id, key, label, value_kind, unit, scope) values
  ('6b6d28da-50aa-5a02-a72d-f422d1c47385', 'caras', 'Caras impresas', 'ENUM', null, 'ITEM'),
  ('2d8c16d7-306f-5933-9df7-9e4c3f4a93fd', 'papel', 'Papel', 'ENUM', null, 'ITEM'),
  ('88ef6bb6-953b-561d-99e5-06b448a5ef5e', 'tamano_papel', 'Tamaño de papel', 'ENUM', null, 'ITEM'),
  ('a97d9ec8-975a-5050-9395-32390402b7d4', 'talla', 'Talla', 'ENUM', null, 'ITEM'),
  ('085fadf7-51a5-5c80-8027-b997873654f1', 'color', 'Color', 'TEXT', null, 'ITEM'),
  ('bec272ff-d51d-5ab2-86e8-73e50b6ce3f5', 'estructura', 'Estructura', 'ENUM', null, 'ITEM'),
  ('497f4972-c1f1-59eb-aaca-79d7ce319bbe', 'ajuste', 'Ajuste', 'ENUM', null, 'ITEM'),
  ('1d498ead-c31b-507e-a523-1723fca91e25', 'paneles', 'Paneles', 'ENUM', null, 'ITEM'),
  ('94849786-183d-5751-a72a-a255fb471ca2', 'tamano_display', 'Tamaño del display', 'DIMENSIONS', 'in', 'ITEM');

insert into option_value (id, option_definition_id, code, label, spec, sort, is_active) values
  ('6c8d9fe8-1684-581b-a6cd-b6f491921d93', '6b6d28da-50aa-5a02-a72d-f422d1c47385', '1', '1 cara', null, 1, true),
  ('4ba304fa-8abc-549d-bdf6-2e4918c37cf0', '6b6d28da-50aa-5a02-a72d-f422d1c47385', '2', '2 caras', null, 2, true),
  ('5ee055a6-597a-5b1a-b234-d7af8706062b', '2d8c16d7-306f-5933-9df7-9e4c3f4a93fd', 'Bond', 'Bond', null, 1, true),
  ('7f23e854-f1dd-5037-a4dc-51c45a67239f', '2d8c16d7-306f-5933-9df7-9e4c3f4a93fd', 'Premium', 'Premium', null, 2, true),
  ('a870c3e7-836e-56f6-b2d9-ca01693a6adb', '88ef6bb6-953b-561d-99e5-06b448a5ef5e', 'Carta', 'Carta', null, 1, true),
  ('e0fca6f5-5c68-5228-ba67-285240d73123', '88ef6bb6-953b-561d-99e5-06b448a5ef5e', 'Media carta', 'Media carta', null, 2, true),
  ('962e83a5-285a-51ed-aa16-c6f503a08717', '88ef6bb6-953b-561d-99e5-06b448a5ef5e', '1/4 carta', '1/4 carta', null, 3, true),
  ('9309307f-815b-5a77-b59d-433b5a2557e8', 'a97d9ec8-975a-5050-9395-32390402b7d4', 'S', 'S', null, 1, true),
  ('e74ed564-a299-53a5-8fdd-00fc9d30c9f1', 'a97d9ec8-975a-5050-9395-32390402b7d4', 'M', 'M', null, 2, true),
  ('c3079b76-784d-585b-b2fc-fb03c7796cbf', 'a97d9ec8-975a-5050-9395-32390402b7d4', 'L', 'L', null, 3, true),
  ('6abd7f04-24f0-52fc-8494-fe2686b8060a', 'a97d9ec8-975a-5050-9395-32390402b7d4', 'XL', 'XL', null, 4, true),
  ('5ca8e6b4-f0ff-51a3-b0ae-b9f01e69bbef', 'a97d9ec8-975a-5050-9395-32390402b7d4', '2XL', '2XL', null, 5, true),
  ('264942b4-192e-51b3-ac8d-627a27aba558', 'a97d9ec8-975a-5050-9395-32390402b7d4', '3XL', '3XL', null, 6, true),
  ('0a8652a4-6468-5b5c-b641-f28158ea8ce0', 'bec272ff-d51d-5ab2-86e8-73e50b6ce3f5', 'Structured', 'Structured', null, 1, true),
  ('d65c5ca9-8412-50f6-b6a2-43acbad91159', 'bec272ff-d51d-5ab2-86e8-73e50b6ce3f5', 'Unstructured', 'Unstructured', null, 2, true),
  ('56be1fb4-249f-5065-979c-83e0840516c7', '497f4972-c1f1-59eb-aaca-79d7ce319bbe', 'Fitted', 'Fitted', null, 1, true),
  ('74a26ddc-06a1-59d1-849b-99c10f0aed88', '497f4972-c1f1-59eb-aaca-79d7ce319bbe', 'Adjustable', 'Adjustable', null, 2, true),
  ('b05f868b-4391-50e2-88d0-32e1ae8b6472', '1d498ead-c31b-507e-a523-1723fca91e25', '5-panel', '5-panel', null, 1, true),
  ('c8443953-c3bb-5d87-9a28-3d7fe2dec4e4', '1d498ead-c31b-507e-a523-1723fca91e25', '6-panel', '6-panel', null, 2, true),
  ('ab8b31ed-e26c-5cb6-a605-f44156f14038', '94849786-183d-5751-a72a-a255fb471ca2', '24x63', '24 × 63 in', '{"w":24,"h":63}'::jsonb, 1, true),
  ('910f27d7-9caa-5700-a2bb-bc647f5ab6ee', '94849786-183d-5751-a72a-a255fb471ca2', '32x72', '32 × 72 in', '{"w":32,"h":72}'::jsonb, 2, true),
  ('bac11c23-bd51-544e-a7d1-94be1e6f5547', '94849786-183d-5751-a72a-a255fb471ca2', '48x78', '48 × 78 in', '{"w":48,"h":78}'::jsonb, 3, true);

insert into item_option (item_id, option_definition_id, is_required, selection_mode, is_distributable, sort, default_value_id) values
  ('9a7f52f4-b893-5808-bfa2-21ccace19965', '6b6d28da-50aa-5a02-a72d-f422d1c47385', true, 'SINGLE', false, 1, null),
  ('ccabd035-6447-550f-b8be-08e8b6d8d0e2', '6b6d28da-50aa-5a02-a72d-f422d1c47385', true, 'SINGLE', false, 2, null),
  ('bdf332e7-d03b-5223-bd25-4006aebb5885', '2d8c16d7-306f-5933-9df7-9e4c3f4a93fd', true, 'SINGLE', false, 3, null),
  ('bdf332e7-d03b-5223-bd25-4006aebb5885', '88ef6bb6-953b-561d-99e5-06b448a5ef5e', true, 'SINGLE', false, 4, null),
  ('bdf332e7-d03b-5223-bd25-4006aebb5885', '6b6d28da-50aa-5a02-a72d-f422d1c47385', true, 'SINGLE', false, 5, null),
  ('9a6c6eef-c05c-5abf-933b-786ee7f3f570', 'a97d9ec8-975a-5050-9395-32390402b7d4', true, 'SINGLE', true, 6, null),
  ('9a6c6eef-c05c-5abf-933b-786ee7f3f570', '085fadf7-51a5-5c80-8027-b997873654f1', false, 'SINGLE', false, 7, null),
  ('21ae272d-619f-537f-b7bf-5bb418fc2dac', 'a97d9ec8-975a-5050-9395-32390402b7d4', true, 'SINGLE', true, 8, null),
  ('21ae272d-619f-537f-b7bf-5bb418fc2dac', '085fadf7-51a5-5c80-8027-b997873654f1', false, 'SINGLE', false, 9, null),
  ('2118b3b7-4ef6-555d-8053-41f1742976e8', 'bec272ff-d51d-5ab2-86e8-73e50b6ce3f5', false, 'SINGLE', false, 10, null),
  ('2118b3b7-4ef6-555d-8053-41f1742976e8', '497f4972-c1f1-59eb-aaca-79d7ce319bbe', false, 'SINGLE', false, 11, null),
  ('2118b3b7-4ef6-555d-8053-41f1742976e8', '1d498ead-c31b-507e-a523-1723fca91e25', false, 'SINGLE', false, 12, null),
  ('a698953b-aeb0-566d-bbb3-90ac476952cc', '94849786-183d-5751-a72a-a255fb471ca2', true, 'SINGLE', false, 13, null);

insert into item_option_value (item_id, option_definition_id, option_value_id, sort, is_active) values
  ('9a7f52f4-b893-5808-bfa2-21ccace19965', '6b6d28da-50aa-5a02-a72d-f422d1c47385', '6c8d9fe8-1684-581b-a6cd-b6f491921d93', 1, true),
  ('9a7f52f4-b893-5808-bfa2-21ccace19965', '6b6d28da-50aa-5a02-a72d-f422d1c47385', '4ba304fa-8abc-549d-bdf6-2e4918c37cf0', 2, true),
  ('ccabd035-6447-550f-b8be-08e8b6d8d0e2', '6b6d28da-50aa-5a02-a72d-f422d1c47385', '6c8d9fe8-1684-581b-a6cd-b6f491921d93', 1, true),
  ('ccabd035-6447-550f-b8be-08e8b6d8d0e2', '6b6d28da-50aa-5a02-a72d-f422d1c47385', '4ba304fa-8abc-549d-bdf6-2e4918c37cf0', 2, true),
  ('bdf332e7-d03b-5223-bd25-4006aebb5885', '2d8c16d7-306f-5933-9df7-9e4c3f4a93fd', '5ee055a6-597a-5b1a-b234-d7af8706062b', 1, true),
  ('bdf332e7-d03b-5223-bd25-4006aebb5885', '2d8c16d7-306f-5933-9df7-9e4c3f4a93fd', '7f23e854-f1dd-5037-a4dc-51c45a67239f', 2, true),
  ('bdf332e7-d03b-5223-bd25-4006aebb5885', '88ef6bb6-953b-561d-99e5-06b448a5ef5e', 'a870c3e7-836e-56f6-b2d9-ca01693a6adb', 1, true),
  ('bdf332e7-d03b-5223-bd25-4006aebb5885', '88ef6bb6-953b-561d-99e5-06b448a5ef5e', 'e0fca6f5-5c68-5228-ba67-285240d73123', 2, true),
  ('bdf332e7-d03b-5223-bd25-4006aebb5885', '88ef6bb6-953b-561d-99e5-06b448a5ef5e', '962e83a5-285a-51ed-aa16-c6f503a08717', 3, true),
  ('bdf332e7-d03b-5223-bd25-4006aebb5885', '6b6d28da-50aa-5a02-a72d-f422d1c47385', '6c8d9fe8-1684-581b-a6cd-b6f491921d93', 1, true),
  ('bdf332e7-d03b-5223-bd25-4006aebb5885', '6b6d28da-50aa-5a02-a72d-f422d1c47385', '4ba304fa-8abc-549d-bdf6-2e4918c37cf0', 2, true),
  ('9a6c6eef-c05c-5abf-933b-786ee7f3f570', 'a97d9ec8-975a-5050-9395-32390402b7d4', '9309307f-815b-5a77-b59d-433b5a2557e8', 1, true),
  ('9a6c6eef-c05c-5abf-933b-786ee7f3f570', 'a97d9ec8-975a-5050-9395-32390402b7d4', 'e74ed564-a299-53a5-8fdd-00fc9d30c9f1', 2, true),
  ('9a6c6eef-c05c-5abf-933b-786ee7f3f570', 'a97d9ec8-975a-5050-9395-32390402b7d4', 'c3079b76-784d-585b-b2fc-fb03c7796cbf', 3, true),
  ('9a6c6eef-c05c-5abf-933b-786ee7f3f570', 'a97d9ec8-975a-5050-9395-32390402b7d4', '6abd7f04-24f0-52fc-8494-fe2686b8060a', 4, true),
  ('9a6c6eef-c05c-5abf-933b-786ee7f3f570', 'a97d9ec8-975a-5050-9395-32390402b7d4', '5ca8e6b4-f0ff-51a3-b0ae-b9f01e69bbef', 5, true),
  ('9a6c6eef-c05c-5abf-933b-786ee7f3f570', 'a97d9ec8-975a-5050-9395-32390402b7d4', '264942b4-192e-51b3-ac8d-627a27aba558', 6, true),
  ('21ae272d-619f-537f-b7bf-5bb418fc2dac', 'a97d9ec8-975a-5050-9395-32390402b7d4', '9309307f-815b-5a77-b59d-433b5a2557e8', 1, true),
  ('21ae272d-619f-537f-b7bf-5bb418fc2dac', 'a97d9ec8-975a-5050-9395-32390402b7d4', 'e74ed564-a299-53a5-8fdd-00fc9d30c9f1', 2, true),
  ('21ae272d-619f-537f-b7bf-5bb418fc2dac', 'a97d9ec8-975a-5050-9395-32390402b7d4', 'c3079b76-784d-585b-b2fc-fb03c7796cbf', 3, true),
  ('21ae272d-619f-537f-b7bf-5bb418fc2dac', 'a97d9ec8-975a-5050-9395-32390402b7d4', '6abd7f04-24f0-52fc-8494-fe2686b8060a', 4, true),
  ('21ae272d-619f-537f-b7bf-5bb418fc2dac', 'a97d9ec8-975a-5050-9395-32390402b7d4', '5ca8e6b4-f0ff-51a3-b0ae-b9f01e69bbef', 5, true),
  ('21ae272d-619f-537f-b7bf-5bb418fc2dac', 'a97d9ec8-975a-5050-9395-32390402b7d4', '264942b4-192e-51b3-ac8d-627a27aba558', 6, true),
  ('2118b3b7-4ef6-555d-8053-41f1742976e8', 'bec272ff-d51d-5ab2-86e8-73e50b6ce3f5', '0a8652a4-6468-5b5c-b641-f28158ea8ce0', 1, true),
  ('2118b3b7-4ef6-555d-8053-41f1742976e8', 'bec272ff-d51d-5ab2-86e8-73e50b6ce3f5', 'd65c5ca9-8412-50f6-b6a2-43acbad91159', 2, true),
  ('2118b3b7-4ef6-555d-8053-41f1742976e8', '497f4972-c1f1-59eb-aaca-79d7ce319bbe', '56be1fb4-249f-5065-979c-83e0840516c7', 1, true),
  ('2118b3b7-4ef6-555d-8053-41f1742976e8', '497f4972-c1f1-59eb-aaca-79d7ce319bbe', '74a26ddc-06a1-59d1-849b-99c10f0aed88', 2, true),
  ('2118b3b7-4ef6-555d-8053-41f1742976e8', '1d498ead-c31b-507e-a523-1723fca91e25', 'b05f868b-4391-50e2-88d0-32e1ae8b6472', 1, true),
  ('2118b3b7-4ef6-555d-8053-41f1742976e8', '1d498ead-c31b-507e-a523-1723fca91e25', 'c8443953-c3bb-5d87-9a28-3d7fe2dec4e4', 2, true),
  ('a698953b-aeb0-566d-bbb3-90ac476952cc', '94849786-183d-5751-a72a-a255fb471ca2', 'ab8b31ed-e26c-5cb6-a605-f44156f14038', 1, true),
  ('a698953b-aeb0-566d-bbb3-90ac476952cc', '94849786-183d-5751-a72a-a255fb471ca2', '910f27d7-9caa-5700-a2bb-bc647f5ab6ee', 2, true),
  ('a698953b-aeb0-566d-bbb3-90ac476952cc', '94849786-183d-5751-a72a-a255fb471ca2', 'bac11c23-bd51-544e-a7d1-94be1e6f5547', 3, true);

insert into decoration_capability (item_id, method_id, constraints, note) values
  ('9a6c6eef-c05c-5abf-933b-786ee7f3f570', 'bb517b51-f86c-592d-8106-dddf29b01ad1', null, null),
  ('9a6c6eef-c05c-5abf-933b-786ee7f3f570', '25b7c3ee-a56e-52dc-b994-13e017096252', null, null),
  ('9a6c6eef-c05c-5abf-933b-786ee7f3f570', 'c507936e-8b8d-5cde-8735-1fd1eec8540c', null, null),
  ('9a6c6eef-c05c-5abf-933b-786ee7f3f570', '5eeaf560-62cb-53f7-a2be-ba87f89feb62', null, null),
  ('21ae272d-619f-537f-b7bf-5bb418fc2dac', 'bb517b51-f86c-592d-8106-dddf29b01ad1', null, null),
  ('21ae272d-619f-537f-b7bf-5bb418fc2dac', '25b7c3ee-a56e-52dc-b994-13e017096252', null, null),
  ('21ae272d-619f-537f-b7bf-5bb418fc2dac', 'c507936e-8b8d-5cde-8735-1fd1eec8540c', null, null),
  ('21ae272d-619f-537f-b7bf-5bb418fc2dac', '5eeaf560-62cb-53f7-a2be-ba87f89feb62', null, null),
  ('2118b3b7-4ef6-555d-8053-41f1742976e8', 'bb517b51-f86c-592d-8106-dddf29b01ad1', null, null),
  ('2118b3b7-4ef6-555d-8053-41f1742976e8', '25b7c3ee-a56e-52dc-b994-13e017096252', null, null),
  ('2118b3b7-4ef6-555d-8053-41f1742976e8', 'c507936e-8b8d-5cde-8735-1fd1eec8540c', null, null),
  ('2118b3b7-4ef6-555d-8053-41f1742976e8', '5eeaf560-62cb-53f7-a2be-ba87f89feb62', null, null),
  ('170e3c75-5a85-5350-be2f-ace4ed45d8c6', 'bb517b51-f86c-592d-8106-dddf29b01ad1', null, null);

insert into composition_line (id, parent_item_id, child_item_id, quantity, role, sort, note) values
  ('a38d7108-639a-5880-87d1-3a219329eed4', 'a698953b-aeb0-566d-bbb3-90ac476952cc', 'a09ec452-c755-538b-8752-25bda134d265', 1, 'INCLUDED', 1, null),
  ('a7c60a7e-9aa2-521f-9a07-ab1f2d22f2fe', 'a698953b-aeb0-566d-bbb3-90ac476952cc', 'dbe194c9-7ed9-51ac-bb56-d7013a89e7a4', 1, 'INCLUDED', 2, null),
  ('3059cc97-d3df-5b8c-9d4b-ae1acae13de4', '1b0c6cb7-d15e-5bf0-854c-4744babe1eb8', 'd3b32238-191c-5c5d-82f3-4701c7ed538a', 1, 'OPTIONAL', 1, null);

insert into price_definition (id, item_id, price_book_id, component, model, amount, rate, rate_unit, min_charge, min_quantity, max_quantity, status, valid_from, valid_to, version, supersedes_id, authorized_by, authorized_at) values
  ('9a87e43c-ab7e-51e6-89e9-893e1bd25dd1', '9a7f52f4-b893-5808-bfa2-21ccace19965', '096f98ae-3ce4-5963-b616-95dd648cff87', 'ITEM', 'EXACT_QUANTITY_MATRIX', null, null, null, null, null, null, 'DRAFT', '2026-09-15T00:00:00Z', null, 1, null, null, null);

insert into price_break (price_definition_id, quantity, amount, amount_basis) values
  ('9a87e43c-ab7e-51e6-89e9-893e1bd25dd1', 100, 25.00, 'TOTAL'),
  ('9a87e43c-ab7e-51e6-89e9-893e1bd25dd1', 250, 35.00, 'TOTAL'),
  ('9a87e43c-ab7e-51e6-89e9-893e1bd25dd1', 500, 55.00, 'TOTAL'),
  ('9a87e43c-ab7e-51e6-89e9-893e1bd25dd1', 1000, 90.00, 'TOTAL'),
  ('9a87e43c-ab7e-51e6-89e9-893e1bd25dd1', 1500, 120.00, 'TOTAL'),
  ('9a87e43c-ab7e-51e6-89e9-893e1bd25dd1', 2000, 150.00, 'TOTAL'),
  ('9a87e43c-ab7e-51e6-89e9-893e1bd25dd1', 2500, 180.00, 'TOTAL'),
  ('9a87e43c-ab7e-51e6-89e9-893e1bd25dd1', 3000, 210.00, 'TOTAL'),
  ('9a87e43c-ab7e-51e6-89e9-893e1bd25dd1', 4000, 270.00, 'TOTAL'),
  ('9a87e43c-ab7e-51e6-89e9-893e1bd25dd1', 5000, 330.00, 'TOTAL');

insert into price_condition (id, price_definition_id, price_rule_id, kind, option_definition_id, option_value_id, decoration_method_id) values
  ('62dbf6b6-b548-5a41-902b-99a0ab0e62b2', '9a87e43c-ab7e-51e6-89e9-893e1bd25dd1', null, 'OPTION_VALUE', '6b6d28da-50aa-5a02-a72d-f422d1c47385', '6c8d9fe8-1684-581b-a6cd-b6f491921d93', null);

update price_definition set status = 'AUTHORIZED', authorized_by = 'owner — entrevista 2026-09-15', authorized_at = '2026-09-15T00:00:00Z' where id = '9a87e43c-ab7e-51e6-89e9-893e1bd25dd1';

insert into price_definition (id, item_id, price_book_id, component, model, amount, rate, rate_unit, min_charge, min_quantity, max_quantity, status, valid_from, valid_to, version, supersedes_id, authorized_by, authorized_at) values
  ('03a51d6b-d081-5e34-9440-1acecbaa56fa', '9a7f52f4-b893-5808-bfa2-21ccace19965', '096f98ae-3ce4-5963-b616-95dd648cff87', 'ITEM', 'EXACT_QUANTITY_MATRIX', null, null, null, null, null, null, 'DRAFT', '2026-09-15T00:00:00Z', null, 1, null, null, null);

insert into price_break (price_definition_id, quantity, amount, amount_basis) values
  ('03a51d6b-d081-5e34-9440-1acecbaa56fa', 100, 35.00, 'TOTAL'),
  ('03a51d6b-d081-5e34-9440-1acecbaa56fa', 250, 50.00, 'TOTAL'),
  ('03a51d6b-d081-5e34-9440-1acecbaa56fa', 500, 80.00, 'TOTAL'),
  ('03a51d6b-d081-5e34-9440-1acecbaa56fa', 1000, 130.00, 'TOTAL'),
  ('03a51d6b-d081-5e34-9440-1acecbaa56fa', 1500, 175.00, 'TOTAL'),
  ('03a51d6b-d081-5e34-9440-1acecbaa56fa', 2000, 220.00, 'TOTAL'),
  ('03a51d6b-d081-5e34-9440-1acecbaa56fa', 2500, 265.00, 'TOTAL'),
  ('03a51d6b-d081-5e34-9440-1acecbaa56fa', 3000, 310.00, 'TOTAL'),
  ('03a51d6b-d081-5e34-9440-1acecbaa56fa', 4000, 400.00, 'TOTAL'),
  ('03a51d6b-d081-5e34-9440-1acecbaa56fa', 5000, 490.00, 'TOTAL');

insert into price_condition (id, price_definition_id, price_rule_id, kind, option_definition_id, option_value_id, decoration_method_id) values
  ('d45071da-08a5-5859-8096-d16a262a9b9e', '03a51d6b-d081-5e34-9440-1acecbaa56fa', null, 'OPTION_VALUE', '6b6d28da-50aa-5a02-a72d-f422d1c47385', '4ba304fa-8abc-549d-bdf6-2e4918c37cf0', null);

update price_definition set status = 'AUTHORIZED', authorized_by = 'owner — entrevista 2026-09-15', authorized_at = '2026-09-15T00:00:00Z' where id = '03a51d6b-d081-5e34-9440-1acecbaa56fa';

insert into price_definition (id, item_id, price_book_id, component, model, amount, rate, rate_unit, min_charge, min_quantity, max_quantity, status, valid_from, valid_to, version, supersedes_id, authorized_by, authorized_at) values
  ('dcc95a7b-3754-5c46-a9bd-77e50f6c5023', 'ccabd035-6447-550f-b8be-08e8b6d8d0e2', '096f98ae-3ce4-5963-b616-95dd648cff87', 'ITEM', 'EXACT_QUANTITY_MATRIX', null, null, null, null, null, null, 'DRAFT', '2026-09-15T00:00:00Z', null, 1, null, null, null);

insert into price_break (price_definition_id, quantity, amount, amount_basis) values
  ('dcc95a7b-3754-5c46-a9bd-77e50f6c5023', 100, 35.00, 'TOTAL'),
  ('dcc95a7b-3754-5c46-a9bd-77e50f6c5023', 250, 55.00, 'TOTAL'),
  ('dcc95a7b-3754-5c46-a9bd-77e50f6c5023', 500, 85.00, 'TOTAL'),
  ('dcc95a7b-3754-5c46-a9bd-77e50f6c5023', 1000, 140.00, 'TOTAL'),
  ('dcc95a7b-3754-5c46-a9bd-77e50f6c5023', 1500, 185.00, 'TOTAL'),
  ('dcc95a7b-3754-5c46-a9bd-77e50f6c5023', 2000, 230.00, 'TOTAL'),
  ('dcc95a7b-3754-5c46-a9bd-77e50f6c5023', 2500, 275.00, 'TOTAL'),
  ('dcc95a7b-3754-5c46-a9bd-77e50f6c5023', 3000, 320.00, 'TOTAL'),
  ('dcc95a7b-3754-5c46-a9bd-77e50f6c5023', 4000, 410.00, 'TOTAL'),
  ('dcc95a7b-3754-5c46-a9bd-77e50f6c5023', 5000, 500.00, 'TOTAL');

insert into price_condition (id, price_definition_id, price_rule_id, kind, option_definition_id, option_value_id, decoration_method_id) values
  ('b8c2124a-4a76-5946-9e4b-fd0f0ede446e', 'dcc95a7b-3754-5c46-a9bd-77e50f6c5023', null, 'OPTION_VALUE', '6b6d28da-50aa-5a02-a72d-f422d1c47385', '6c8d9fe8-1684-581b-a6cd-b6f491921d93', null);

update price_definition set status = 'AUTHORIZED', authorized_by = 'owner — entrevista 2026-09-15', authorized_at = '2026-09-15T00:00:00Z' where id = 'dcc95a7b-3754-5c46-a9bd-77e50f6c5023';

insert into price_definition (id, item_id, price_book_id, component, model, amount, rate, rate_unit, min_charge, min_quantity, max_quantity, status, valid_from, valid_to, version, supersedes_id, authorized_by, authorized_at) values
  ('6b58997b-77a5-5651-bf42-a8016a0ab078', 'ccabd035-6447-550f-b8be-08e8b6d8d0e2', '096f98ae-3ce4-5963-b616-95dd648cff87', 'ITEM', 'EXACT_QUANTITY_MATRIX', null, null, null, null, null, null, 'DRAFT', '2026-09-15T00:00:00Z', null, 1, null, null, null);

insert into price_break (price_definition_id, quantity, amount, amount_basis) values
  ('6b58997b-77a5-5651-bf42-a8016a0ab078', 100, 50.00, 'TOTAL'),
  ('6b58997b-77a5-5651-bf42-a8016a0ab078', 250, 80.00, 'TOTAL'),
  ('6b58997b-77a5-5651-bf42-a8016a0ab078', 500, 120.00, 'TOTAL'),
  ('6b58997b-77a5-5651-bf42-a8016a0ab078', 1000, 195.00, 'TOTAL'),
  ('6b58997b-77a5-5651-bf42-a8016a0ab078', 1500, 255.00, 'TOTAL'),
  ('6b58997b-77a5-5651-bf42-a8016a0ab078', 2000, 315.00, 'TOTAL'),
  ('6b58997b-77a5-5651-bf42-a8016a0ab078', 2500, 375.00, 'TOTAL'),
  ('6b58997b-77a5-5651-bf42-a8016a0ab078', 3000, 435.00, 'TOTAL'),
  ('6b58997b-77a5-5651-bf42-a8016a0ab078', 4000, 555.00, 'TOTAL'),
  ('6b58997b-77a5-5651-bf42-a8016a0ab078', 5000, 675.00, 'TOTAL');

insert into price_condition (id, price_definition_id, price_rule_id, kind, option_definition_id, option_value_id, decoration_method_id) values
  ('7db5308d-5e8c-5644-ac49-7549acec1737', '6b58997b-77a5-5651-bf42-a8016a0ab078', null, 'OPTION_VALUE', '6b6d28da-50aa-5a02-a72d-f422d1c47385', '4ba304fa-8abc-549d-bdf6-2e4918c37cf0', null);

update price_definition set status = 'AUTHORIZED', authorized_by = 'owner — entrevista 2026-09-15', authorized_at = '2026-09-15T00:00:00Z' where id = '6b58997b-77a5-5651-bf42-a8016a0ab078';

insert into price_definition (id, item_id, price_book_id, component, model, amount, rate, rate_unit, min_charge, min_quantity, max_quantity, status, valid_from, valid_to, version, supersedes_id, authorized_by, authorized_at) values
  ('81d31998-26d4-52ef-988e-14d650a7734f', '3e66e8e4-e365-5ee3-bf9f-30486288969d', '096f98ae-3ce4-5963-b616-95dd648cff87', 'ITEM', 'FIXED', 65.00, null, null, null, null, 1, 'DRAFT', '2026-09-15T00:00:00Z', null, 1, null, null, null);

update price_definition set status = 'AUTHORIZED', authorized_by = 'owner — entrevista 2026-09-15', authorized_at = '2026-09-15T00:00:00Z' where id = '81d31998-26d4-52ef-988e-14d650a7734f';

insert into price_definition (id, item_id, price_book_id, component, model, amount, rate, rate_unit, min_charge, min_quantity, max_quantity, status, valid_from, valid_to, version, supersedes_id, authorized_by, authorized_at) values
  ('4c7d3f82-9ffe-56ca-83db-96f373801d5b', 'bdf332e7-d03b-5223-bd25-4006aebb5885', '096f98ae-3ce4-5963-b616-95dd648cff87', 'ITEM', 'EXACT_QUANTITY_MATRIX', null, null, null, null, null, null, 'DRAFT', '2026-09-15T00:00:00Z', null, 1, null, null, null);

insert into price_break (price_definition_id, quantity, amount, amount_basis) values
  ('4c7d3f82-9ffe-56ca-83db-96f373801d5b', 100, 40.00, 'TOTAL'),
  ('4c7d3f82-9ffe-56ca-83db-96f373801d5b', 250, 70.00, 'TOTAL'),
  ('4c7d3f82-9ffe-56ca-83db-96f373801d5b', 500, 110.00, 'TOTAL'),
  ('4c7d3f82-9ffe-56ca-83db-96f373801d5b', 1000, 180.00, 'TOTAL'),
  ('4c7d3f82-9ffe-56ca-83db-96f373801d5b', 1500, 250.00, 'TOTAL'),
  ('4c7d3f82-9ffe-56ca-83db-96f373801d5b', 2000, 320.00, 'TOTAL'),
  ('4c7d3f82-9ffe-56ca-83db-96f373801d5b', 2500, 390.00, 'TOTAL'),
  ('4c7d3f82-9ffe-56ca-83db-96f373801d5b', 3000, 460.00, 'TOTAL'),
  ('4c7d3f82-9ffe-56ca-83db-96f373801d5b', 4000, 600.00, 'TOTAL'),
  ('4c7d3f82-9ffe-56ca-83db-96f373801d5b', 5000, 740.00, 'TOTAL');

insert into price_condition (id, price_definition_id, price_rule_id, kind, option_definition_id, option_value_id, decoration_method_id) values
  ('b91ecb3e-0969-5b73-b94a-f224b1dbc397', '4c7d3f82-9ffe-56ca-83db-96f373801d5b', null, 'OPTION_VALUE', '6b6d28da-50aa-5a02-a72d-f422d1c47385', '6c8d9fe8-1684-581b-a6cd-b6f491921d93', null),
  ('16a86db4-9d4d-51c1-a4ea-fe69132e70b2', '4c7d3f82-9ffe-56ca-83db-96f373801d5b', null, 'OPTION_VALUE', '2d8c16d7-306f-5933-9df7-9e4c3f4a93fd', '5ee055a6-597a-5b1a-b234-d7af8706062b', null),
  ('4dcdda2e-c6df-5508-a911-b63945a37101', '4c7d3f82-9ffe-56ca-83db-96f373801d5b', null, 'OPTION_VALUE', '88ef6bb6-953b-561d-99e5-06b448a5ef5e', 'a870c3e7-836e-56f6-b2d9-ca01693a6adb', null);

update price_definition set status = 'AUTHORIZED', authorized_by = 'owner — entrevista 2026-09-15', authorized_at = '2026-09-15T00:00:00Z' where id = '4c7d3f82-9ffe-56ca-83db-96f373801d5b';

insert into price_definition (id, item_id, price_book_id, component, model, amount, rate, rate_unit, min_charge, min_quantity, max_quantity, status, valid_from, valid_to, version, supersedes_id, authorized_by, authorized_at) values
  ('75322a4c-325f-5d0f-ae1f-dee9fcf869b5', 'bdf332e7-d03b-5223-bd25-4006aebb5885', '096f98ae-3ce4-5963-b616-95dd648cff87', 'ITEM', 'EXACT_QUANTITY_MATRIX', null, null, null, null, null, null, 'DRAFT', '2026-09-15T00:00:00Z', null, 1, null, null, null);

insert into price_break (price_definition_id, quantity, amount, amount_basis) values
  ('75322a4c-325f-5d0f-ae1f-dee9fcf869b5', 100, 30.00, 'TOTAL'),
  ('75322a4c-325f-5d0f-ae1f-dee9fcf869b5', 250, 45.00, 'TOTAL'),
  ('75322a4c-325f-5d0f-ae1f-dee9fcf869b5', 500, 70.00, 'TOTAL'),
  ('75322a4c-325f-5d0f-ae1f-dee9fcf869b5', 1000, 115.00, 'TOTAL'),
  ('75322a4c-325f-5d0f-ae1f-dee9fcf869b5', 1500, 155.00, 'TOTAL'),
  ('75322a4c-325f-5d0f-ae1f-dee9fcf869b5', 2000, 195.00, 'TOTAL'),
  ('75322a4c-325f-5d0f-ae1f-dee9fcf869b5', 2500, 235.00, 'TOTAL'),
  ('75322a4c-325f-5d0f-ae1f-dee9fcf869b5', 3000, 275.00, 'TOTAL'),
  ('75322a4c-325f-5d0f-ae1f-dee9fcf869b5', 4000, 350.00, 'TOTAL'),
  ('75322a4c-325f-5d0f-ae1f-dee9fcf869b5', 5000, 425.00, 'TOTAL');

insert into price_condition (id, price_definition_id, price_rule_id, kind, option_definition_id, option_value_id, decoration_method_id) values
  ('eb4bfb8d-ae6c-5993-a6fc-548396cd3a22', '75322a4c-325f-5d0f-ae1f-dee9fcf869b5', null, 'OPTION_VALUE', '6b6d28da-50aa-5a02-a72d-f422d1c47385', '6c8d9fe8-1684-581b-a6cd-b6f491921d93', null),
  ('4055be83-6284-5836-9374-61b73e964d7e', '75322a4c-325f-5d0f-ae1f-dee9fcf869b5', null, 'OPTION_VALUE', '2d8c16d7-306f-5933-9df7-9e4c3f4a93fd', '5ee055a6-597a-5b1a-b234-d7af8706062b', null),
  ('e1c1fd83-c011-516e-98f0-f6a3bf0d48e0', '75322a4c-325f-5d0f-ae1f-dee9fcf869b5', null, 'OPTION_VALUE', '88ef6bb6-953b-561d-99e5-06b448a5ef5e', 'e0fca6f5-5c68-5228-ba67-285240d73123', null);

update price_definition set status = 'AUTHORIZED', authorized_by = 'owner — entrevista 2026-09-15', authorized_at = '2026-09-15T00:00:00Z' where id = '75322a4c-325f-5d0f-ae1f-dee9fcf869b5';

insert into price_definition (id, item_id, price_book_id, component, model, amount, rate, rate_unit, min_charge, min_quantity, max_quantity, status, valid_from, valid_to, version, supersedes_id, authorized_by, authorized_at) values
  ('30ee894b-0ca0-5bdb-9acc-8212a7e64871', 'bdf332e7-d03b-5223-bd25-4006aebb5885', '096f98ae-3ce4-5963-b616-95dd648cff87', 'ITEM', 'EXACT_QUANTITY_MATRIX', null, null, null, null, null, null, 'DRAFT', '2026-09-15T00:00:00Z', null, 1, null, null, null);

insert into price_break (price_definition_id, quantity, amount, amount_basis) values
  ('30ee894b-0ca0-5bdb-9acc-8212a7e64871', 100, 25.00, 'TOTAL'),
  ('30ee894b-0ca0-5bdb-9acc-8212a7e64871', 250, 35.00, 'TOTAL'),
  ('30ee894b-0ca0-5bdb-9acc-8212a7e64871', 500, 50.00, 'TOTAL'),
  ('30ee894b-0ca0-5bdb-9acc-8212a7e64871', 1000, 80.00, 'TOTAL'),
  ('30ee894b-0ca0-5bdb-9acc-8212a7e64871', 1500, 105.00, 'TOTAL'),
  ('30ee894b-0ca0-5bdb-9acc-8212a7e64871', 2000, 130.00, 'TOTAL'),
  ('30ee894b-0ca0-5bdb-9acc-8212a7e64871', 2500, 155.00, 'TOTAL'),
  ('30ee894b-0ca0-5bdb-9acc-8212a7e64871', 3000, 180.00, 'TOTAL'),
  ('30ee894b-0ca0-5bdb-9acc-8212a7e64871', 4000, 230.00, 'TOTAL'),
  ('30ee894b-0ca0-5bdb-9acc-8212a7e64871', 5000, 280.00, 'TOTAL');

insert into price_condition (id, price_definition_id, price_rule_id, kind, option_definition_id, option_value_id, decoration_method_id) values
  ('2f834342-4cab-586a-906d-53d99da9599c', '30ee894b-0ca0-5bdb-9acc-8212a7e64871', null, 'OPTION_VALUE', '6b6d28da-50aa-5a02-a72d-f422d1c47385', '6c8d9fe8-1684-581b-a6cd-b6f491921d93', null),
  ('3690b0fe-533c-5815-8e3f-dfd4001c228c', '30ee894b-0ca0-5bdb-9acc-8212a7e64871', null, 'OPTION_VALUE', '2d8c16d7-306f-5933-9df7-9e4c3f4a93fd', '5ee055a6-597a-5b1a-b234-d7af8706062b', null),
  ('8875f572-ed25-5842-a906-86f58f614eb2', '30ee894b-0ca0-5bdb-9acc-8212a7e64871', null, 'OPTION_VALUE', '88ef6bb6-953b-561d-99e5-06b448a5ef5e', '962e83a5-285a-51ed-aa16-c6f503a08717', null);

update price_definition set status = 'AUTHORIZED', authorized_by = 'owner — entrevista 2026-09-15', authorized_at = '2026-09-15T00:00:00Z' where id = '30ee894b-0ca0-5bdb-9acc-8212a7e64871';

insert into price_definition (id, item_id, price_book_id, component, model, amount, rate, rate_unit, min_charge, min_quantity, max_quantity, status, valid_from, valid_to, version, supersedes_id, authorized_by, authorized_at) values
  ('36a68321-22fb-519b-89b6-cce462a4270a', 'bdf332e7-d03b-5223-bd25-4006aebb5885', '096f98ae-3ce4-5963-b616-95dd648cff87', 'ITEM', 'EXACT_QUANTITY_MATRIX', null, null, null, null, null, null, 'DRAFT', '2026-09-15T00:00:00Z', null, 1, null, null, null);

insert into price_break (price_definition_id, quantity, amount, amount_basis) values
  ('36a68321-22fb-519b-89b6-cce462a4270a', 100, 105.00, 'TOTAL'),
  ('36a68321-22fb-519b-89b6-cce462a4270a', 250, 190.00, 'TOTAL'),
  ('36a68321-22fb-519b-89b6-cce462a4270a', 500, 310.00, 'TOTAL'),
  ('36a68321-22fb-519b-89b6-cce462a4270a', 1000, 530.00, 'TOTAL'),
  ('36a68321-22fb-519b-89b6-cce462a4270a', 1500, 730.00, 'TOTAL'),
  ('36a68321-22fb-519b-89b6-cce462a4270a', 2000, 920.00, 'TOTAL'),
  ('36a68321-22fb-519b-89b6-cce462a4270a', 2500, 1110.00, 'TOTAL'),
  ('36a68321-22fb-519b-89b6-cce462a4270a', 3000, 1290.00, 'TOTAL'),
  ('36a68321-22fb-519b-89b6-cce462a4270a', 4000, 1640.00, 'TOTAL'),
  ('36a68321-22fb-519b-89b6-cce462a4270a', 5000, 1970.00, 'TOTAL');

insert into price_condition (id, price_definition_id, price_rule_id, kind, option_definition_id, option_value_id, decoration_method_id) values
  ('129b6cb5-5425-5889-a9a8-060110225dc4', '36a68321-22fb-519b-89b6-cce462a4270a', null, 'OPTION_VALUE', '6b6d28da-50aa-5a02-a72d-f422d1c47385', '6c8d9fe8-1684-581b-a6cd-b6f491921d93', null),
  ('8d06ec4d-6bfc-5d81-9b3b-4a0844083b6c', '36a68321-22fb-519b-89b6-cce462a4270a', null, 'OPTION_VALUE', '2d8c16d7-306f-5933-9df7-9e4c3f4a93fd', '7f23e854-f1dd-5037-a4dc-51c45a67239f', null),
  ('fff02e68-d93d-50d0-b26d-68d71cb19454', '36a68321-22fb-519b-89b6-cce462a4270a', null, 'OPTION_VALUE', '88ef6bb6-953b-561d-99e5-06b448a5ef5e', 'a870c3e7-836e-56f6-b2d9-ca01693a6adb', null);

update price_definition set status = 'AUTHORIZED', authorized_by = 'owner — entrevista 2026-09-15', authorized_at = '2026-09-15T00:00:00Z' where id = '36a68321-22fb-519b-89b6-cce462a4270a';

insert into price_definition (id, item_id, price_book_id, component, model, amount, rate, rate_unit, min_charge, min_quantity, max_quantity, status, valid_from, valid_to, version, supersedes_id, authorized_by, authorized_at) values
  ('df9c531f-7051-57a7-920f-231527815fb0', 'bdf332e7-d03b-5223-bd25-4006aebb5885', '096f98ae-3ce4-5963-b616-95dd648cff87', 'ITEM', 'EXACT_QUANTITY_MATRIX', null, null, null, null, null, null, 'DRAFT', '2026-09-15T00:00:00Z', null, 1, null, null, null);

insert into price_break (price_definition_id, quantity, amount, amount_basis) values
  ('df9c531f-7051-57a7-920f-231527815fb0', 100, 60.00, 'TOTAL'),
  ('df9c531f-7051-57a7-920f-231527815fb0', 250, 105.00, 'TOTAL'),
  ('df9c531f-7051-57a7-920f-231527815fb0', 500, 165.00, 'TOTAL'),
  ('df9c531f-7051-57a7-920f-231527815fb0', 1000, 280.00, 'TOTAL'),
  ('df9c531f-7051-57a7-920f-231527815fb0', 1500, 390.00, 'TOTAL'),
  ('df9c531f-7051-57a7-920f-231527815fb0', 2000, 490.00, 'TOTAL'),
  ('df9c531f-7051-57a7-920f-231527815fb0', 2500, 590.00, 'TOTAL'),
  ('df9c531f-7051-57a7-920f-231527815fb0', 3000, 680.00, 'TOTAL'),
  ('df9c531f-7051-57a7-920f-231527815fb0', 4000, 870.00, 'TOTAL'),
  ('df9c531f-7051-57a7-920f-231527815fb0', 5000, 1050.00, 'TOTAL');

insert into price_condition (id, price_definition_id, price_rule_id, kind, option_definition_id, option_value_id, decoration_method_id) values
  ('73b4ab7a-0888-5d98-a8eb-b3f42b90bc4f', 'df9c531f-7051-57a7-920f-231527815fb0', null, 'OPTION_VALUE', '6b6d28da-50aa-5a02-a72d-f422d1c47385', '6c8d9fe8-1684-581b-a6cd-b6f491921d93', null),
  ('be5ed249-3787-5de2-92d2-9d2d0ebd8ccd', 'df9c531f-7051-57a7-920f-231527815fb0', null, 'OPTION_VALUE', '2d8c16d7-306f-5933-9df7-9e4c3f4a93fd', '7f23e854-f1dd-5037-a4dc-51c45a67239f', null),
  ('834440a2-fe05-53f0-82a8-4890c8a08c3a', 'df9c531f-7051-57a7-920f-231527815fb0', null, 'OPTION_VALUE', '88ef6bb6-953b-561d-99e5-06b448a5ef5e', 'e0fca6f5-5c68-5228-ba67-285240d73123', null);

update price_definition set status = 'AUTHORIZED', authorized_by = 'owner — entrevista 2026-09-15', authorized_at = '2026-09-15T00:00:00Z' where id = 'df9c531f-7051-57a7-920f-231527815fb0';

insert into price_definition (id, item_id, price_book_id, component, model, amount, rate, rate_unit, min_charge, min_quantity, max_quantity, status, valid_from, valid_to, version, supersedes_id, authorized_by, authorized_at) values
  ('b1baf1bc-d18f-5716-bdab-1d024ea72452', 'bdf332e7-d03b-5223-bd25-4006aebb5885', '096f98ae-3ce4-5963-b616-95dd648cff87', 'ITEM', 'EXACT_QUANTITY_MATRIX', null, null, null, null, null, null, 'DRAFT', '2026-09-15T00:00:00Z', null, 1, null, null, null);

insert into price_break (price_definition_id, quantity, amount, amount_basis) values
  ('b1baf1bc-d18f-5716-bdab-1d024ea72452', 100, 35.00, 'TOTAL'),
  ('b1baf1bc-d18f-5716-bdab-1d024ea72452', 250, 60.00, 'TOTAL'),
  ('b1baf1bc-d18f-5716-bdab-1d024ea72452', 500, 90.00, 'TOTAL'),
  ('b1baf1bc-d18f-5716-bdab-1d024ea72452', 1000, 150.00, 'TOTAL'),
  ('b1baf1bc-d18f-5716-bdab-1d024ea72452', 1500, 210.00, 'TOTAL'),
  ('b1baf1bc-d18f-5716-bdab-1d024ea72452', 2000, 260.00, 'TOTAL'),
  ('b1baf1bc-d18f-5716-bdab-1d024ea72452', 2500, 320.00, 'TOTAL'),
  ('b1baf1bc-d18f-5716-bdab-1d024ea72452', 3000, 370.00, 'TOTAL'),
  ('b1baf1bc-d18f-5716-bdab-1d024ea72452', 4000, 460.00, 'TOTAL'),
  ('b1baf1bc-d18f-5716-bdab-1d024ea72452', 5000, 560.00, 'TOTAL');

insert into price_condition (id, price_definition_id, price_rule_id, kind, option_definition_id, option_value_id, decoration_method_id) values
  ('aa2795a9-396e-58a0-970c-63ab86519ee0', 'b1baf1bc-d18f-5716-bdab-1d024ea72452', null, 'OPTION_VALUE', '6b6d28da-50aa-5a02-a72d-f422d1c47385', '6c8d9fe8-1684-581b-a6cd-b6f491921d93', null),
  ('a868258c-eb0f-5fa9-869f-bfcf5a004531', 'b1baf1bc-d18f-5716-bdab-1d024ea72452', null, 'OPTION_VALUE', '2d8c16d7-306f-5933-9df7-9e4c3f4a93fd', '7f23e854-f1dd-5037-a4dc-51c45a67239f', null),
  ('d89d6f39-a551-557f-bab7-be82c3c0c5df', 'b1baf1bc-d18f-5716-bdab-1d024ea72452', null, 'OPTION_VALUE', '88ef6bb6-953b-561d-99e5-06b448a5ef5e', '962e83a5-285a-51ed-aa16-c6f503a08717', null);

update price_definition set status = 'AUTHORIZED', authorized_by = 'owner — entrevista 2026-09-15', authorized_at = '2026-09-15T00:00:00Z' where id = 'b1baf1bc-d18f-5716-bdab-1d024ea72452';

insert into price_definition (id, item_id, price_book_id, component, model, amount, rate, rate_unit, min_charge, min_quantity, max_quantity, status, valid_from, valid_to, version, supersedes_id, authorized_by, authorized_at) values
  ('31effc48-5cbc-5734-a906-d2700a219361', 'bdf332e7-d03b-5223-bd25-4006aebb5885', '096f98ae-3ce4-5963-b616-95dd648cff87', 'ITEM', 'EXACT_QUANTITY_MATRIX', null, null, null, null, null, null, 'DRAFT', '2026-09-15T00:00:00Z', null, 1, null, null, null);

insert into price_break (price_definition_id, quantity, amount, amount_basis) values
  ('31effc48-5cbc-5734-a906-d2700a219361', 100, 150.00, 'TOTAL'),
  ('31effc48-5cbc-5734-a906-d2700a219361', 250, 270.00, 'TOTAL'),
  ('31effc48-5cbc-5734-a906-d2700a219361', 500, 440.00, 'TOTAL'),
  ('31effc48-5cbc-5734-a906-d2700a219361', 1000, 750.00, 'TOTAL'),
  ('31effc48-5cbc-5734-a906-d2700a219361', 1500, 1030.00, 'TOTAL'),
  ('31effc48-5cbc-5734-a906-d2700a219361', 2000, 1300.00, 'TOTAL'),
  ('31effc48-5cbc-5734-a906-d2700a219361', 2500, 1570.00, 'TOTAL'),
  ('31effc48-5cbc-5734-a906-d2700a219361', 3000, 1825.00, 'TOTAL'),
  ('31effc48-5cbc-5734-a906-d2700a219361', 4000, 2320.00, 'TOTAL'),
  ('31effc48-5cbc-5734-a906-d2700a219361', 5000, 2790.00, 'TOTAL');

insert into price_condition (id, price_definition_id, price_rule_id, kind, option_definition_id, option_value_id, decoration_method_id) values
  ('75850398-e4dd-56ee-9947-ae3f954f98ed', '31effc48-5cbc-5734-a906-d2700a219361', null, 'OPTION_VALUE', '6b6d28da-50aa-5a02-a72d-f422d1c47385', '4ba304fa-8abc-549d-bdf6-2e4918c37cf0', null),
  ('c661d161-7297-57b5-99d6-c0cb78252295', '31effc48-5cbc-5734-a906-d2700a219361', null, 'OPTION_VALUE', '2d8c16d7-306f-5933-9df7-9e4c3f4a93fd', '7f23e854-f1dd-5037-a4dc-51c45a67239f', null),
  ('696e6225-4c09-5efd-b572-511198e362d2', '31effc48-5cbc-5734-a906-d2700a219361', null, 'OPTION_VALUE', '88ef6bb6-953b-561d-99e5-06b448a5ef5e', 'a870c3e7-836e-56f6-b2d9-ca01693a6adb', null);

update price_definition set status = 'AUTHORIZED', authorized_by = 'owner — entrevista 2026-09-15', authorized_at = '2026-09-15T00:00:00Z' where id = '31effc48-5cbc-5734-a906-d2700a219361';

insert into price_definition (id, item_id, price_book_id, component, model, amount, rate, rate_unit, min_charge, min_quantity, max_quantity, status, valid_from, valid_to, version, supersedes_id, authorized_by, authorized_at) values
  ('9d97a3ce-c39c-5439-a730-0f84ed65772e', 'bdf332e7-d03b-5223-bd25-4006aebb5885', '096f98ae-3ce4-5963-b616-95dd648cff87', 'ITEM', 'EXACT_QUANTITY_MATRIX', null, null, null, null, null, null, 'DRAFT', '2026-09-15T00:00:00Z', null, 1, null, null, null);

insert into price_break (price_definition_id, quantity, amount, amount_basis) values
  ('9d97a3ce-c39c-5439-a730-0f84ed65772e', 100, 85.00, 'TOTAL'),
  ('9d97a3ce-c39c-5439-a730-0f84ed65772e', 250, 150.00, 'TOTAL'),
  ('9d97a3ce-c39c-5439-a730-0f84ed65772e', 500, 235.00, 'TOTAL'),
  ('9d97a3ce-c39c-5439-a730-0f84ed65772e', 1000, 400.00, 'TOTAL'),
  ('9d97a3ce-c39c-5439-a730-0f84ed65772e', 1500, 550.00, 'TOTAL'),
  ('9d97a3ce-c39c-5439-a730-0f84ed65772e', 2000, 690.00, 'TOTAL'),
  ('9d97a3ce-c39c-5439-a730-0f84ed65772e', 2500, 835.00, 'TOTAL'),
  ('9d97a3ce-c39c-5439-a730-0f84ed65772e', 3000, 960.00, 'TOTAL'),
  ('9d97a3ce-c39c-5439-a730-0f84ed65772e', 4000, 1230.00, 'TOTAL'),
  ('9d97a3ce-c39c-5439-a730-0f84ed65772e', 5000, 1485.00, 'TOTAL');

insert into price_condition (id, price_definition_id, price_rule_id, kind, option_definition_id, option_value_id, decoration_method_id) values
  ('3c085184-b66b-595d-86e0-3d5e9bf17fff', '9d97a3ce-c39c-5439-a730-0f84ed65772e', null, 'OPTION_VALUE', '6b6d28da-50aa-5a02-a72d-f422d1c47385', '4ba304fa-8abc-549d-bdf6-2e4918c37cf0', null),
  ('768b976d-06a4-51a1-8824-b69ad7746e31', '9d97a3ce-c39c-5439-a730-0f84ed65772e', null, 'OPTION_VALUE', '2d8c16d7-306f-5933-9df7-9e4c3f4a93fd', '7f23e854-f1dd-5037-a4dc-51c45a67239f', null),
  ('ba0fcf0a-67bf-5e1f-b37e-af8b0a7c28d1', '9d97a3ce-c39c-5439-a730-0f84ed65772e', null, 'OPTION_VALUE', '88ef6bb6-953b-561d-99e5-06b448a5ef5e', 'e0fca6f5-5c68-5228-ba67-285240d73123', null);

update price_definition set status = 'AUTHORIZED', authorized_by = 'owner — entrevista 2026-09-15', authorized_at = '2026-09-15T00:00:00Z' where id = '9d97a3ce-c39c-5439-a730-0f84ed65772e';

insert into price_definition (id, item_id, price_book_id, component, model, amount, rate, rate_unit, min_charge, min_quantity, max_quantity, status, valid_from, valid_to, version, supersedes_id, authorized_by, authorized_at) values
  ('f4e7580c-28b9-5830-a7cc-61fe03265f9b', 'bdf332e7-d03b-5223-bd25-4006aebb5885', '096f98ae-3ce4-5963-b616-95dd648cff87', 'ITEM', 'EXACT_QUANTITY_MATRIX', null, null, null, null, null, null, 'DRAFT', '2026-09-15T00:00:00Z', null, 1, null, null, null);

insert into price_break (price_definition_id, quantity, amount, amount_basis) values
  ('f4e7580c-28b9-5830-a7cc-61fe03265f9b', 100, 50.00, 'TOTAL'),
  ('f4e7580c-28b9-5830-a7cc-61fe03265f9b', 250, 85.00, 'TOTAL'),
  ('f4e7580c-28b9-5830-a7cc-61fe03265f9b', 500, 130.00, 'TOTAL'),
  ('f4e7580c-28b9-5830-a7cc-61fe03265f9b', 1000, 220.00, 'TOTAL'),
  ('f4e7580c-28b9-5830-a7cc-61fe03265f9b', 1500, 300.00, 'TOTAL'),
  ('f4e7580c-28b9-5830-a7cc-61fe03265f9b', 2000, 370.00, 'TOTAL'),
  ('f4e7580c-28b9-5830-a7cc-61fe03265f9b', 2500, 450.00, 'TOTAL'),
  ('f4e7580c-28b9-5830-a7cc-61fe03265f9b', 3000, 525.00, 'TOTAL'),
  ('f4e7580c-28b9-5830-a7cc-61fe03265f9b', 4000, 650.00, 'TOTAL'),
  ('f4e7580c-28b9-5830-a7cc-61fe03265f9b', 5000, 790.00, 'TOTAL');

insert into price_condition (id, price_definition_id, price_rule_id, kind, option_definition_id, option_value_id, decoration_method_id) values
  ('2ec31525-8d10-5898-86ca-b0769413e6b0', 'f4e7580c-28b9-5830-a7cc-61fe03265f9b', null, 'OPTION_VALUE', '6b6d28da-50aa-5a02-a72d-f422d1c47385', '4ba304fa-8abc-549d-bdf6-2e4918c37cf0', null),
  ('9359ca8e-d5ac-5330-bfe8-b1e8bb396ec3', 'f4e7580c-28b9-5830-a7cc-61fe03265f9b', null, 'OPTION_VALUE', '2d8c16d7-306f-5933-9df7-9e4c3f4a93fd', '7f23e854-f1dd-5037-a4dc-51c45a67239f', null),
  ('5dbe2ca0-11ad-5db2-8746-0888bf34769a', 'f4e7580c-28b9-5830-a7cc-61fe03265f9b', null, 'OPTION_VALUE', '88ef6bb6-953b-561d-99e5-06b448a5ef5e', '962e83a5-285a-51ed-aa16-c6f503a08717', null);

update price_definition set status = 'AUTHORIZED', authorized_by = 'owner — entrevista 2026-09-15', authorized_at = '2026-09-15T00:00:00Z' where id = 'f4e7580c-28b9-5830-a7cc-61fe03265f9b';

insert into price_rule (id, price_book_id, code, label, kind, amount, exclusivity_key, status, valid_from, valid_to, version, supersedes_id, authorized_by, authorized_at) values
  ('ec424fd2-eceb-5bc1-a89a-71a8a1d7e0f2', '096f98ae-3ce4-5963-b616-95dd648cff87', 'size_2xl', 'Recargo talla 2XL', 'ADD_PER_UNIT', 2.00, 'size_surcharge', 'DRAFT', '2026-09-15T00:00:00Z', null, 1, null, null, null);

insert into price_condition (id, price_definition_id, price_rule_id, kind, option_definition_id, option_value_id, decoration_method_id) values
  ('08265c4a-e090-53bb-9ebb-d101f9137f80', null, 'ec424fd2-eceb-5bc1-a89a-71a8a1d7e0f2', 'OPTION_VALUE', 'a97d9ec8-975a-5050-9395-32390402b7d4', '5ca8e6b4-f0ff-51a3-b0ae-b9f01e69bbef', null);

insert into price_rule_assignment (price_rule_id, item_id) values
  ('ec424fd2-eceb-5bc1-a89a-71a8a1d7e0f2', '9a6c6eef-c05c-5abf-933b-786ee7f3f570'),
  ('ec424fd2-eceb-5bc1-a89a-71a8a1d7e0f2', '21ae272d-619f-537f-b7bf-5bb418fc2dac');

update price_rule set status = 'AUTHORIZED', authorized_by = 'owner — entrevista 2026-09-15', authorized_at = '2026-09-15T00:00:00Z' where id = 'ec424fd2-eceb-5bc1-a89a-71a8a1d7e0f2';

insert into price_rule (id, price_book_id, code, label, kind, amount, exclusivity_key, status, valid_from, valid_to, version, supersedes_id, authorized_by, authorized_at) values
  ('edd636ba-656a-5869-a71a-5b86d9c14767', '096f98ae-3ce4-5963-b616-95dd648cff87', 'size_3xl', 'Recargo talla 3XL', 'ADD_PER_UNIT', 3.00, 'size_surcharge', 'DRAFT', '2026-09-15T00:00:00Z', null, 1, null, null, null);

insert into price_condition (id, price_definition_id, price_rule_id, kind, option_definition_id, option_value_id, decoration_method_id) values
  ('0b17d60d-b3e7-598c-9be0-ca0b8e10c2e0', null, 'edd636ba-656a-5869-a71a-5b86d9c14767', 'OPTION_VALUE', 'a97d9ec8-975a-5050-9395-32390402b7d4', '264942b4-192e-51b3-ac8d-627a27aba558', null);

insert into price_rule_assignment (price_rule_id, item_id) values
  ('edd636ba-656a-5869-a71a-5b86d9c14767', '9a6c6eef-c05c-5abf-933b-786ee7f3f570'),
  ('edd636ba-656a-5869-a71a-5b86d9c14767', '21ae272d-619f-537f-b7bf-5bb418fc2dac');

update price_rule set status = 'AUTHORIZED', authorized_by = 'owner — entrevista 2026-09-15', authorized_at = '2026-09-15T00:00:00Z' where id = 'edd636ba-656a-5869-a71a-5b86d9c14767';

insert into presentation (id, item_id, locale, occasion, display_name, short_description, aliases, seo_keywords, is_default, status) values
  ('94affc29-cef8-59a4-8d64-374ba6e54657', '9a7f52f4-b893-5808-bfa2-21ccace19965', 'es', null, 'Tarjeta de presentación Tradicional', null, array['tarjeta', 'tarjetas', 'tarjeta de negocio']::text[], '{}'::text[], true, 'DRAFT'),
  ('4e7884b7-80d2-5a40-8185-0cd2dac360e7', 'ccabd035-6447-550f-b8be-08e8b6d8d0e2', 'es', null, 'Tarjeta de presentación Premium / Gloss', null, array['tarjeta', 'tarjetas', 'tarjeta de negocio']::text[], '{}'::text[], true, 'DRAFT'),
  ('15b94c3e-e18c-5fca-b618-3df8f362e9a7', 'bdf332e7-d03b-5223-bd25-4006aebb5885', 'es', null, 'Flyers', null, array['volante', 'volantes']::text[], '{}'::text[], true, 'DRAFT'),
  ('6a612bc1-9624-545c-8912-49f299c1cd7c', '3e66e8e4-e365-5ee3-bf9f-30486288969d', 'es', null, 'Imanes para vehículo — par 2 × 1 ft', null, array['imán', 'iman', 'imanes']::text[], '{}'::text[], true, 'DRAFT'),
  ('f56be274-3c1d-5628-80e4-f4e676b25397', '9a6c6eef-c05c-5abf-933b-786ee7f3f570', 'es', null, 'Camiseta de algodón cuello redondo', null, array['playera', 'camiseta']::text[], '{}'::text[], true, 'DRAFT'),
  ('8e834581-2b9e-5326-a0b8-5b43cc8f437c', '21ae272d-619f-537f-b7bf-5bb418fc2dac', 'es', null, 'Camiseta Dry Fit / poliéster', null, '{}'::text[], '{}'::text[], true, 'DRAFT'),
  ('124bf1ee-33d2-5e63-a823-61542e22a8a0', '2118b3b7-4ef6-555d-8053-41f1742976e8', 'es', null, 'Gorra', null, '{}'::text[], '{}'::text[], true, 'DRAFT'),
  ('f36c3493-69ac-5461-a948-c5614ac38f80', 'a698953b-aeb0-566d-bbb3-90ac476952cc', 'es', null, 'X-Banner completo', null, '{}'::text[], '{}'::text[], true, 'DRAFT'),
  ('53a04995-c6a8-59d3-9e20-c211b340d8b2', 'a09ec452-c755-538b-8752-25bda134d265', 'es', null, 'Estructura X-Banner', null, '{}'::text[], '{}'::text[], true, 'DRAFT'),
  ('a0bc0eb7-9141-5dad-be21-46fda0aa1553', 'dbe194c9-7ed9-51ac-bb56-d7013a89e7a4', 'es', null, 'Gráfica impresa X-Banner', null, '{}'::text[], '{}'::text[], true, 'DRAFT'),
  ('3b9247d8-ab79-5bbb-b150-fb32893b178b', '1b0c6cb7-d15e-5bf0-854c-4744babe1eb8', 'es', null, 'Yard Sign / Realtor Sign 18 × 24 in', null, array['letrero de jardín']::text[], '{}'::text[], true, 'DRAFT'),
  ('6155a2bf-f4e9-50a0-8eca-cc94fd0a40ea', 'd3b32238-191c-5c5d-82f3-4701c7ed538a', 'es', null, 'Estaca para yard sign', null, '{}'::text[], '{}'::text[], true, 'DRAFT'),
  ('a04ed2d0-0b07-5166-b05b-f9d826d9306d', '170e3c75-5a85-5350-be2f-ace4ed45d8c6', 'es', null, 'Aplicación DTF sobre artículo del cliente', null, '{}'::text[], '{}'::text[], true, 'DRAFT'),
  ('b1d6bea2-22ff-52c7-9dc2-87ec9e069817', 'e5c4d1af-5064-5752-9947-fdf31848ba3c', 'es', null, 'DTF Transfer individual', null, '{}'::text[], '{}'::text[], true, 'DRAFT'),
  ('88db25aa-3cbc-51c9-a571-77ee2d0470b3', '917f0a15-aba6-514a-a9ef-b1fa57f7f77a', 'es', null, 'DTF Gang Sheet', null, '{}'::text[], '{}'::text[], true, 'DRAFT'),
  ('91af4f5d-8afd-51e1-a36f-8331dcccffd9', '201c6543-8beb-5c7a-8ac9-0ef4860d971f', 'es', null, 'Invitación para evento', null, '{}'::text[], '{}'::text[], true, 'DRAFT'),
  ('7f0ff8c7-3a3e-566f-8c1b-d91f3bc7165b', '9a7f52f4-b893-5808-bfa2-21ccace19965', 'en', null, 'Business card', null, array['Business card', 'business cards', 'traditional business card']::text[], '{}'::text[], true, 'DRAFT'),
  ('6210f7e0-0261-5600-a493-a0ae8f09b28e', 'ccabd035-6447-550f-b8be-08e8b6d8d0e2', 'en', null, 'Premium business card', null, array['Premium business card', 'business card', 'business cards', 'gloss business card']::text[], '{}'::text[], true, 'DRAFT'),
  ('25597f62-5952-5b37-b053-9fc79e184ee7', 'bdf332e7-d03b-5223-bd25-4006aebb5885', 'en', null, 'Flyer', null, array['Flyer', 'flyers']::text[], '{}'::text[], true, 'DRAFT'),
  ('bd80d345-f505-5657-90c7-17df5582f079', '3e66e8e4-e365-5ee3-bf9f-30486288969d', 'en', null, 'Vehicle magnet', null, array['Vehicle magnet', 'car magnet', 'magnets']::text[], '{}'::text[], true, 'DRAFT'),
  ('b1d3a088-b3da-5c70-8f9b-afc0d6ce37a4', '9a6c6eef-c05c-5abf-933b-786ee7f3f570', 'en', null, 'cotton crew-neck T-shirt', null, array['cotton crew-neck T-shirt', 't-shirt', 'tee']::text[], '{}'::text[], true, 'DRAFT'),
  ('4b096979-36b8-5ce3-ab96-f0fa7dcd1720', '1b0c6cb7-d15e-5bf0-854c-4744babe1eb8', 'en', null, 'yard sign', null, array['yard sign', 'realtor sign', 'lawn sign', 'real estate sign', 'coroplast sign']::text[], '{}'::text[], true, 'DRAFT'),
  ('50bd1630-c34a-5e6a-a462-a75641fd1c2a', '201c6543-8beb-5c7a-8ac9-0ef4860d971f', 'es', 'XV', 'Invitación para XV años', null, '{}'::text[], '{}'::text[], false, 'DRAFT'),
  ('ba8d866e-4ae9-5920-85e0-5b1685cf71f8', '201c6543-8beb-5c7a-8ac9-0ef4860d971f', 'es', 'Boda', 'Invitación para boda', null, '{}'::text[], '{}'::text[], false, 'DRAFT'),
  ('7055e785-ea24-510a-a469-4488082b2507', '201c6543-8beb-5c7a-8ac9-0ef4860d971f', 'es', 'Cumpleaños', 'Invitación para cumpleaños', null, '{}'::text[], '{}'::text[], false, 'DRAFT');

insert into publication_assignment (profile_id, item_id, presentation_id, is_included, sort) values
  ('8ef033f9-a5c7-57da-baa7-8addb251b66d', '9a7f52f4-b893-5808-bfa2-21ccace19965', null, true, null),
  ('52f5224c-a0aa-5807-9446-8fa8afebe8c0', '9a7f52f4-b893-5808-bfa2-21ccace19965', null, true, null),
  ('8ef033f9-a5c7-57da-baa7-8addb251b66d', 'ccabd035-6447-550f-b8be-08e8b6d8d0e2', null, true, null),
  ('52f5224c-a0aa-5807-9446-8fa8afebe8c0', 'ccabd035-6447-550f-b8be-08e8b6d8d0e2', null, true, null),
  ('8ef033f9-a5c7-57da-baa7-8addb251b66d', 'bdf332e7-d03b-5223-bd25-4006aebb5885', null, true, null),
  ('52f5224c-a0aa-5807-9446-8fa8afebe8c0', 'bdf332e7-d03b-5223-bd25-4006aebb5885', null, true, null),
  ('8ef033f9-a5c7-57da-baa7-8addb251b66d', '3e66e8e4-e365-5ee3-bf9f-30486288969d', null, true, null),
  ('52f5224c-a0aa-5807-9446-8fa8afebe8c0', '3e66e8e4-e365-5ee3-bf9f-30486288969d', null, true, null);

insert into source_reference (id, entity_type, entity_id, field, source_kind, source_locator, payload, captured_at) values
  ('8fbafcf5-22fa-56f1-a299-11358c9f565a', 'catalog_item', '9a7f52f4-b893-5808-bfa2-21ccace19965', null, 'LEGACY_ID', 'MIG1-O-008', null, '2026-09-29T00:00:00Z'),
  ('e1604193-a971-51e8-86ae-5b8078727ef8', 'catalog_item', '9a7f52f4-b893-5808-bfa2-21ccace19965', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!OFERTAS[Oferta_ID=MIG1-O-008]', null, '2026-09-29T00:00:00Z'),
  ('e0e71280-bff7-560c-a14b-d7d1ef641067', 'catalog_item', 'ccabd035-6447-550f-b8be-08e8b6d8d0e2', null, 'LEGACY_ID', 'MIG1-O-009', null, '2026-09-29T00:00:00Z'),
  ('62e21f06-bbe6-5edf-9b67-1dfcb768efbf', 'catalog_item', 'ccabd035-6447-550f-b8be-08e8b6d8d0e2', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!OFERTAS[Oferta_ID=MIG1-O-009]', null, '2026-09-29T00:00:00Z'),
  ('a1b105e6-1c5b-5172-8310-26ae6a961863', 'catalog_item', 'bdf332e7-d03b-5223-bd25-4006aebb5885', null, 'LEGACY_ID', 'MIG2-O-036', null, '2026-09-29T00:00:00Z'),
  ('f02652fb-8078-578a-9c3b-cdf93ca07336', 'catalog_item', 'bdf332e7-d03b-5223-bd25-4006aebb5885', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!OFERTAS[Oferta_ID=MIG2-O-036]', null, '2026-09-29T00:00:00Z'),
  ('c26a75d3-6187-5f81-8a14-4c778cc350bf', 'catalog_item', '3e66e8e4-e365-5ee3-bf9f-30486288969d', null, 'LEGACY_ID', 'MIGF-O-015', null, '2026-09-29T00:00:00Z'),
  ('cca321d1-038b-57db-a5a5-e64cb9e8139f', 'catalog_item', '3e66e8e4-e365-5ee3-bf9f-30486288969d', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!OFERTAS[Oferta_ID=MIGF-O-015]', null, '2026-09-29T00:00:00Z'),
  ('3fb5b3bd-4b92-54e2-8cea-d20441c8beb6', 'catalog_item', '9a6c6eef-c05c-5abf-933b-786ee7f3f570', null, 'LEGACY_ID', 'MIG1-O-004', null, '2026-09-29T00:00:00Z'),
  ('de3f84cc-f56f-5025-9121-c52be4b33d8c', 'catalog_item', '9a6c6eef-c05c-5abf-933b-786ee7f3f570', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!OFERTAS[Oferta_ID=MIG1-O-004]', null, '2026-09-29T00:00:00Z'),
  ('9bce807c-d4bf-5a91-929d-b168614f0756', 'catalog_item', '21ae272d-619f-537f-b7bf-5bb418fc2dac', null, 'LEGACY_ID', 'MIG1-O-005', null, '2026-09-29T00:00:00Z'),
  ('97a56291-edbb-540f-a84e-e09e00de2775', 'catalog_item', '21ae272d-619f-537f-b7bf-5bb418fc2dac', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!OFERTAS[Oferta_ID=MIG1-O-005]', null, '2026-09-29T00:00:00Z'),
  ('48a8324d-47d8-56b0-914f-e3115acc2833', 'catalog_item', '2118b3b7-4ef6-555d-8053-41f1742976e8', null, 'LEGACY_ID', 'MIG2-O-018', null, '2026-09-29T00:00:00Z'),
  ('c513fdaa-c96d-5da4-b677-b2a128afa248', 'catalog_item', '2118b3b7-4ef6-555d-8053-41f1742976e8', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!OFERTAS[Oferta_ID=MIG2-O-018]', null, '2026-09-29T00:00:00Z'),
  ('42c8d2e6-3899-5afa-829d-2c28e4754205', 'catalog_item', '2118b3b7-4ef6-555d-8053-41f1742976e8', null, 'LEGACY_ID', 'MIGF-O-004', null, '2026-09-29T00:00:00Z'),
  ('d2d82ba4-bd20-5c01-8c7e-343391322abc', 'catalog_item', '2118b3b7-4ef6-555d-8053-41f1742976e8', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!OFERTAS[Oferta_ID=MIGF-O-004]', null, '2026-09-29T00:00:00Z'),
  ('82fad9fe-dd58-5606-8fec-e3c310ff51d7', 'catalog_item', 'a698953b-aeb0-566d-bbb3-90ac476952cc', null, 'LEGACY_ID', 'MIG1-O-003', null, '2026-09-29T00:00:00Z'),
  ('dcb7838c-c824-5d30-acca-b753d82858dd', 'catalog_item', 'a698953b-aeb0-566d-bbb3-90ac476952cc', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!OFERTAS[Oferta_ID=MIG1-O-003]', null, '2026-09-29T00:00:00Z'),
  ('ad20299b-5b6f-5f42-8be1-83c78b76993e', 'catalog_item', 'a09ec452-c755-538b-8752-25bda134d265', null, 'LEGACY_ID', 'MIG1-O-021', null, '2026-09-29T00:00:00Z'),
  ('99a0a50e-0bef-55b9-aa9e-8fdcae1bfed6', 'catalog_item', 'a09ec452-c755-538b-8752-25bda134d265', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!OFERTAS[Oferta_ID=MIG1-O-021]', null, '2026-09-29T00:00:00Z'),
  ('3dd3e372-7b61-528e-8e86-fff29b9cd217', 'catalog_item', 'dbe194c9-7ed9-51ac-bb56-d7013a89e7a4', null, 'LEGACY_ID', 'OWN-O-003', null, '2026-09-29T00:00:00Z'),
  ('8d99c15d-5d7f-52e0-8dcf-2134ac2f13d7', 'catalog_item', 'dbe194c9-7ed9-51ac-bb56-d7013a89e7a4', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!OFERTAS[Oferta_ID=OWN-O-003]', null, '2026-09-29T00:00:00Z'),
  ('aedf2041-8290-5d5b-80b4-7c1a9303ec44', 'catalog_item', '1b0c6cb7-d15e-5bf0-854c-4744babe1eb8', null, 'LEGACY_ID', 'MIG1-O-020', null, '2026-09-29T00:00:00Z'),
  ('b24dd7b5-6488-592d-bc65-d1c758f796ae', 'catalog_item', '1b0c6cb7-d15e-5bf0-854c-4744babe1eb8', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!OFERTAS[Oferta_ID=MIG1-O-020]', null, '2026-09-29T00:00:00Z'),
  ('acfbfc96-9d7c-5db3-8549-11ab493e464d', 'catalog_item', '170e3c75-5a85-5350-be2f-ace4ed45d8c6', null, 'LEGACY_ID', 'MIG1-O-018', null, '2026-09-29T00:00:00Z'),
  ('a574af73-7aac-5979-83a2-92a3886c5e9d', 'catalog_item', '170e3c75-5a85-5350-be2f-ace4ed45d8c6', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!OFERTAS[Oferta_ID=MIG1-O-018]', null, '2026-09-29T00:00:00Z'),
  ('8a0d18d6-c574-56de-916e-7869d1c88191', 'catalog_item', 'e5c4d1af-5064-5752-9947-fdf31848ba3c', null, 'LEGACY_ID', 'MIG1-O-015', null, '2026-09-29T00:00:00Z'),
  ('97b27df0-7162-578a-a5bd-5e7787acf782', 'catalog_item', 'e5c4d1af-5064-5752-9947-fdf31848ba3c', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!OFERTAS[Oferta_ID=MIG1-O-015]', null, '2026-09-29T00:00:00Z'),
  ('f85720b5-cf66-5268-bb53-ece7a1a39bad', 'catalog_item', '917f0a15-aba6-514a-a9ef-b1fa57f7f77a', null, 'LEGACY_ID', 'MIG1-O-016', null, '2026-09-29T00:00:00Z'),
  ('6331f054-3b3a-533b-8123-fe65b32ef4fd', 'catalog_item', '917f0a15-aba6-514a-a9ef-b1fa57f7f77a', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!OFERTAS[Oferta_ID=MIG1-O-016]', null, '2026-09-29T00:00:00Z'),
  ('0421a4cd-435e-5b66-a0cb-7522cfa1dc89', 'catalog_item', '201c6543-8beb-5c7a-8ac9-0ef4860d971f', null, 'LEGACY_ID', 'MIGF-O-010', null, '2026-09-29T00:00:00Z'),
  ('c2160998-8d2f-513e-85b4-cf718de952af', 'catalog_item', '201c6543-8beb-5c7a-8ac9-0ef4860d971f', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!OFERTAS[Oferta_ID=MIGF-O-010]', null, '2026-09-29T00:00:00Z'),
  ('a2b8f626-ffe0-5d0d-8b34-e35c13b70443', 'catalog_item', 'd3b32238-191c-5c5d-82f3-4701c7ed538a', null, 'OWNER_INTERVIEW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!OFERTAS[MIG1-O-020].Notas', '{"quote":"OWNER 2026-09-15: NO incluye estaca metálica por defecto; no proveedor estable. Accesorio futuro."}'::jsonb, '2026-09-29T00:00:00Z'),
  ('3c8bea18-8c6b-56e3-8386-1635e42dafc4', 'presentation', '50bd1630-c34a-5e6a-a462-a75641fd1c2a', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRESENTACIONES[MIGF-PR-001]', null, '2026-09-29T00:00:00Z'),
  ('f166012a-0b59-5f01-afb5-6a15f4fbb362', 'presentation', 'ba8d866e-4ae9-5920-85e0-5b1685cf71f8', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRESENTACIONES[MIGF-PR-002]', null, '2026-09-29T00:00:00Z'),
  ('d641e467-784d-583f-a315-ab18c5da2c7d', 'presentation', '7055e785-ea24-510a-a469-4488082b2507', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRESENTACIONES[MIGF-PR-003]', null, '2026-09-29T00:00:00Z'),
  ('64126461-b6e3-5643-a03e-52bfe0013add', 'price_definition', '9a87e43c-ab7e-51e6-89e9-893e1bd25dd1', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRECIOS[MIG1-P-009,MIG1-P-010,MIG2-P-016,OWN-P-091,OWN-P-095,OWN-P-099,OWN-P-103,OWN-P-107,OWN-P-111,OWN-P-115]', '{"excelModel":"Por tabla","excelBase":"Por paquete"}'::jsonb, '2026-09-29T00:00:00Z'),
  ('05e0b2c1-3c5e-5a40-a00f-dc5989ffc86c', 'price_definition', '03a51d6b-d081-5e34-9440-1acecbaa56fa', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRECIOS[MIG1-P-011,MIG1-P-012,MIG2-P-017,OWN-P-092,OWN-P-096,OWN-P-100,OWN-P-104,OWN-P-108,OWN-P-112,OWN-P-116]', '{"excelModel":"Por tabla","excelBase":"Por paquete"}'::jsonb, '2026-09-29T00:00:00Z'),
  ('1dd8ba6a-4807-51c1-8258-275f2616b5ea', 'price_definition', 'dcc95a7b-3754-5c46-a9bd-77e50f6c5023', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRECIOS[MIG1-P-013,MIG1-P-014,MIG2-P-018,OWN-P-093,OWN-P-097,OWN-P-101,OWN-P-105,OWN-P-109,OWN-P-113,OWN-P-117]', '{"excelModel":"Por tabla","excelBase":"Por paquete"}'::jsonb, '2026-09-29T00:00:00Z'),
  ('d2677677-4fcb-50f5-87e6-e89b4058355c', 'price_definition', '6b58997b-77a5-5651-bf42-a8016a0ab078', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRECIOS[MIG1-P-015,MIG1-P-016,MIG2-P-019,OWN-P-094,OWN-P-098,OWN-P-102,OWN-P-106,OWN-P-110,OWN-P-114,OWN-P-118]', '{"excelModel":"Por tabla","excelBase":"Por paquete"}'::jsonb, '2026-09-29T00:00:00Z'),
  ('e3447921-4bb3-5f9a-be12-4ea78983bd3d', 'price_definition', '81d31998-26d4-52ef-988e-14d650a7734f', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRECIOS[MIGF-P-001]', '{"excelModel":"Fijo","excelBase":"Total"}'::jsonb, '2026-09-29T00:00:00Z'),
  ('df3815a1-5dac-5f69-b684-730d334b0ec0', 'price_definition', '4c7d3f82-9ffe-56ca-83db-96f373801d5b', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRECIOS[OWN-P-001,OWN-P-004,OWN-P-007,OWN-P-010,OWN-P-013,OWN-P-016,OWN-P-019,OWN-P-022,OWN-P-025,OWN-P-028]', '{"excelModel":"Por tabla","excelBase":"Por paquete"}'::jsonb, '2026-09-29T00:00:00Z'),
  ('f4858932-62a5-5968-8147-c0921d625cf9', 'price_definition', '75322a4c-325f-5d0f-ae1f-dee9fcf869b5', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRECIOS[OWN-P-002,OWN-P-005,OWN-P-008,OWN-P-011,OWN-P-014,OWN-P-017,OWN-P-020,OWN-P-023,OWN-P-026,OWN-P-029]', '{"excelModel":"Por tabla","excelBase":"Por paquete"}'::jsonb, '2026-09-29T00:00:00Z'),
  ('545afc64-6c93-5d84-9d30-527dbf02fde4', 'price_definition', '30ee894b-0ca0-5bdb-9acc-8212a7e64871', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRECIOS[OWN-P-003,OWN-P-006,OWN-P-009,OWN-P-012,OWN-P-015,OWN-P-018,OWN-P-021,OWN-P-024,OWN-P-027,OWN-P-030]', '{"excelModel":"Por tabla","excelBase":"Por paquete"}'::jsonb, '2026-09-29T00:00:00Z'),
  ('333fc0ba-33c2-58e8-b22e-7de904f7dd6d', 'price_definition', '36a68321-22fb-519b-89b6-cce462a4270a', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRECIOS[OWN-P-031,OWN-P-034,OWN-P-037,OWN-P-040,OWN-P-043,OWN-P-046,OWN-P-049,OWN-P-052,OWN-P-055,OWN-P-058]', '{"excelModel":"Por tabla","excelBase":"Por paquete"}'::jsonb, '2026-09-29T00:00:00Z'),
  ('23319c59-f3a5-5c13-8fea-b0a9448cdcf0', 'price_definition', 'df9c531f-7051-57a7-920f-231527815fb0', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRECIOS[OWN-P-032,OWN-P-035,OWN-P-038,OWN-P-041,OWN-P-044,OWN-P-047,OWN-P-050,OWN-P-053,OWN-P-056,OWN-P-059]', '{"excelModel":"Por tabla","excelBase":"Por paquete"}'::jsonb, '2026-09-29T00:00:00Z'),
  ('8cd9eff9-2637-5fda-95e8-f20afbff1205', 'price_definition', 'b1baf1bc-d18f-5716-bdab-1d024ea72452', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRECIOS[OWN-P-033,OWN-P-036,OWN-P-039,OWN-P-042,OWN-P-045,OWN-P-048,OWN-P-051,OWN-P-054,OWN-P-057,OWN-P-060]', '{"excelModel":"Por tabla","excelBase":"Por paquete"}'::jsonb, '2026-09-29T00:00:00Z'),
  ('9b2591f1-e536-5dc5-ba2c-689db9c10a3a', 'price_definition', '31effc48-5cbc-5734-a906-d2700a219361', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRECIOS[OWN-P-061,OWN-P-064,OWN-P-067,OWN-P-070,OWN-P-073,OWN-P-076,OWN-P-079,OWN-P-082,OWN-P-085,OWN-P-088]', '{"excelModel":"Por tabla","excelBase":"Por paquete"}'::jsonb, '2026-09-29T00:00:00Z'),
  ('3ee2ed9d-0fcc-5f7e-80b7-c621c4064dbd', 'price_definition', '9d97a3ce-c39c-5439-a730-0f84ed65772e', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRECIOS[OWN-P-062,OWN-P-065,OWN-P-068,OWN-P-071,OWN-P-074,OWN-P-077,OWN-P-080,OWN-P-083,OWN-P-086,OWN-P-089]', '{"excelModel":"Por tabla","excelBase":"Por paquete"}'::jsonb, '2026-09-29T00:00:00Z'),
  ('83ebd443-bd69-53b0-9433-1e86acc640cb', 'price_definition', 'f4e7580c-28b9-5830-a7cc-61fe03265f9b', null, 'EXCEL_ROW', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRECIOS[OWN-P-063,OWN-P-066,OWN-P-069,OWN-P-072,OWN-P-075,OWN-P-078,OWN-P-081,OWN-P-084,OWN-P-087,OWN-P-090]', '{"excelModel":"Por tabla","excelBase":"Por paquete"}'::jsonb, '2026-09-29T00:00:00Z'),
  ('0cd9321d-aeec-5334-9091-e5a09577f7cc', 'catalog_item', 'a698953b-aeb0-566d-bbb3-90ac476952cc', null, 'HISTORICAL_PRICE_EVIDENCE', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRECIOS[MIG1-P-003]', '{"amount":"65","currency":"USD","condition":"tamaño=24 x 63 in","status":"HISTÓRICO / NO AUTORIZADO para cotizar (OWNER 2026-09-15)"}'::jsonb, '2026-09-29T00:00:00Z'),
  ('89b81bf3-aff4-5803-889c-960cda92fca6', 'catalog_item', 'a698953b-aeb0-566d-bbb3-90ac476952cc', null, 'HISTORICAL_PRICE_EVIDENCE', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRECIOS[MIG1-P-004]', '{"amount":"85","currency":"USD","condition":"tamaño=32 x 72 in","status":"HISTÓRICO / NO AUTORIZADO para cotizar (OWNER 2026-09-15)"}'::jsonb, '2026-09-29T00:00:00Z'),
  ('68c556bd-19ef-5637-b899-ded3fb486c1b', 'catalog_item', 'a698953b-aeb0-566d-bbb3-90ac476952cc', null, 'HISTORICAL_PRICE_EVIDENCE', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRECIOS[MIG2-P-009]', '{"amount":"120","currency":"USD","condition":"tamaño=48 x 78 in","status":"HISTÓRICO / NO AUTORIZADO para cotizar (OWNER 2026-09-15)"}'::jsonb, '2026-09-29T00:00:00Z'),
  ('92227eef-69e2-594a-8b1a-a7293ecb032e', 'catalog_item', '9a6c6eef-c05c-5abf-933b-786ee7f3f570', null, 'HISTORICAL_PRICE_EVIDENCE', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRECIOS[MIG1-P-005]', '{"amount":"15","currency":"USD","condition":null,"status":"HISTÓRICO / NO AUTORIZADO para cotizar (OWNER 2026-09-15)"}'::jsonb, '2026-09-29T00:00:00Z'),
  ('cb8c55d8-a54d-5f0e-b4ec-b2ac441b330b', 'catalog_item', '21ae272d-619f-537f-b7bf-5bb418fc2dac', null, 'HISTORICAL_PRICE_EVIDENCE', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRECIOS[MIG1-P-006]', '{"amount":"18","currency":"USD","condition":null,"status":"HISTÓRICO / NO AUTORIZADO para cotizar (OWNER 2026-09-15)"}'::jsonb, '2026-09-29T00:00:00Z'),
  ('d6395fd9-c68c-5877-9c83-4f92a49f7998', 'catalog_item', '2118b3b7-4ef6-555d-8053-41f1742976e8', null, 'HISTORICAL_PRICE_EVIDENCE', 'Design_To_Go_Catalog_v1.2_RC_MANGO_TANGO.xlsx!PRECIOS[MIG2-P-013]', '{"amount":"15","currency":"USD","condition":null,"status":"HISTÓRICO / NO AUTORIZADO para cotizar (OWNER 2026-09-15)"}'::jsonb, '2026-09-29T00:00:00Z');

insert into decision_record (id, code, title, status, statement, decided_by, decided_at, source) values
  ('db24b9eb-4a5e-5b53-bf03-d8c6f59217da', 'P1-01', 'Confirmar estado comercial de los items del slice', 'OPEN', 'Estados sembrados provisionalmente desde v1.2 (Activo/Candidato) o por tener precio autorizado vigente.', null, null, null),
  ('d88aeb89-2221-54dd-b981-dc0458726d5d', 'P1-03', 'Imanes: ¿2 pares = 130 USD?', 'OPEN', 'Precio autorizado 65 USD por par; por ahora FIXED con máximo 1 par.', null, null, null),
  ('383cea41-7658-5f83-85e9-174130766fed', 'P1-05', 'Alcance del recargo 2XL/3XL', 'OPEN', 'Asignado a camiseta algodón y Dry Fit (notas del dueño en esos registros). Polo, sudaderas: pendiente.', null, null, null),
  ('f46682fa-4712-50eb-a3ce-c1c693ab2f7a', 'P2-01', 'Lista de tallas y segmentos', 'OPEN', 'S–XL sembradas como vocabulario provisional; el Excel sólo documenta 2XL/3XL.', null, null, null),
  ('695e89aa-7267-5b76-b42d-c95f7bc2c5b7', 'OD-SIZE-SURCHARGE', 'Recargos por talla', 'DECIDED', '2XL = +2 USD y 3XL = +3 USD por pieza, donde la regla aplique; nunca a gorras.', 'owner', '2026-09-29T00:00:00Z', 'OWNER_DECISIONS_POST_AUDIT.md'),
  ('d2d8fe66-2037-53d4-b1d9-2e76b6834fc0', 'DQ-GORRA-TALLA', 'Talla 2XL/3XL en Gorra no se migra', 'DECIDED', 'OWN-OP-007 era un defecto del Excel (C07, BR-026).', 'architecture', '2026-09-29T00:00:00Z', 'STEP 03 MIGRATION-MAPPING §2');

insert into decision_subject (decision_id, entity_type, entity_id) values
  ('db24b9eb-4a5e-5b53-bf03-d8c6f59217da', 'catalog_item', '9a7f52f4-b893-5808-bfa2-21ccace19965'),
  ('db24b9eb-4a5e-5b53-bf03-d8c6f59217da', 'catalog_item', 'ccabd035-6447-550f-b8be-08e8b6d8d0e2'),
  ('db24b9eb-4a5e-5b53-bf03-d8c6f59217da', 'catalog_item', 'bdf332e7-d03b-5223-bd25-4006aebb5885'),
  ('db24b9eb-4a5e-5b53-bf03-d8c6f59217da', 'catalog_item', '3e66e8e4-e365-5ee3-bf9f-30486288969d'),
  ('db24b9eb-4a5e-5b53-bf03-d8c6f59217da', 'catalog_item', '9a6c6eef-c05c-5abf-933b-786ee7f3f570'),
  ('db24b9eb-4a5e-5b53-bf03-d8c6f59217da', 'catalog_item', '21ae272d-619f-537f-b7bf-5bb418fc2dac'),
  ('db24b9eb-4a5e-5b53-bf03-d8c6f59217da', 'catalog_item', '2118b3b7-4ef6-555d-8053-41f1742976e8'),
  ('db24b9eb-4a5e-5b53-bf03-d8c6f59217da', 'catalog_item', 'a698953b-aeb0-566d-bbb3-90ac476952cc'),
  ('db24b9eb-4a5e-5b53-bf03-d8c6f59217da', 'catalog_item', 'a09ec452-c755-538b-8752-25bda134d265'),
  ('db24b9eb-4a5e-5b53-bf03-d8c6f59217da', 'catalog_item', 'dbe194c9-7ed9-51ac-bb56-d7013a89e7a4'),
  ('db24b9eb-4a5e-5b53-bf03-d8c6f59217da', 'catalog_item', '1b0c6cb7-d15e-5bf0-854c-4744babe1eb8'),
  ('db24b9eb-4a5e-5b53-bf03-d8c6f59217da', 'catalog_item', 'd3b32238-191c-5c5d-82f3-4701c7ed538a'),
  ('db24b9eb-4a5e-5b53-bf03-d8c6f59217da', 'catalog_item', '170e3c75-5a85-5350-be2f-ace4ed45d8c6'),
  ('db24b9eb-4a5e-5b53-bf03-d8c6f59217da', 'catalog_item', 'e5c4d1af-5064-5752-9947-fdf31848ba3c'),
  ('db24b9eb-4a5e-5b53-bf03-d8c6f59217da', 'catalog_item', '917f0a15-aba6-514a-a9ef-b1fa57f7f77a'),
  ('db24b9eb-4a5e-5b53-bf03-d8c6f59217da', 'catalog_item', '201c6543-8beb-5c7a-8ac9-0ef4860d971f'),
  ('d88aeb89-2221-54dd-b981-dc0458726d5d', 'catalog_item', '3e66e8e4-e365-5ee3-bf9f-30486288969d'),
  ('383cea41-7658-5f83-85e9-174130766fed', 'catalog_item', '9a6c6eef-c05c-5abf-933b-786ee7f3f570'),
  ('383cea41-7658-5f83-85e9-174130766fed', 'catalog_item', '21ae272d-619f-537f-b7bf-5bb418fc2dac'),
  ('f46682fa-4712-50eb-a3ce-c1c693ab2f7a', 'catalog_item', '9a6c6eef-c05c-5abf-933b-786ee7f3f570'),
  ('f46682fa-4712-50eb-a3ce-c1c693ab2f7a', 'catalog_item', '21ae272d-619f-537f-b7bf-5bb418fc2dac'),
  ('695e89aa-7267-5b76-b42d-c95f7bc2c5b7', 'catalog_item', '9a6c6eef-c05c-5abf-933b-786ee7f3f570'),
  ('695e89aa-7267-5b76-b42d-c95f7bc2c5b7', 'catalog_item', '21ae272d-619f-537f-b7bf-5bb418fc2dac'),
  ('695e89aa-7267-5b76-b42d-c95f7bc2c5b7', 'catalog_item', '2118b3b7-4ef6-555d-8053-41f1742976e8'),
  ('d2d8fe66-2037-53d4-b1d9-2e76b6834fc0', 'catalog_item', '2118b3b7-4ef6-555d-8053-41f1742976e8');
